### PR TITLE
Replaced <></> with Fragment tag

### LINKED ISSUE #4233: On hovering the Link widget, a tooltip should be displayed
### Environment
The latest `develop`

### What is the expected behaviour?
On hovering the widget, a tooltip should be displayed if a tooltip is provided in the widget inspector.

### What is the current behaviour?
With a tooltip provided, on hover, there is no tip that is being displayed

### How to reproduce the issue?

1. Add Link widget from widget manager
2. Click on the config handler of the widget to open up the widget inspector
3. Provide a tooltip (expected type is a **String)**
4. Hover on the widget

### PR DESCRIPTION
**Pull request by zainbinfurqan**
Replaced <></> with Fragment tag

fixes #4233

### CODE REVIEW

**Comment by arpitnath** [comment]
Hi @zainbinfurqan, 
Thank you for showing interest to contribute to ToolJet.
A pull request would be considered valid if it satisfies the following conditions:
1. The pull request should be raised against the `develop` branch.
2. The pull request should be accompanied by a valid issue, which should be assigned to the contributor by the ToolJet team.
3. The pull request should be accompanied by a valid description.

Closing this pull request as it does not satisfy the above conditions.
You can read more about contributing to ToolJet [here](https://docs.tooljet.com/docs/category/contributing-guide) and find valid hacktoberfest issues [here](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest).

**Comment by zainbinfurqan** [comment]
@arpitnath  I did comment on the issue which Assign to me can you please have a look on it? [issue](https://github.com/ToolJet/ToolJet/issues/4233)

**Comment by zainbinfurqan** [comment]
I am excited & want to contribute to this repo can you please help me out with it?

**Comment by arpitnath** [comment]
owh, I see. Its really hard for us to figure out which PR is linked to issues if the PR has no issues linked.

**Comment by arpitnath** [comment]
Resolves #4233

**Comment by zainbinfurqan** [comment]
@arpitnath  who will review the MR?

**Comment by gsmithun4** [comment]
deployed https://tj-4545.herokuapp.com

**Comment by gsmithun4** [comment]
@zainbinfurqan Please fix the lint error

**Comment by withshubh** [comment]
Closing the PR. ref: https://github.com/ToolJet/ToolJet/pull/4609#issuecomment-1294833735

**Pull request closed without merging**
