### PR TITLE
Updated documentation for Toggle Switch Component

### LINKED ISSUE #10845: [docs]: Update the documentation for the Toggle Switch Component
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/toggle-switch-v2

**Formatting updates:**
- Update the formatting based on the [latest](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide) guidelines.
- For each h2 (created using ##), remove 24px padding-bottom. The `div` that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom". 

**Content updates:**
- Update the "Devices" content to a table  [reference](https://docs.tooljet.com/docs/widgets/text-input#devices)

**The changes are to be implemented in two files -** 
 Next - ToolJet/docs/docs/widgets/toggle-switch-v2.md
 Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/toggle-switch-v2.md

 _**The deadline for this task is 3 days from the day of the assignment. Please feel free to reach out to us in our [Slack community](https://tooljet.com/slack) if you have any questions.**_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by Naman13112004**
Removed padding bottom and replaced Devices content with a table.
Fixes #10845

### CODE REVIEW

**Comment by Naman13112004** [comment]
Hi @PriteshKiri 
I have created a PR, kindly review it.
Also, can you please tell me if this will be tagged for hacktoberfest or not.
Wanted to know since I came to know about open source from hacktoberfest.

**Comment by PriteshKiri** [comment]
Thanks for the quick PR.

Yes, this PR will be counted in `hacktoberfest`

**Review by RudraPratik30 — CHANGES_REQUESTED** [review]
Hey @Naman13112004 
Please make sure all the fx are bold and not inclosed within single tick.
Refer [style guide](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide/#1-text-formatting-guidelines) for more.

**Comment by Naman13112004** [comment]
Hello @RudraPratik30 sir, 
I have done the requested changes and made sure that all the `fx` are changed to <b>fx</b>
Kindly review the same
Thanks

**Comment by RudraPratik30** [comment]
Hey @Naman13112004, can you please use ** ** to make something bold, instead of using <b> HTML tag, because that might cause errors in markdown sometimes, so avoid using HTML tags in markdown.
Thanks!

**Comment by Naman13112004** [comment]
Thank you @RudraPratik30 sir for the information.
I didn't know that it could cause errors in markdown.
I have done the changes as required.
Kindly review the same.

**Review by RudraPratik30 — APPROVED** [review]
Hey @Naman13112004 , approving the changes from my end and forwarding it to the team for final review.
Thanks for contributing, your PR will be merged by the end of this week.

**Comment by Avii-KS** [comment]
Hi @PriteshKiri  can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by RudraPratik30** [comment]
Hey @Avii-KS, the issue is resolved and the PR is under review, can you please check other issues with `community contribution` label?

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Pull request merged**
