### PR TITLE
Option to toggle display  of column hide ::[ Table widget ]

### LINKED ISSUE #4481: Option to toggle display  of column hide ::[ Table widget ]
### Is your proposal related to a problem?

Currently no option to hide disable column icon

### Describe the solution you'd like

Add property to toggle show/hide of column hide option.

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #4481

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2x6h5fg Option to switch on/off show hide button : Table widget](https://app.clickup.com/t/2x6h5fg)

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey, please have this option turned on by default.

And for existing table that doesn't have a value for this option, fallback to `false`, that is, do not display it.

Also, please discuss with Shubhendra for documentation

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hi, table is crashing when I click on it.

https://user-images.githubusercontent.com/20333972/201632687-f88fccca-89dd-40f0-a9f8-5fa1d9e544d0.mov

**Comment by stepinfwd** [comment]
closing this , opened https://github.com/ToolJet/ToolJet/pull/4831

**Pull request closed without merging**
