### PR TITLE
feat: Add DTO for organization create

### LINKED ISSUE #4634: [improvement] create a DTO for title length validation in workspace
### Is your proposal related to a problem?

The title length validation of the workspace should have a data transfer object.

### Describe the solution you'd like

Create a DTO for title length validation of workspace

reference: https://github.com/ToolJet/ToolJet/pull/4402#discussion_r1005465650

### PR DESCRIPTION
**Pull request by TheLearneer**
Fixes #4634

### CODE REVIEW

**Comment by gsmithun4** [comment]
@TheLearneer Please fix the lint errors

**Comment by TheLearneer** [comment]
@gsmithun4 @withshubh I guess there is some issue with github actions.
Please look into it.
It's been running for over an hour now 😓

**Comment by TheLearneer** [comment]
Hi @gsmithun4 any idea what is the problem here and how I may solve it?

**Comment by gsmithun4** [comment]
@TheLearneer Please rebase

**Comment by TheLearneer** [comment]
Done @gsmithun4 🙏

**Review by gsmithun4 — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @TheLearneer  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
