### PR TITLE
Update homepage design

### PR DESCRIPTION
**Pull request by gondar00**
- Move all apps link under folders
- Update logo
- Minor bug fixes
- Update plugin icons

### CODE REVIEW

**Review by arpitnath — APPROVED** [review]

**Comment by shubh22** [comment]
Task linked: [CU-333cwmc Comments are not visible on the sidebar comments section.](https://app.clickup.com/t/333cwmc)

**Comment by shubh22** [comment]
Task linked: [CU-85zrgxx3d Scrolling should be limited to work area.](https://app.clickup.com/t/85zrgxx3d)

**Comment by shubh22** [comment]
Task linked: [CU-85zrgx2xa Added comments are not visible after going back to dashboard and opening app again](https://app.clickup.com/t/85zrgx2xa)

**Comment by shubh22** [comment]
Task linked: [CU-85zrhaxt8 Add new workspace option is available in single workspace](https://app.clickup.com/t/85zrhaxt8)

**Review by arpitnath — APPROVED** [review]

**Pull request merged**
