### PR TITLE
Add a minimal delay to promise

### PR DESCRIPTION
**Pull request by prasadwalvekar**
### Cause 

Loading happens too fast and the skeleton gets replaced immediately with content.

### Changes

Added a function that 
1. Creates a new `Promise` that resolves after 400ms
2. Waits for both the timer Promise and network request `Promise` to resolve
3. Returns the value

This handles following scenarios -
1. The network returns the data in less than a 400ms. The combined promise will resolve when the timer fires after 400ms. As both promises need to be complete, the function will return after 400ms.
2. The network request takes exactly or more than 400ms. The combined promise will resolve when the network request returns. As the timer has already expired while waiting, the response is available immediately.

### Loom 

https://www.loom.com/share/b325a9242a144f83b404a18638adfb2b

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
@prasadwalvekar 
I don't agree with slowing down the interaction intentionally. We should be aiming for quicker interactions. 

I think the flicker happens due to the difference in the height of the table in its empty state and the loading state. Let's say we set `height` or `min-height` for the table, the resizing issue won't happen and it should solve the flicker issue, right?

**Comment by prasadwalvekar** [comment]
@Navaneeth-pk Setting a `min-height` was already implemented and it does not seem to be working. 

See that min-height has already been set ->

https://github.com/prasadwalvekar/ToolJet/blob/develop/frontend/src/HomePage/HomePage.jsx#L125

**Comment by Navaneeth-pk** [comment]
Can you please try making the min height 900px and see if flickering issue is less/gone ?

**Comment by prasadwalvekar** [comment]
@Navaneeth-pk 

> Can you please try making the min height 900px and see if flickering issue is less/gone ?

No. It does not fix the issue.

**Comment by Navaneeth-pk** [comment]
Let's close this issue then, I think flicker is better than slowing down the page load :)

**Pull request closed without merging**
