### PR TITLE
Setup pipeline using Github actions 

### LINKED ISSUE #746: Setup pipeline using github actions
Setup Github actions workflow to run build, lint and test stages for both client and server.
We should enable for public fork pull request runs as well.

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #746 

- Checks for push to pull requests to develop branch
- Run build check and lint check parallel

### CODE REVIEW

**Comment by arpitnath** [comment]
Todo: Test Job

**Comment by akshaysasidrn** [comment]
@arpitnath let's remove the test run since the config fails? We can add for tests with db setup as a follow up.

**Review by akshaysasidrn — APPROVED** [review]

**Comment by arpitnath** [comment]
> @arpitnath let's remove the test run since the config fails? We can add for tests with db setup as a follow up.

yeah okay. removing the test run

**Comment by arpitnath** [comment]
`npm ci` was failing due to no `name` property in the root package.json

**Review by akshaysasidrn — APPROVED** [review]

**Comment by akshaysasidrn** [comment]
@arpitnath I have cherry picked commit from this branch and created a new [pull request](https://github.com/ToolJet/ToolJet/pull/1539).  Shall I close the PR?

**Comment by arpitnath** [comment]
> @arpitnath I have cherry picked commit from this branch and created a new [pull request](https://github.com/ToolJet/ToolJet/pull/1539). Shall I close the PR?

Yeah sure 🙌🏻

**Pull request closed without merging**
