### PR TITLE
cursor added to form-check-input[type=checkbox] at tabler.scss

### PR DESCRIPTION
**Pull request by nazrul7711**
its working 
Screenshot 2023-04-27 at 11 01 50 AM

### CODE REVIEW

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@nazrul7711 Thanks for the PR!

There are so many changes which are irrelevant to the issue. Can you please revert all those changes?

**Comment by nazrul7711** [comment]
hi kavin, i included these packages to get tooljet running in my pc . it was throwing errors that following packages are missing. should i just modify the css file and make a pull request?

**Comment by kavinvenkatachalam** [comment]
Hey @nazrul7711 I can understand. Can you please close this & open a new PR for this issue and push only the files relevant to the issue?

**Comment by nazrul7711** [comment]
Ok I will do that

**Pull request closed without merging**
