### PR TITLE
[docs]: Fix typos in widgets docs

### PR DESCRIPTION
**Pull request by nisusam**

### CODE REVIEW

**Comment by RudraPratik30** [comment]
Hey @nisusam, thanks for contributing!
The changes look good to me. Can you please replicate the same changes in the LTS version as well so that the docs are consistent?
Please follow the file path for LTS version: ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/

**Comment by nisusam** [comment]
@RudraPratik30, the same changes were fixed in the LTS version too.

**Review by RudraPratik30 — APPROVED** [review]
Hey @nisusam, thanks for contributing!
The changes look good to me, forwarding it to the team for final review.
Your PR will be merged soon, thanks again!

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Review by johnsoncherian — APPROVED** [review]

**Pull request merged**
