### PR TITLE
Disabled home page scrolling

### PR DESCRIPTION
**Pull request by Syed-Ansar**
Scrolling Disabled 

Fixed issue #2860 

In the below video. I was scrolling you can see that the scrolling bar is disabled.

https://user-images.githubusercontent.com/82027712/175774372-33ccd2c9-83d3-4444-8f86-330f05446043.mp4

### CODE REVIEW

**Comment by gsmithun4** [comment]
deployed https://tj-3395.herokuapp.com/

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Case

Test Cases | Steps | Result
-- | -- | --
Should not be able to scroll the home page. | Create several application. | Applications are created.
  | Go to homepage. | Homepage is displayed.
  | Try scrolling. | Scrolling is disabled.


</body>
</html>

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@Syed-Ansar Adding `overflow-y: hidden` to the `body` tag will disable the scroll through out the app. For lower screen resolution, `profile` page cannot be scrolled to the bottom of the page. Attaching the screenshot

image

cc: @gsmithun4 @sherfin94

**Comment by gsmithun4** [comment]
> @Syed-Ansar Adding `overflow-y: hidden` to the `body` tag will disable the scroll through out the app. For lower screen resolution, `profile` page cannot be scrolled to the bottom of the page. Attaching the screenshot
> 
> image
> 
> cc: @gsmithun4 @sherfin94

@kavinvenkatachalam can you please suggest any alternate solution?

**Comment by kavinvenkatachalam** [comment]
@gsmithun4 Instead of changing `overflow`, we can change the `page-body` class height and set `min-height` to enable scrolling for smaller screen resolution. We can change it as follows

`  height: calc(100vh - 2.5rem - 48px);
  min-height: 500px;`

cc: @Syed-Ansar

**Comment by withshubh** [comment]
@Syed-Ansar - Please update the PR with requested changes.

**Comment by Syed-Ansar** [comment]
> @Syed-Ansar - Please update the PR with requested changes.

Hey @withshubh I have my semester exams going on so I can't do it at present I will do it after my exams.

**Comment by withshubh** [comment]
> > @Syed-Ansar - Please update the PR with requested changes.
> 
> Hey @withshubh I have my semester exams going on so I can't do it at present I will do it after my exams.

Hey @Syed-Ansar  
Are you willing to continue working on the PR?

**Pull request closed without merging**
