### PR TITLE
[localization] translate strings (editor & header) section in Indonesian

### PR DESCRIPTION
**Pull request by depapp**
add Indonesian (Bahasa Indonesia) localization (id.json) for `editor` and `header` section
this PR solve #4293

### CODE REVIEW

**Comment by depapp** [comment]
hello guys @withshubh @Navaneeth-pk
could you please help me to review this PR 🙇🏻
thanks

**Review by withshubh — APPROVED** [review]

**Comment by depapp** [comment]
thanks for the approval @withshubh 🙇🏻 
since I don't have permission to merge di PR, could you please help. thanks

**Comment by Navaneeth-pk** [comment]
@depapp please resolve the merge conflicts.

**Comment by depapp** [comment]
> @depapp please resolve the merge conflicts.

sure @Navaneeth-pk 🍻

**Comment by depapp** [comment]
@Navaneeth-pk could you please help to recheck? 🙇🏻

**Pull request merged**
