### PR TITLE
[Feature] : selection/copy btn text from preview code block

### LINKED ISSUE #1548: Generated code hinter preview is not selectable/copiable
### Environment

Ubuntu 20.04, Enterprise deployment
### What is the expected behaviour?

The user should be able to copy/select generated code preview.
### What is the current behaviour?

The user is not able to copy/select generated code preview.

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #1548

### CODE REVIEW

**Comment by arpitnath** [comment]
loom: https://www.loom.com/share/288ea47acdc84c74a52935cae92cf35f

**Comment by sherfin94** [comment]
Hey @arpitnath, looks like there are some subtle issues. When I click on a code field, I have to somehow double click and 'halt' the code preview there before I can copy it. If I try to click and drag, it goes away.


https://user-images.githubusercontent.com/20333972/146398248-c69028e2-c5f3-401f-9ec3-abe4aabac4c2.mov

**Comment by sherfin94** [comment]
Not sure if this is a major issue, but I seem to be able to have multiple code previews open at once:

https://user-images.githubusercontent.com/20333972/146398735-66464a4b-fb90-466b-9936-a707cd404ffe.mov

**Comment by arpitnath** [comment]
Closing this PR.
Ref: #3155

**Pull request closed without merging**
