### PR TITLE
Translated App Card in Spanish 

### LINKED ISSUE #4188: [localization] Translate App Card in Spanish
### Is your proposal related to a problem?

Add translations for the App Card in Spanish

### Describe the solution you'd like

The strings need to be translated:

Screenshot 2022-09-30 at 3 43 04 PM

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

### PR DESCRIPTION
**Pull request by vedant-z**
Fixes #4188

### CODE REVIEW

**Comment by vedant-z** [comment]
@withshubh Please review this

**Comment by Navaneeth-pk** [comment]
@vedant-z  please add proper titles for PRs.

**Comment by vedant-z** [comment]
@Navaneeth-pk So sorry sir 

I have made the necessary changes

**Comment by withshubh** [comment]
Closing the PR as the issue was not assigned to you. Please do not create PRs unless assigned otherwise we will have to mark them as invalid or spam.

**Pull request closed without merging**
