### PR TITLE
Add preview for Multiselect and Datepicker happyPaths

### PR DESCRIPTION
**Pull request by emidhun**
Fixes: #3736

### CODE REVIEW

**Review by ajith-k-v — COMMENTED** [review]
@emidhun Date picker spec is failing please check.
Screenshot 2022-09-02 at 1 44 18 PM

**Comment by emidhun** [comment]
> @emidhun Date picker spec is failing please check. Screenshot 2022-09-02 at 1 44 18 PM

@ajith-k-v  The failure was due to a bug, not because of the spec.
The issue is fixed on develop now, I will rebase the branch with base develop.

**Comment by emidhun** [comment]
@ajith-k-v Resolved conflicts and commented few lines of code since the bug is not fixed yet.
Please review.
Screenshot 2022-09-14 at 10 15 46 AM
Screenshot 2022-09-14 at 11 24 30 AM

**Review by ajith-k-v — APPROVED** [review]
LGTM

**Pull request merged**
