### PR TITLE
Fix broken image link

### PR DESCRIPTION
**Pull request by ArthiSiva**

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
These images are working as expected ( you can see that here https://docs.tooljet.io/docs/widgets/Image ) . Please do not spam.

**Comment by ArthiSiva** [comment]
These are not working when we try to open in github

**Comment by Navaneeth-pk** [comment]
As I mentioned in the other PR, these files are not meant to be read on GitHub, our documentation is generated using Docusaurus framework.

**Comment by ArthiSiva** [comment]
But users while trying to get context of the project they might try to check the github files. I was a bit confused on going through the md files. Since all the md files show the alt text without any redirection. So thought of editing. This will really help new joiners for the next hacktoberfest.

**Comment by Navaneeth-pk** [comment]
Sorry, those md files are not readme files. They are for generating documents using Docusaurus. The generated documentation is available at http://docs.tooljet.io.

**Comment by ArthiSiva** [comment]
But we can get enough context of the page by checking the md files. Even that should have good links. The broken ones saying 404 error must be removed.

**Comment by ArthiSiva** [comment]
@Navaneeth-pk This PR is for the enhancement of the current approach, making it universal. Using a complete url. Instead of the one that would work only on the website

**Comment by ArthiSiva** [comment]
https://github.com/ToolJet/ToolJet/blob/develop/img/widgets/datepicker/datepicker.gif

**Comment by Navaneeth-pk** [comment]
Sorry, as I have explained in your PR, the files are meant for Docusaurus framework. We do not plan to serve the images using GitHub.

**Comment by ArthiSiva** [comment]
Okay Thank you

**Comment by ArthiSiva** [comment]
@Navaneeth-pk Sorry for spamming. I thought that this could be an enhancement. Please don't mark as spam.

**Comment by ArthiSiva** [comment]
I tried to provide an enhancement that was not required by the project. By mistake

**Pull request closed without merging**
