### PR TITLE
fix: added background styles for number input

### LINKED ISSUE #4177: Add background color style in number input widget
## Proposed feature
Option to change and update the background color of the number input widget with the `Background color` property in the style tab.

### Description
Currently, the number widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

Screenshot 2022-10-01 at 11 51 37 AM

reference: https://github.com/ToolJet/ToolJet/pull/1721

### PR DESCRIPTION
**Pull request by carefreeav09**
Fixes #4177

### CODE REVIEW

**Review by arpitnath — CHANGES_REQUESTED** [review]
Can you please add the default value for the background color in the **configWidget.js**

**Comment by arpitnath** [comment]
@carefreeav09 Also can you fix the merge conflicts? 
Thank you 😅

**Comment by carefreeav09** [comment]
Okay, i will. Thank you.

**Comment by carefreeav09** [comment]
I accidentally committed the changes from a incorrect username. Apologies for this mess, i will close this PR and create a new one.

**Pull request closed without merging**
