### PR TITLE
Fix for failing specs on release branch

### PR DESCRIPTION
**Pull request by emidhun**

### CODE REVIEW

**Comment by emidhun** [comment]
<h2>Cypress Results</h2>
<table><tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr><tr><td>Failing :red_circle:</td><td>79</td><td>2</td><td>5</td><td>0</td><td>4223.005s</td></tr></table>
<a href="">

**Comment by emidhun** [comment]
<h2>Cypress Results</h2>
<table><tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr><tr><td>Failing :red_circle:</td><td>80</td><td>1</td><td>5</td><td>0</td><td>3958.375s</td></tr></table>
<a href="">

**Comment by emidhun** [comment]
<h2>Cypress Results</h2>
<table><tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr><tr><td>Failing :red_circle:</td><td>78</td><td>3</td><td>5</td><td>0</td><td>4224.758s</td></tr></table>
<a href="">

**Comment by emidhun** [comment]
<h2>Cypress Results</h2>
<table><tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr><tr><td>Failing :red_circle:</td><td>79</td><td>2</td><td>5</td><td>0</td><td>6088.195s</td></tr></table>
<a href="">

**Comment by emidhun** [comment]
<h2>Cypress Results</h2>
<table><tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr><tr><td>Passing :white_check_mark:</td><td>81</td><td>0</td><td>5</td><td>0</td><td>4062.899s</td></tr></table>
<a href="">

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
