### PR TITLE
[localization] issue-4188 added spanish keys for card app

### LINKED ISSUE #4188: [localization] Translate App Card in Spanish
### Is your proposal related to a problem?

Add translations for the App Card in Spanish

### Describe the solution you'd like

The strings need to be translated:

Screenshot 2022-09-30 at 3 43 04 PM

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

### PR DESCRIPTION
**Pull request by Elegidoadedo**
This PR will add spanish translations for card keys related to issue:

fixes #4188

### CODE REVIEW

**Comment by withshubh** [comment]
Please link the issue in the description.

**Comment by Elegidoadedo** [comment]
> Please link the issue in the description.

Solved @withshubh  :)

**Comment by withshubh** [comment]
Hey @Elegidoadedo - Please resolve the merge conflicts.

**Comment by Elegidoadedo** [comment]
> 

Sure, i will do it today. Thanks @withshubh

**Review by withshubh — APPROVED** [review]

**Comment by Navaneeth-pk** [comment]
@Elegidoadedo please resolve merge conflicts.

**Comment by withshubh** [comment]
Hey @Elegidoadedo - Please remove the files that are not required in this PR.

**Comment by Elegidoadedo** [comment]
> 

Done :)

**Review by withshubh — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @Elegidoadedo  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
