### PR TITLE
Changed Auto Saved text to Saved

### PR DESCRIPTION
**Pull request by kevinosborn31**
Let me know if you want me to change the loading text from "Auto Saving..." to "Saving..."
Fixes #2362

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
Yes, please change that too.
@kevinosborn31

**Comment by Navaneeth-pk** [comment]
Please resolve the lint errors.
@kevinosborn31

**Comment by kevinosborn31** [comment]
Hi @Navaneeth-pk

Resolving errors and adding the other text now.

**Comment by kevinosborn31** [comment]
Hi @Navaneeth-pk 

I have updated the text and fixed the lint issue, let me know if there are more errors but looks fine now on my end.

Thanks!
Kevin

**Pull request merged**
