### PR TITLE
docs: search text size fixed

### LINKED ISSUE #5101: [docs] resize `Search` text on search bar
### Summary

Currently, the search text on the search bar of the documentation is a bit large.
Its current value is `1rem `
set it to `0.85rem`

Screenshot 2022-12-28 at 1 42 26 PM

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs

### Steps to reproduce the issue

1. Open Docs
2. Check the search bar on top-left

### Additional Information

_No response_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by Aashish-Upadhyay-101**
#5101 
search placeholder size is set to 0.85rem

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @Aashish-Upadhyay-101 - Please do not create PRs unless the issue is assigned to you. Please follow the contributing guidelines.

**Comment by Aashish-Upadhyay-101** [comment]
> Hey @Aashish-Upadhyay-101 - Please do not create PRs unless the issue is assigned to you. Please follow the contributing guidelines.

@withshubh sorry, I will follow the guidelines next time. 😅

**Comment by withshubh** [comment]
Hey @Aashish-Upadhyay-101 - The change looks good to me.
Could you please also make a minor change to reduce the dimension of `DocSearch-Search-Icon` to height: 15px and width: 15px.
Currently its 20x20

**Comment by withshubh** [comment]
Closing this PR since there was no update for more than a month.

**Pull request closed without merging**
