### PR TITLE
show password checkbox gets enabled only on clicking on the Checkbox

### PR DESCRIPTION
**Pull request by Syed-Ansar**
show password checkbox gets enabled only on clicking on the Checkbox and label. #3267

### CODE REVIEW

**Comment by Syed-Ansar** [comment]
Hey @shah21 can you review this PR I have created another one for the same issue due to lint problems.

**Comment by shah21** [comment]
> Hey @shah21 can you review this PR I have created another one for the same issue due to lint problems.

@Syed-Ansar you could have fixed the lint issue with this PR. Please avoid creating multiple PRs for the same issue unless you have serious git issues.

**Comment by Syed-Ansar** [comment]
> > Hey @shah21 can you review this PR I have created another one for the same issue due to lint problems.
> 
> @Syed-Ansar you could have fixed the lint issue with this PR. Please avoid creating multiple PRs for the same issue unless you have serious git issues.

Okay I will do that from next time.

**Review by shah21 — APPROVED** [review]
LGTM

**Pull request merged**
