### PR TITLE
Successfully changed into Sentence case in file widgetConfig.js

### PR DESCRIPTION
**Pull request by gaurab-khanal**
Fixes the issue #7797

### CODE REVIEW

**Review by tejakummarikuntla — CHANGES_REQUESTED** [review]
Hey @gaurab-khanal.
I request you revisit issue description #7797 and be sure to make changes only for the labels mentioned in the table. Please do not make changes to any other labels of any other components.

Kindly update the PR to progress it for further review.

**Comment by gaurab-khanal** [comment]
> Hey @gaurab-khanal. I request you revisit issue description #7797 and be sure to make changes only for the labels mentioned in the table. Please do not make changes to any other labels of any other components.
> 
> Kindly update the PR to progress it for further review.

Do you mean only these table labels of all components?
image

**Comment by gaurab-khanal** [comment]
Hey @tejakummarikuntla  just made the changes. You can have a look. Waiting for the review.

**Review by tejakummarikuntla — CHANGES_REQUESTED** [review]
Hey @gaurab-khanal, please revert all the changes outside `widgetConfig.js` file

**Comment by tejakummarikuntla** [comment]
We are closing the PR due to contributor inactivity.

**Pull request closed without merging**
