### PR TITLE
canvas grid resized when resizing a component and component snaps to the nearest grid.

### LINKED ISSUE #747: Canvas grid size should be increased and decreased in steps of 30px and 10px (height and width resp)
### Description
Resize grid blocks in the canvas for resizing the widgets.
the width can be increased or decreased in steps of 30px, and height can be increased or decreased in steps of 10px.

**Note**: Repositioning of the widgets should not change the size of the grids (30 x 30).

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #747 

**Loom**: https://www.loom.com/share/79cbbdd684df49aeba68c03e94483b28

### CODE REVIEW

**Comment by arpitnath** [comment]
### Update
**Loom** : https://www.loom.com/share/1f5d2480dc794ac69e8def7665426dc5
**app**: https://tooljetpr-app.herokuapp.com/apps/03eb8f40-9eef-491f-a165-970133f7a18b

**Comment by arpitnath** [comment]
need to update the heroku app

**Comment by arpitnath** [comment]
updated app: https://tooljetpr-app.herokuapp.com/apps/03eb8f40-9eef-491f-a165-970133f7a18b

**Comment by arpitnath** [comment]
app updated: https://tooljet-pr-app.herokuapp.com/apps/99ab8fab-5353-42b9-a6e1-2573f548c473

**Comment by arpitnath** [comment]
> updated app: https://tooljetpr-app.herokuapp.com/apps/03eb8f40-9eef-491f-a165-970133f7a18b

Not working

**Comment by arpitnath** [comment]
update: 
https://www.loom.com/share/e8543ab56e5c4c59b86b0f05e067fae6

**Review by Navaneeth-pk — APPROVED** [review]

**Pull request merged**
