### PR TITLE
[docs]: Fix documentation for the QR Scanner Component

### LINKED ISSUE #11121: [docs]: Update the documentation for the QR Scanner Component
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/qr-scanner

**Content updates:**
- In the "Exposed Variables" Table, update the content in the "Description" and "How To Access" columns for the **lastDetectedValue** variable [reference](https://docs.tooljet.com/docs/widgets/text-input/#exposed-variables) ( Please just check the sentence structure from the given reference )
- In the "Events" Table, update the event name from "On Detect" to "On detect".
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" column.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/qr-scanner.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/qr-scanner.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by ArnavSingha**
updating the docs to make it easier to follow

Content updated:

In the "Exposed Variables" Table, update the content in the "Description" and "How To Access" columns for the lastDetectedValue variable [reference](https://docs.tooljet.com/docs/widgets/text-input/#exposed-variables) ( Please just check the sentence structure from the given reference )
In the "Events" Table, update the event name from "On Detect" to "On detect".
Layout Table
Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
Update the name of the first column from "Layout" to "Property"
Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
Add a full stop at the end of the sentence in the "Description" and "Expected value" column.

-----
will close #11121

### CODE REVIEW

**Comment by RudraPratik30** [comment]
Hey @ArnavSingha, thanks for contributing!
You were supposed to make changes in two versions (LTS and Next) as given in the issue, but I can see that you have made changes only in one file.
Can you please replicate the changes in other version as well, in the same PR?

**Comment by ArnavSingha** [comment]
@RudraPratik30 ok i can give me some time

**Comment by ArnavSingha** [comment]
@RudraPratik30 done it please check it out and let me know.

**Comment by RudraPratik30** [comment]
Hey @ArnavSingha!
You were supposed to make changes in 2.50.0 (LTS) version, but I can see you have mistakenly edited 2.5.0 version instead.

Can you please revert all the changes from 2.5.0 and make changes in the correct file?

Please refer the following file path: ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/qr-scanner.md

**Comment by RudraPratik30** [comment]
Hey @ArnavSingha!
You were supposed to make changes in 2.50.0 (LTS) version, but I can see you have mistakenly edited 2.5.0 version instead.

Can you please revert all the changes from 2.5.0 and make changes in the correct file?

Please refer the following file path: ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/qr-scanner.md

**Review by RudraPratik30 — CHANGES_REQUESTED** [review]
Please make the changes in correct file.

**Comment by ArnavSingha** [comment]
extremely sorry for the 2.5.0 changes what i made. I revert all the changes from 2.5.0 and done the necessary changes on version-2.50.0-LTS/widgets/qr-scanner.md

**Review by RudraPratik30 — CHANGES_REQUESTED** [review]
Hey @ArnavSingha, I can't find the changes in "Exposed Variable" table as mentioned in the issue, can you please update that table as well? Rest of the changes look good to me.

> -  In the "Exposed Variables" Table, update the content in the "Description" and "How To Access" columns for the lastDetectedValue variable [reference](https://docs.tooljet.com/docs/widgets/text-input/#exposed-variables) ( Please just check the sentence structure from the given reference )

Please make the changes in both versions, thanks!

**Comment by ArnavSingha** [comment]
Hey @RudraPratik30 , Exposed Variable changed on both versions. BTW "Description" part looks good to me!!

**Comment by RudraPratik30** [comment]
Hey @ArnavSingha! Thanks for updating the how to access column. But,
> BTW "Description" part looks good to me!!

We have to make all the docs consistent and that's why this changes is necessary.

**Review by RudraPratik30 — APPROVED** [review]
Hey @ArnavSingha, thanks for contributing!
The changes look good to me and forwarding it to the team for final review.

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Pull request merged**
