### PR TITLE
[Feature]: Copy/Paste widgets

### LINKED ISSUE #3251: [Feature]: Copy/Paste Widgets
### Is your proposal related to a problem?

There is no option to copy and paste the widgets within the app or from one app to another

### Describe the solution you'd like

- Select the widget 
- `cmd + c` or `ctrl + c` to copy the widget
- `cmd + v` or `ctrl + v` to paste the widget in the canvas

### Describe alternatives you've considered

NA

### If the feature is approved, would you be willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by kavinvenkatachalam**
Resolves #3251

- Select the widget 
- `cmd + c` or `ctrl + c` to copy the widget
- click the container/tab/canvas where the copied widget needs to be pasted
- `cmd + v` or `ctrl + v` to paste the widget in the canvas

**Changes involved -**

- Support multi widget clone or copy-paste
- Clone or copy-paste containers with multiple children inside it
- Copy-paste widget from the canvas into a container or from one container to another

### CODE REVIEW

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @kavinvenkatachalam , sorry for the delayed review, everything seems to work properly.

As an enhancement, could we make use of clipboard instead of local storage, so that developers can copy and paste widgets between different deployments?.

**Comment by shubh22** [comment]
Task linked: [CU-2h1aaun Copy and Paste Widgets](https://app.clickup.com/t/2h1aaun)

**Comment by kavinvenkatachalam** [comment]
@sherfin94 As discussed created an issue for the alignment #3590

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Cases

Test Cases | Steps | Result
-- | -- | --
Should be able to copy multiple widgets. | Create an application. | Application gets created.
  | Drag and drop few widgets. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+c. | The widgets are copied.
Should be able to paste multiple widgets | Create an application. | Application gets created.
  | Drag and drop few widgets. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+c. | The widgets are copied.
  | Press ctrl+v. | The widgets are pasted.
Should be able to clone multiple widgets. | Create an application. | Application gets created.
  | Drag and drop few widgets. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+d. | The widgets are copied.
Should be able to copy & paste with multiple children inside it. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets inside container. | Widgets are placed inside conatiner.
  | Click on container & press ctrl+c. | The container with children is copied.
  | Press ctrl+v. | Container along with the children is pasted.
Should be able to copy and paste from canvas to container. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets on canvas. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+c. | The widgets are copied.
  | Select container. | Container is selected.
  | Press ctrl+v. | The widgets are pasted inside container.
Should be able to copy and paste from one container to another container. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets on the container. | The widgets are inside container.
  | Drag and drop container. | Container is present on canvas.
  | Select the 1st container. | 1st container is selected.
  | Press ctrl+c. | The container with widgets is copied.
  | Select second container. | Container is selected.
  | Press ctrl+v. | The widgets are pasted inside container.
Should be able to copy & paste in between 2 applications. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets on the container. | The widgets are inside container.
  | Drag and drop container. | Container is present on canvas.
  | Select both containers. | Containers are selected.
  | Press ctrl+c. | Components are copied.
  | Create another applicaton. | Application is created.
  | Press ctrl+v. | Components are pasted.


</body>
</html><html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Test Cases | Steps | Result
-- | -- | --
Should be able to copy multiple widgets. | Create an application. | Application gets created.
  | Drag and drop few widgets. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+c. | The widgets are copied.
Should be able to paste multiple widgets | Create an application. | Application gets created.
  | Drag and drop few widgets. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+c. | The widgets are copied.
  | Press ctrl+v. | The widgets are pasted.
Should be able to clone multiple widgets. | Create an application. | Application gets created.
  | Drag and drop few widgets. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+d. | The widgets are copied.
Should be able to copy & paste with multiple children inside it. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets inside container. | Widgets are placed inside conatiner.
  | Click on container & press ctrl+c. | The container with children is copied.
  | Press ctrl+v. | Container along with the children is pasted.
Should be able to copy and paste from canvas to container. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets on canvas. | The widgets are on canvas.
  | Click on one widget & press & hold shift and click on other widgets. | All the widgets get selected.
  | Press ctrl+c. | The widgets are copied.
  | Select container. | Container is selected.
  | Press ctrl+v. | The widgets are pasted inside container.
Should be able to copy and paste from one container to another container. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets on the container. | The widgets are inside container.
  | Drag and drop container. | Container is present on canvas.
  | Select the 1st container. | 1st container is selected.
  | Press ctrl+c. | The container with widgets is copied.
  | Select second container. | Container is selected.
  | Press ctrl+v. | The widgets are pasted inside container.
Should be able to copy & paste in between 2 applications. | Create an application. | Application gets created.
  | Drag and drop container. | Container is present on canvas.
  | Drag and drop few widgets on the container. | The widgets are inside container.
  | Drag and drop container. | Container is present on canvas.
  | Select both containers. | Containers are selected.
  | Press ctrl+c. | Components are copied.
  | Create another applicaton. | Application is created.
  | Press ctrl+v. | Components are pasted.


</body>
</html>

**Pull request merged**
