### PR TITLE
Added column highlighting on search to table

### LINKED ISSUE #2743: Add search term highlighting to table widget
### Is your proposal related to a problem?
Dynamically mark search terms when a user searches inside a table widget this can be provided as a setting option inside table widget inspector

### Describe the solution you'd like
When a user searches for a text highlight it if the setting option is set to true

Ex: When a user searches for keyword "sarah" the text can be highlighted where the keyword matches

image

### PR DESCRIPTION
**Pull request by felipeTht**
Resolve #2743

### CODE REVIEW

**Comment by arpitnath** [comment]
App Link: https://tooljet-pr-2811.herokuapp.com/

**Comment by arpitnath** [comment]
App link: https://tooljet-pr-2811.herokuapp.com/

**Review by arpitnath — CHANGES_REQUESTED** [review]
https://www.loom.com/share/c859b87375a4424d92d45448ce83dfc4
Bulk selection is not working.

**Comment by sherfin94** [comment]
@felipeTht Thank you for your contribution.

We're in the middle of a major refactor of the Table component in [this PR](https://github.com/ToolJet/ToolJet/pull/3933). There might probably be merge conflicts once it is merged.

So please wait until that PR is merged, so that you can update this PR to work along with the new changes.

**Comment by shubh22** [comment]
Task linked: [CU-2vjzwr0 Table: Add search term highlighting to table widget](https://app.clickup.com/t/2vjzwr0)

**Comment by arpitnath** [comment]
@felipeTht Hi 👋🏻
As mentioned above, we were in the middle of a major refactor of the Table https://github.com/ToolJet/ToolJet/pull/2811#issuecomment-1247774842
Can you please update and resolve the merge conflicts in the PR to work along with the new changes?

cc: @sherfin94

**Comment by felipeTht** [comment]
Ok! I'll try to do asap.

**Pull request closed without merging**
