### PR TITLE
#2932 Fix issue with continuous redirect

### LINKED ISSUE #2352: Docs link for Twilio is broken
The Twilio data source modal contains a link to the [ToolJet docs website](https://docs.tooljet.io/docs/data-sources/twilio), which keeps redirecting. 

### Environment
ToolJet website

### What is the expected behaviour?
The link should open up the documentation page

### What is the current behaviour?
When you navigate to the link, the url is redirected to the url with `/docs` appended to it, so after a while this is the url: `https://docs.tooljet.com/docs/data-sources/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/intro`

### How to reproduce the issue?

1. Navigate to the provided link
2. That's all
3.

### Any possible solutions?
twilio.md documentation doesn't exist in the docs/docs/data-sources directory. 

### If the bug is confirmed, would you be willing to submit a PR?
no

### LINKED ISSUE #2647: Recursive redirects
### Environment
MacOS

### What is the expected behaviour?
I should be able to visit the [REST API](https://docs.tooljet.com/docs/data-sources/restapi) page.

### What is the current behaviour?
On the [integrations](https://tooljet.com/integrations) page, upon clicking the REST API card, you'll be redirected to a new tab containing the recursive redirects

### How to reproduce the issue?

1. Go to [Integrations](https://tooljet.com/integrations) page.
2. Click `SaaS/APIs` tab and click REST API card
image

3. You'll be redirected to the issue

### Please provide any traces or logs that could help here.
Recursive redirects 🤔. I think there is no handling for the broken links
image

### Any possible solutions?
- Replace `https://docs.tooljet.com/docs/data-sources/rest-api` with `https://docs.tooljet.com/docs/data-sources/restapi`
- Create handling for broken links. 

### Can you identify the location in the driver source code where the problem exists?
- Nah I can't see the source code of the [integrations](https://tooljet.com/integrations) page.
- this might be the [culprit](https://github.com/ToolJet/ToolJet/blob/d45ef4865e6add191a445e761bca6dac35777bb5/docs/docusaurus.config.js#L7) or this [one](https://github.com/ToolJet/ToolJet/blob/d45ef4865e6add191a445e761bca6dac35777bb5/docs/docusaurus.config.js#L8) 
### If the bug is confirmed, would you be willing to submit a PR?
Yup

### LINKED ISSUE #2890: Tooljet docs endless path append and redirect
not sure if this is the right place to report this but found a small bug when navigating the wiki.
### Environment
    Tooljet docs

### What is the expected behaviour?
  acessing https://docs.tooljet.com/docs/ should redirect to  https://docs.tooljet.com/docs/intro/

### What is the current behaviour?

  endless loop

### How to reproduce the issue?

1. access:  https://docs.tooljet.com/docs/ 
2. get endless redirected as seen below

### Screenshots or Screencast

tooljetdocks endless redrect

### Any possible solutions?
return status code 301 and redirect to /docs/intro/

### LINKED ISSUE #2932: Docusaurus default redirect issue
### Environment
Hosted docs

### What is the expected behaviour?
When trying to reach a invalid URL in the documentation, the redirect to https://docs.tooljet.com/docs/intro should happen
### What is the current behaviour?
The URL in the docs keep recursively calling /docs/intro if pointed to an unavailable URL. 
### How to reproduce the issue?
Visit any of the links mentioned below and watch the URL change
1. https://docs.tooljet.com/docs/data-sources
2. https://docs.tooljet.com/docs/widgets/

### Screenshots or Screencast

https://user-images.githubusercontent.com/26953573/165904435-6cc3df66-1fd8-4f81-b4f5-01eacf0810d8.mp4

### Any possible solutions?
Unsure of the exact solution but has to be something with the default redirect URL in the docusaurus config. 

### Can you identify the location in the driver source code where the problem exists?
Not Sure

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by timagixe**
Fixes #2932 
Fixes #2890
Fixes #2647
Fixes #2352

### CODE REVIEW

**Comment by timagixe** [comment]
Also related to #2890 and would probably fix it too.

**Comment by timagixe** [comment]
And one more issue seems to be related #2647.

**Comment by timagixe** [comment]
And probably fill fix #2352

**Review by withshubh — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @timagixe 👋 

Thank you for contributing. 🎉

**Pull request merged**
