### PR TITLE
[Hotfix] Multi select widget's menu gets overlaps with parent container when added to nested listview widgets

### PR DESCRIPTION
**Pull request by arpitnath**
fixes: multi-select dropdown menu overlaps inside nested listview

### CODE REVIEW

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Cases

Test Cases | Steps | Result
-- | -- | --
Multi select's widget menu should not get overlapped with parent container in nested list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on canvas.
  | Drag and drop another list view inside list view. | List view has list view inside.
  | Drag and drop multiselect widget inside the second list view. | Multiselect widget is dropped inside second list view.
  | Select multiple options. | Menu does not get overlapped by parent container.
List View should be able to be dragged & drop on canvas. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
Should be able to change the list view's name. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
  | Enter name. | Name is changed.
Should be able to change the list data. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
  | Enter the changes on list data. | The changes are reflected on canvas.
Should be able to change the row height. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
  | Enter height in row height field. | The row height is increased/decreased.
Should be able to hide the bottom border. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
Should be able to show alert.(every action type checked) | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on add event handler. | The event handler is added.
  | Click on a row of list view. | Alert is shown.
Should be able to have a list view inside a list view.(5 level depth i.e listview inside listview inside listview inside listview inside listview) | Create an application. | Application gets created.
  | Drag and drop listview. | Listview is displayed on the canvas.
  | Drag and drop another listview inside the previous listview. | Listview inside listview is displayed.
Should be able to drop any other widget inside list view. | Create an application. | Application gets created.
  | Drag and drop listview. | Listview is displayed on the canvas.
  | Drag and drop widgets on first row. | The widgets will then be shown in every row.
Should be able to delete list view. | Create an application. | Application gets created.
  | Drag and drop list view on the canvas. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Click on delete icon. | List view is deleted.
Should be able to give some border to list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | Border field is displayed.
  | Enter 30 in border. | Border is rounded accordingly.
Should be able to give box shadow. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | General is displayed.
  | Click on general. | Box shadow field is displayed.
  | Change X,Y, Blur,Spread accordingly or click on fx and then change the options. | The changes for box shadow is displayed.
Should be able to give clear the box shadow settings. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | General is displayed.
  | Click on general. | Box shadow field is displayed.
  | Change X,Y, Blur,Spread accordingly or click on fx and then change the options. | The changes for box shadow is displayed.
  | Click on box shadow. | The panel opens up.
  | Click on clear button. | The box shadow are reset.
Should be able to change color for background. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | Background Color is displayed.
  | Change the color or click on fx and enter the hex code for color. | The background color changes.
Should be able to not view list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Go to styles. | Visible toggle is displayed.
  | Toggle the visibility field or click on fx and enter false. | The list view is not visible.
Should be able to disable the list view. | Create an application. | Application gets created.
  | Drag & drop list view. | List view is added to the canvas.
  | Go to styles. | Disable toggle is displayed.
  | Toggle the Disable field or click on fx and enter true. | The list view is disabled.
Checked all the basic test case for nested list view as well. |   |  


</body>
</html>

**Review by sherfin94 — CHANGES_REQUESTED** [review]
The inner list view seems to be overflowing out of the component: 
image

**Comment by arpitnath** [comment]
Closing this.
cc: @sherfin94 @stepinfwd

**Pull request closed without merging**
