### PR TITLE
Template: Created student attendance tracker

### PR DESCRIPTION
**Pull request by MK884**
# Description
 This pull request adds the student attendance tracker template to project #9927  . This template streamlines student attendance 
 tracking. Maintain attendance records, view course-wise attendance for specific dates, and mark students as present.

 This template will have 1 page only.

 if no results are found in the attendance table for a particular date and course, it will simply fetch students' details from students_details table.

# Changes:
Created folder server/templates/student-attendance-tracker for the student attendance tracker template.

use two ToolJet DB:
students_details => to store all student's details course-wise (student_id, name, email, mobile and course_name) 
attendance_table => to maintain attendance of all students with course and date (atttendace_id, student_id, name, email, mobile, course_name, status and attendance_date)

### CODE REVIEW

**Comment by GrowwithNaveen** [comment]
Hi @MK884, 
We tested the application again and noticed that the TJDB schema is missing. Could you please export the app again and update the JSON in the PR? Also, it would be helpful if you could share the demo data you used for testing the template.

Thanks in advance!

**Comment by MK884** [comment]
okay sure @GrowwithNaveen . One doubt, need to update only `definition.json` or both `definition.json` and `manifest.json` cause there are no options for student attendance tracker template 
image

**Comment by GrowwithNaveen** [comment]
Hi @MK884, it's sufficient to update only the definition.json file with the exported JSON of the template.

Thanks!

**Comment by MK884** [comment]
sorry for the inconvenience and delay.  I hope that this template will go live soon.
[students_details.csv](https://github.com/user-attachments/files/17459721/students_details.csv)

**Comment by GrowwithNaveen** [comment]
Hi @MK884,

Thanks for the quick turnaround. The template looks good overall. However, I noticed that the "Marking attendance for specific date and course" functionality is missing from the application. Could you please develop this feature and provide an update?

Updating screenshot for reference.

Feature list:
image

Current application:
image

**Comment by MK884** [comment]
hi @GrowwithNaveen . solve the problem there was a positioning issue.
image

**Comment by GrowwithNaveen** [comment]
Hi @MK884,

Thanks for the update! This is working fine now, and we’ll proceed with deployment from here. I’ll keep you posted on the updates. Additionally, there are [new community templates available for development](https://github.com/orgs/ToolJet/projects/16/views/2)—please take a look when you have a chance.

Thanks again!

**Review by abhinabaadhikari — APPROVED** [review]

**Pull request merged**
