### PR TITLE
[improvement] Adds default widgets to the Listview widget

### LINKED ISSUE #3616: Add default widgets to Listview
### Description
With default data, the **Listview** widget should have an image, a text and a button. 

For example, if the length of the default data is 3 then the child components for the listview widget will be 3 rows, each row with the 3 widgets

### PR DESCRIPTION
**Pull request by arpitnath**
Resolves #3616

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2hr9jcz ListView should have default example](https://app.clickup.com/t/2hr9jcz)

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Cases

Test Case | Steps | Resullt
-- | -- | --
List View should be able to be dragged & drop on canvas. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
Should be able to change the list view's name. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
  | Enter name. | Name is changed.
Should be able to change the list data. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
  | Enter the changes on list data. | The changes are reflected on canvas.
Should be able to change the row height. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
  | Enter height in row height field. | The row height is increased/decreased.
Should be able to hide the bottom border. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on list view. | The properties is displayed on the right.
Should be able to show alert. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is displayed on the canvas.
  | Click on add event handler. | The event handler is added.
  | Click on a row of list view. | Alert is shown.
Should be able to have a list view inside a list view.(5 level depth i.e listview inside listview inside listview inside listview inside listview) | Create an application. | Application gets created.
  | Drag and drop listview. | Listview is displayed on the canvas.
  | Drag and drop another listview inside the previous listview. | Listview inside listview is displayed.
Should be able to drop any other widget inside list view. | Create an application. | Application gets created.
  | Drag and drop listview. | Listview is displayed on the canvas.
  | Drag and drop widgets on first row. | The widgets will then be shown in every row.
Should be able to view default widgets in list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view has button, text & image as default.
Should be able to add new widgets while default widget already present. | Create an application. | Application gets created.
  | Drag and drop list view. | List view has button, text & image as default.
  | Drag and drop widgets on first row. | The widgets are added to the list view.
Should be able to remove the default widgets & add new widgets. | Create an application. | Application gets created.
  | Drag and drop list view. | List view has button, text & image as default.
  | Delete the default widgets. | The default widgets are deleted.
  | Drag and drop widgets on first row of list view. | The widgets are added to the list view.
Should be able to delete the default widgets & add list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view has button, text & image as default.
  | Delete the default widgets. | The default widgets are deleted.
  | Drag and drop list view on first row. | The list view is added.
  | Delete the default widgets in next list view. | The default widgets are deleted.
  | Drag and drop list view on first row. | The list view is added & nesting of list view works.
Should be able to remove one/two default widgets and add list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view has button, text & image as default.
  | Delete one/two default widgets. | The default widgets are deleted.
  | Drag and drop another list view on the first row of the previous list view. | The new list view list view is added to the previous list view & nesting works.
Should be able to delete list view. | Create an application. | Application gets created.
  | Drag and drop list view on the canvas. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Click on delete icon. | List view is deleted.
Should be able to give some border to list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | Border field is displayed.
  | Enter 30 in border. | Border is rounded accordingly.
Should be able to give box shadow. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | General is displayed.
  | Click on general. | Box shadow field is displayed.
  | Change X,Y, Blur,Spread accordingly or click on fx and then change the options. | The changes for box shadow is displayed.
Should be able to give clear the box shadow settings. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | General is displayed.
  | Click on general. | Box shadow field is displayed.
  | Change X,Y, Blur,Spread accordingly or click on fx and then change the options. | The changes for box shadow is displayed.
  | Click on box shadow. | The panel opens up.
  | Click on clear button. | The box shadow are reset.
Should be able to change color for background. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Select the list view. | List view is selected.
  | Go to styles. | Background Color is displayed.
  | Change the color or click on fx and enter the hex code for color. | The background color changes.
Should be able to not view list view. | Create an application. | Application gets created.
  | Drag and drop list view. | List view is added to the canvas.
  | Go to styles. | Visible toggle is displayed.
  | Toggle the visibility field or click on fx and enter false. | The list view is not visible.
Should be able to disable the list view. | Create an application. | Application gets created.
  | Drag & drop list view. | List view is added to the canvas.
  | Go to styles. | Disable toggle is displayed.
  | Toggle the Disable field or click on fx and enter true. | The list view is disabled.


</body>
</html>

**Review by sherfin94 — CHANGES_REQUESTED** [review]
The child widgets seem to get regenerated when all of them are deleted.


https://user-images.githubusercontent.com/20333972/180727288-d0b43726-ad26-4ffa-bda2-7c6efc246372.mov

**Comment by arpitnath** [comment]
Refer: PR - #3716

**Comment by shubh22** [comment]
Task linked: [CU-2namw25 Default widgets for Container layout widgets](https://app.clickup.com/t/2namw25)

**Pull request closed without merging**
