### PR TITLE
Bugfix/inspector dark mode

### LINKED ISSUE #892: Make section headers on inspector slightly more legible in dark mode
### Is your proposal related to a problem?

The section headers on inspector are not optimally legible for dark mode at the moment:
image

### Describe the solution you'd like

Increase its brightness to resemble something like this:
image

### Describe alternatives you've considered

(Write your answer here.)

### PR DESCRIPTION
**Pull request by RajMhatre20**
Replaced the font color 
```#656d77```
in tabler.scss to 
```#f4f6fa``` 
closes #892

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
Thanks! Can you please add screenshots of how this looks like on both the dark mode and light mode?
@RajMhatre20

**Comment by RajMhatre20** [comment]
Dark Mode:
image
Light Mode:
image

**Comment by Navaneeth-pk** [comment]
Looks good! we can merge the PR once the CLA is signed.
@RajMhatre20

**Comment by RajMhatre20** [comment]
Alright Done, Thankyou :)

**Pull request merged**
