### PR TITLE
[Feature]: Tree Select Widget

### LINKED ISSUE #3532: [Feature]: Tree Select Widget
Create a Tree Select widget to select multiple checkboxes in a tree view

### PR DESCRIPTION
**Pull request by kavinvenkatachalam**
Resolves #3532

image

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2h1aepv Multi Select Tree Widget](https://app.clickup.com/t/2h1aepv)

**Review by arpitnath — APPROVED** [review]
LGTM

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Cases

Test Cases | Steps | Result
-- | -- | --
Should be able to view icon in light mode. | Create an application | Application gets created.
  | Search tree select widget on search. | Icon is visible.
Should be able to view icon in dark mode. | Create an application | Application gets created.
  | Click on dark mode. | Dark mode is activated.
  | Search tree select widget on search. | Icon is visible.
Should be able to update widget's title. | Create an application | Application gets created.
  | Drag & drop tree select widget on canvas. | Tree select is displayed on canavas.
  | Select tree select widget. | Tree select widget is selected.
  | Go to properties. | Title is displayed.
  | Enter updated name in Title field. | The updated title is entered & reflected on tree select widget on canvas.
Should be able to update widget's name. | Create an application | Application gets created.
  | Drag & drop tree select widget on canvas. | Tree select is displayed on canavas.
  | Select tree select widget. | Tree select widget is selected.
  | Go to properties. | Name of tree select  is displayed.
  | Enter updated name in Name field. | The updated name is entered & reflected on tree select widget on canvas.
Should not be able to update widget's name to taken name. | Create an application | Application gets created.
  | Drag & drop tree select widget on canvas. | Tree select is displayed on canavas.
  | Drag & drop another tree select widget on canvas. | Tree select is displayed on canavas.
  | Select tree select widget. | Tree select widget is selected.
  | Go to properties. | Name of tree select  is displayed.
  | Enter the first widget name in secnd widget. | Error message is displayed.
Should be able to update the structure. | Create an application | Application gets created.
  | Drag & drop tree select widget on canvas. | Tree select is displayed on canavas.
  | Select tree select widget. | Tree select widget is selected.
  | Enter a different structure. | The tree select changes respectively.
Should be able to change checked values. | Create an application | Application gets created.
  | Drag & drop tree select widget on canvas. | Tree select is displayed on canavas.
  | Select tree select widget. | Tree select widget is selected.
  | Enter new checked value. | The checked value for tree select on canvas is changed.
Should be able to change expanded values. | Create an application | Application gets created.
  | Drag & drop tree select widget on canvas. | Tree select is displayed on canavas.
  | Select tree select widget. | Tree select widget is selected.
  | Enter new expand value. | New value is expanded for tree select on canavas.
Event handler should work.(checked for every action type) | Create an application | Application gets created.
  | Drag & drop tree select widget. | Tree select widget is displayed on canvas.
  | Select the tree select widget. | The widget is selected & properties is displayed.
  | Click on events. | The event panel opens up.
  | Click on + Add Handler button on events. | New event is created.
  | Click on one label in tree select. | Alert is displayed.
Should be able to delete event. | Create an application | Application gets created.
  | Drag & drop tree select widget. | Tree select widget is displayed on canvas.
  | Select the tree select widget. | The widget is selected & properties is displayed.
  | Click on events. | The event panel opens up.
  | Click on + Add Handler button on events. | New event is created.
  | Click on delete button icon. | Event is deleted.
Should be able to add multiple events. | Create an application | Application gets created.
  | Drag & drop tree select widget. | Tree select widget is displayed on canvas.
  | Select the tree select widget. | The widget is selected & properties is displayed.
  | Click on events. | The event panel opens up.
  | Click on + Add Handler button on events. | New event is created.
  | Click on + Add Handler button on events. | Another event is created.
Should be able to add a tooltip. | Create an application | Application gets created.
  | Drag & drop tree select widget. | Tree select widget is displayed on canvas.
  | Select the tree select widget. | The widget is selected & properties is displayed.
  | Click on general. | Tooltip is displayed.
  | Enter name on tooltip. | Entered name is present in tooltip.
  | Hover over tree select. | Entered name for tooltip is displayed.
Should be able to put tree select inside modal. | Create an application | Application gets created.
  | Drag & drop modal. | Modal is on canvas.
  | Drag and drop button. | Button is dropped on canvas.
  | Select button. | Properties is visible.
  | Click on events. | The event panel opens up.
  | Click on + Add Handler button on events. | New event is created.
  | Choose action type as show modal & select widget name. | Action type set to show modal.
  | Click on button. | Modal opens up.
  | Drag & drop tree select widget on modal. | Tree select widget is displayed on modal.
Should be able to put tree select inside tab. | Create an application | Application gets created.
  | Drag & drop tab. | Tab is on canvas.
  | Drag & drop tree select inside tab. | Tree select widget is inside tab.
Should be able to put tree select inside listview. | Create an application | Application gets created.
  | Drag & drop listview. | Listview is on canvas.
  | Drag & drop tree select inside listview. | Tree select widget is inside listview.
Should be able to put tree select inside container. | Create an application | Application gets created.
  | Drag & drop container. | Container is on canvas.
  | Drag & drop tree select inside container. | Tree select widget is inside container.
Should be able to change text color. | Create an application | Application gets created.
  | Drag & drop tree select widget. | Tree select widget is displayed on canvas.
  | Select the tree select widget. | The widget is selected & styles is displayed.
  | Click on styles. | Text color is displayed.
  | Pick a color or click on fx & enter hex code in text color field. | Text color is changed.
Should be able to change checkbox color. | Create an application | Application gets created.
  | Drag & drop tree select widget. | Tree select widget is displayed on canvas.
  | Select the tree select widget. | The widget is selected & styles is displayed.
  | Click on styles. | Checkbox color is displayed.
  | Pick a color or click on fx & enter hex code in checkbox color field. | Checkbox color is changed.
Should be able to not view tree select widget. | Create an application. | Application gets created.
  | Drag and drop tree select widget. | Tree select widget is added to the canvas.
  | Go to styles. | Visible toggle is displayed.
  | Toggle the visibility field or click on fx and enter false. | The tree select is not visible.
Should be able to disable the tree select. | Create an application. | Application gets created.
  | Drag & drop tree select. | Tree Select is added to the canvas.
  | Go to styles. | Disable toggle is displayed.
  | Toggle the Disable field or click on fx and enter true. | The tree select is disabled.
Should be able to give box shadow. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Select the tree select. | Tree Select is selected.
  | Go to styles. | General is displayed.
  | Click on general. | Box shadow field is displayed.
  | Change X,Y, Blur,Spread accordingly or click on fx and then change the options. | The changes for box shadow is displayed.
Should be able to give clear the box shadow settings. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Select the tree select. | Tree select is selected.
  | Go to styles. | General is displayed.
  | Click on general. | Box shadow field is displayed.
  | Change X,Y, Blur,Spread accordingly or click on fx and then change the options. | The changes for box shadow is displayed.
  | Click on box shadow. | The panel opens up.
  | Click on clear button. | The box shadow are reset.
Should be able to view the parent as checked while all the child are checked. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Select all the children. | The parent is also selected.
Should be able to able to view all child as checked while parent is checked. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Select the parent. | All the children is also selected.
Should be able to view the checked path array. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Open the inspector. | Inspector is opened.
  | Click on components and go to checked path array. | The checked path array shows the array for the checked values.
Should be able to view the checked value. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Open the inspector. | Inspector is opened.
  | Click on components and go to checked. | The checked path shows the array for the checked values.
Should be able to view the expand value. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Open the inspector. | Inspector is opened.
  | Click on components and go to expand. | The expand shows the array for the expanded values.
Should be able to view the checked path strings. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Open the inspector. | Inspector is opened.
  | Click on components and go to checked path string. | The checked path strings shows the string for the checked values.
Should be able to delete tree select widget. | Create an application. | Application gets created.
  | Drag and drop tree select. | Tree select is added to the canvas.
  | Select the tree select widget. | The widget is selected.
  | Click on delete button icon. | The widget is deleted.


</body>
</html>

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @kavinvenkatachalam , everything looks fine. one small change, set the exposed variables on the widget config so that the values corresponding to the default properties are exposed when the widget is dropped.

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
