### PR TITLE
Fix dashboard search UI #8891

### PR DESCRIPTION
**Pull request by tiwarishankar**
This PR will solve issue #8891 i.e. Dashboard search animation to be fixed to the top of the page
Changes:
1. Fixed Dashboard Search Animation: Ensured the search bar remains fixed at the top during searches.
2. UI Improvements: Simplified rendering logic by removing unnecessary conditions and adding a loading state.
3. Enhanced Conditional Rendering: Updated conditions for displaying the HomeHeader component based on search query and loading state.

### CODE REVIEW

**Comment by tiwarishankar** [comment]
Screen Recording of Current Search UI:

https://github.com/ToolJet/ToolJet/assets/71537738/29a5f89c-fe87-4c8b-8119-d299768ca7fa

**Comment by tiwarishankar** [comment]
Hey @gsmithun4 are you still looking into this PR review ??
c.c @karan-rathod-316

**Comment by karan-rathod-316** [comment]
> Hey @gsmithun4 are you still looking into this PR review ?? c.c @karan-rathod-316

Hi @tiwarishankar, yes. This is in review. GIve us some time.

**Comment by shah21** [comment]
@tiwarishankar  Could you please check why the lint is failing?

**Comment by shah21** [comment]
@tiwarishankar. Could you please resolve the conflicts

**Pull request closed without merging**
