### PR TITLE
Add RU localisation for Tooljet

### PR DESCRIPTION
**Pull request by daniloff200**
First part of https://github.com/ToolJet/ToolJet/issues/4261

Gonna start work on UA localisation as soon, as this one will be merged

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @daniloff200 
I see the translation is incomplete. 🤔

**Comment by daniloff200** [comment]
@withshubh  oh
I was working on another machine and lost part of the work. Now, it's in place ;) Thanks for noticing that

**Review by withshubh — APPROVED** [review]
LGTM

**Comment by Navaneeth-pk** [comment]
@daniloff200 please resolve the merge conflicts.

**Comment by daniloff200** [comment]
@Navaneeth-pk Done)
@withshubh  could you please re-approve this one?

**Comment by daniloff200** [comment]
I'm wondering, can this one be merged, or, some additional work needed? Wanna start working on second part of the task, with the 🇺🇦  locale

**Pull request merged**
