### PR TITLE
[localization] translate strings in Indonesian

### PR DESCRIPTION
**Pull request by depapp**
add Indonesian (Bahasa Indonesia) localization (`id.json`)
this PR solve #4286

### CODE REVIEW

**Comment by depapp** [comment]
hello guys @withshubh @Navaneeth-pk 
could you please help me to review this PR 🙇🏻 
thanks

**Review by withshubh — APPROVED** [review]

**Comment by depapp** [comment]
thanks for the approval @withshubh 🙇🏻 
since I don't have permission to merge di PR, could you please help. thanks

**Comment by withshubh** [comment]
Hey @depapp 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Comment by depapp** [comment]
> Hey @depapp Thanks for contributing to ToolJet. 🙌 Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

thanks @withshubh 🙇🏻

**Pull request merged**
