### PR TITLE
Change icon size

### PR DESCRIPTION
**Pull request by virajbahulkar**
#214 

Screenshot 2021-06-09 at 6 13 05 PM

### CODE REVIEW

**Comment by virajbahulkar** [comment]
@Navaneeth-pk Kept font size of icons similar to headings size.

**Comment by Navaneeth-pk** [comment]
@virajbahulkar 
Can you please make them smaller? I think the icons still stands out as the most emphasized objects on the canvas. Can we also try changing the fill colour of icons to that of the text buttons? I think that makes the UI of the editor look consistent.

**Comment by virajbahulkar** [comment]
> @virajbahulkar
> Can you please make them smaller? I think the icons still stands out as the most emphasized objects on the canvas. Can we also try changing the fill colour of icons to that of the text buttons? I think that makes the UI of the editor look consistent.

Screenshot 2021-06-09 at 11 47 06 PM

is it okay?

**Comment by Navaneeth-pk** [comment]
Looks good to me. Thanks @virajbahulkar

**Pull request merged**
