### PR TITLE
create a new plugin for MindsDB

### LINKED ISSUE #4605: [datasource] create a new plugin for MindsDB
#### Goal
Create a new data source plugin for **[MindsDB](https://mindsdb.com/)** 

#### Operations to be supported:

- list predictors
- list data sources
- get data source
- get predictor
- queryPredict
- data source loadData

#### Implementation
Guide for building ToolJet plugins: https://docs.tooljet.com/docs/contributing-guide/tutorials/creating-a-plugin
MindsDB reference: https://www.npmjs.com/package/mindsdb-js-sdk

### PR DESCRIPTION
**Pull request by abdellani**
closes #4605

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @abdellani 
Thanks for creating the PR. 🎉 
Please let us know if you're still working on it.

**Comment by abdellani** [comment]
Hi @withshubh 
Sorry for the delay.
I was busy during the last few days.
I'll finish it udring this week.

**Comment by withshubh** [comment]
> Hi @withshubh Sorry for the delay. I was busy during the last few days. I'll finish it udring this week.

Awesome! Thanks for the update 🙌

**Comment by abdellani** [comment]
@withshubh looks like some APIs are unreachable without a key. I wrote in the MindsDB channel.
Please have a look and let me know what you think.
https://mindsdbcommunity.slack.com/archives/C01S2T35H18/p1672463906925119

**Comment by shubh22** [comment]
Hi @abdellani,

Looks like MindsDB has released a new version of their JS SDK. Could you please check this out?
https://github.com/mindsdb/mindsdb_js_sdk/tree/1.0.18

Thanks,
Shubham

cc - @withshubh

**Comment by abdellani** [comment]
@shubh22 
ok :+1:

**Comment by abdellani** [comment]
@shubh22 
Unfortunately, with my new schedule, I can't find time to continue working on this.
I'll give up this task.

**Pull request closed without merging**
