### PR TITLE
[docs] Removed inactive links to images in oauth2-authorization.md

### PR DESCRIPTION
**Pull request by domstrozynski**
Removed inactive links to images in [oauth2-authorization.md](https://github.com/ToolJet/ToolJet/blob/develop/docs/docs/how-to/oauth2-authorization.md)

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @domstrozynski 
Thanks for creating the PR.
Can you please link the issue that this PR fixes in the PR description?

**Comment by domstrozynski** [comment]
> Hey @domstrozynski Thanks for creating the PR. Can you please link the issue that this PR fixes in the PR description?

Hi @withshubh 
I haven't created issue, I looked through issues to check if there's something about it already to avoid duplicates though. I thought it'd be a "quick fix" so didn't want to create unnecessary topics. Should I add new issue now? I'm still realtively new to open source contributions, sorry for any inconveniences

**Comment by withshubh** [comment]
> > Hey @domstrozynski Thanks for creating the PR. Can you please link the issue that this PR fixes in the PR description?
> 
> Hi @withshubh I haven't created issue, I looked through issues to check if there's something about it already to avoid duplicates though. I thought it'd be a "quick fix" so didn't want to create unnecessary topics. Should I add new issue now? I'm still realtively new to open source contributions, sorry for any inconveniences

Hey Dominic,

No worries, you can still create an issue. According to the [Contributing Guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md), the issue needs to be reviewed first then it gets assigned to be worked upon. 
It is a good practice to follow the guidelines before contributing to Open Source project 😉

**Comment by domstrozynski** [comment]
@withshubh I got a little bit confused at first, the images seems to be working on the docs website properly, therefore I thought the links are inactive on GitHub since they can't be viewed here. I guess we can close this PR without any changes 😅

**Comment by withshubh** [comment]
> @withshubh I got a little bit confused at first, the images seem to be working on the docs website properly, therefore I thought the links are inactive on GitHub since they can't be viewed here. I guess we can close this PR without any changes 😅

Closing this PR. Feel free to pick any other open issue if interested.

**Pull request closed without merging**
