### PR TITLE
Template: Created placeholder image generator

### PR DESCRIPTION
**Pull request by Ayyanaruto**
#10888 
This pull request adds a new feature to the project by introducing a placeholder image generator. The most important change is the creation of a new manifest file for this feature.

New feature addition:

* [`server/templates/placeholder-image-generator/manifest.json`](diffhunk://#diff-bd48d4e52d12d80a724ebed02c283ef45f78f7602a480465cbee9f3f830db8feR1-R16): Added a manifest file that defines the placeholder image generator, including its name, description, widgets, sources, ID, and category.

**Attachments**

### CODE REVIEW

**Comment by Ayyanaruto** [comment]
@GrowwithNaveen,@abhinabaadhikari @karan-rathod-316

**Comment by Ayyanaruto** [comment]
Hi Pritesh,

 I noticed that you recently assigned the issue #10888 to another community member. I wanted to bring to your attention that I had already submitted a pull request addressing this issue due to  not being assigned . I was wondering if you could kindly advise me on whether I should close my PR or if there's any other action you'd like me to take.

**Comment by PriteshKiri** [comment]
Hey @Ayyanaruto ,

We really appreciate your contribution and the effort you've put in! However, we suggest starting work on an issue only after it has been assigned to a contributor. 

In this case, you can go ahead and close the PR for now. Thank you for your understanding!

**Comment by Ayyanaruto** [comment]
Hey @PriteshKiri, if by chance the assigned community member doesn't solve the above issue, can you assign it to me

**Pull request closed without merging**
