### PR TITLE
On hovering the Link widget, a tooltip should be displayed fixed

### LINKED ISSUE #4233: On hovering the Link widget, a tooltip should be displayed
### Environment
The latest `develop`

### What is the expected behaviour?
On hovering the widget, a tooltip should be displayed if a tooltip is provided in the widget inspector.

### What is the current behaviour?
With a tooltip provided, on hover, there is no tip that is being displayed

### How to reproduce the issue?

1. Add Link widget from widget manager
2. Click on the config handler of the widget to open up the widget inspector
3. Provide a tooltip (expected type is a **String)**
4. Hover on the widget

### PR DESCRIPTION
**Pull request by zainbinfurqan**
fixes #4233

### CODE REVIEW

**Comment by zainbinfurqan** [comment]
@gsmithun4  can you please review it.

**Comment by zainbinfurqan** [comment]
@gsmithun4  can you review it please.

**Comment by Navaneeth-pk** [comment]
@zainbinfurqan please use proper titles while creating PRs.

**Comment by withshubh** [comment]
> @Navaneeth-pk should i update the title on this MR?

Yes, please update the title.

**Comment by zainbinfurqan** [comment]
@Navaneeth-pk  title updated [#4233](https://github.com/ToolJet/ToolJet/issues/4233#issuecomment-1265211406)

**Comment by withshubh** [comment]
> @Navaneeth-pk title updated [#4233](https://github.com/ToolJet/ToolJet/issues/4233#issuecomment-1265211406)

Hey @zainbinfurqan - I think you mentioned the wrong issue number. Can you please verify? Issue #4233 already has one PR linked (https://github.com/ToolJet/ToolJet/pull/4545)

**Comment by zainbinfurqan** [comment]
@Navaneeth-pk  this was also my MR which got some issues, so i created new one.

**Comment by zainbinfurqan** [comment]
@withshubh  can you Please review it?

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@zainbinfurqan Thanks for the PR. Why this changes are required since it's not related to the issue mentioned?

**Comment by zainbinfurqan** [comment]
@kavinvenkatachalam I took the latest pull before create the PR and i got some comments that their are some lint issues, so i resolved them.

**Comment by kavinvenkatachalam** [comment]
> @kavinvenkatachalam I took the latest pull before create the PR and i got some comments that their are some lint issues, so i resolved them.

Thanks for the reply. The lint issue is resolved now. Can you please take a pull, revert all the changes which are not required for this issue?

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare Can you take a pull from latest develop?

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @zainbinfurqan  
Thanks for contributing to ToolJet. :raised_hands: 
While this PR is under review, you can submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
