### PR TITLE
Fix :: Overflowing column in template modal

### LINKED ISSUE #5953: [Enhancement] Zooming on the screen should display a scrollbar
### What is the expected behaviour?
A scrollbar should appear when the user zooms on the screen. 

### What is the current behaviour?
When the user zooms on the screen, there is no scrollbar.

### How to reproduce the issue?
1.  Login with the valid credentials 
2. Click on the new app button and select "Choose from template" option ("Template library modal" should appear with all elements.)
3. Zooming the screen 

### Screenshots or Screencast
Zoom_template

### PR DESCRIPTION
**Pull request by yashrajbothra**
closes #5953

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @yashrajbothra - Thanks for contributing to ToolJet. Please sign the CLA.

**Comment by yashrajbothra** [comment]
Hii @withshubh Thanks for reviewing the PR. I actually signed up for CLA 2 days ago but it's not getting updated here
Screenshot 2023-04-10 at 3 50 25 PM

**Comment by withshubh** [comment]
No worries, thanks for sharing. @yashrajbothra

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by withshubh** [comment]
Closing this PR as the issue is already fixed.

**Pull request closed without merging**
