### PR TITLE
Bug Fixed : Folder icon is now clearly visible in darkmode/issue_3647

### PR DESCRIPTION
**Pull request by UtkarshDixit-py**
Made folder icon's color 2 shades darker so it's clearly visible in dark mode.

### CODE REVIEW

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
Hey @UtkarshDixit-py,

Thanks for the PR. Still, the icon is not clearly visible in the dark mode. 

image

Here is my suggestion,

In the `Folders.jsx` file, check if it is a dark mode and add an additional class
```
<img
src="/assets/images/icons/folder.svg"
alt=""
width="14"
height="14"
className={`folder-ico ${darkMode && 'dark'}`}
/>
```
Add the class in the `theme.scss` file under `folder-list` class
```
.folder-ico.dark {
  filter: invert(1);
}
```

cc: @ajith-k-v

**Comment by UtkarshDixit-py** [comment]
@kavinvenkatachalam Sure

**Comment by UtkarshDixit-py** [comment]
Hey @kavinvenkatachalam I've done what you suggested and it works. Now should i undo the previous commit(change the colour back to the previous lighter shade)?

**Comment by kavinvenkatachalam** [comment]
> Hey @kavinvenkatachalam I've done what you suggested and it works. Now should i undo the previous commit(change the colour back to the previous lighter shade)?
> 
> @ajith-k-v

@UtkarshDixit-py The icon color change which you did looks brighter than the existing one. So, you can keep the same color. No need to revert the commit.

**Comment by kavinvenkatachalam** [comment]
Hey @UtkarshDixit-py Changes look good! can you resolve the conflicts?

**Review by kavinvenkatachalam — APPROVED** [review]

**Pull request merged**
