### PR TITLE
Added Package Name and Version

### PR DESCRIPTION
**Pull request by shriekdj**
For Me the npm was not installing the package and it's reason was that this package is not have `name` and `version` key specified.
don't know why it happened but most of my project don't need that data

### CODE REVIEW

**Comment by gondar00** [comment]
Hi @shriekdj, thanks for contributing 🚀 

I am unable to see the `package-lock.json` file change, can you please once run `npm i` and also commit the `package-lock.json` file. 

Today a new version was released `v1.18.0` could you also please update that in the version key @ package.json?

**Comment by shriekdj** [comment]
> I am unable to see the `package-lock.json` file change, can you please once run `npm i` and also commit the `package-lock.json` file.
> 
> Today a new version was released `v1.18.0` could you also please update that in the version key @ package.json?

Hi @gondar00 , I Just Ran the same code with `npm i` and the `package-lock.json` is updated

I Ran the code on ubuntu 22.04 wsl on windows 10 and used nvm to install node 14.17.3

**Comment by shriekdj** [comment]
Also I Signed the CLA Agreement

**Comment by shriekdj** [comment]
but still check the code by your side also

**Comment by gondar00** [comment]
@shriekdj lockfile version changed from 2 to 1, can you once check that the npm version is pointing to `7.20.0`
```
➜  ToolJet git:(develop) npm -v 
7.20.0
```

You can run this command to change the npm version

`npm i -g npm@7.20.0`

**Comment by shriekdj** [comment]
ok i will check it that also

**Comment by gondar00** [comment]
Looks good! 👍

**Pull request merged**
