### PR TITLE
Enhancement : [RangeSlider widget] Bind onChange event

### PR DESCRIPTION
**Pull request by Srisuma13**
Fixes - https://github.com/ToolJet/ToolJet/issues/4178

### CODE REVIEW

**Comment by Srisuma13** [comment]
@arpitnath Fixed the lint issues, could you please review the PR now? It fixes the https://github.com/ToolJet/ToolJet/issues/4178

**Review by arpitnath — CHANGES_REQUESTED** [review]
The event should fire once, the slider is updated, i.e. after the change is done.
Currently, on sliding the range, events are fired continuously if onChange is binded.

**Review by arpitnath — DISMISSED** [review]
There is an `onAfterChange` api available from the lib that is being used here.
ref: https://github.com/react-component/slider

**Comment by withshubh** [comment]
Hey @Srisuma13 👋 
Please make the changes suggested by @arpitnath

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
