### PR TITLE
[docs]: Fix documentation for the Image Component

### LINKED ISSUE #11124: [docs]: Update the documentation for the Image Component
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/image

**Content updates:**
- ~~In the "Events" Table, update the "Description" for the "On click" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )~~
- Layout Table
  - Update the title name from "Layout" to "Devices" [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices)
  - Update the name of the first column from  "Layout" to "Property"
  - Update the content in the "Description" and "Expected value" columns as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) ( Please just check the sentence structure from the given reference )
  - Add a full stop at the end of the sentence in the "Description" and "Expected value" columns.
  
**The changes are to be implemented in two files -** 
Next - ToolJet/docs/docs/widgets/image.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/image.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by SaurabhGurde**
will close #11124
What does this PR do.
1) Changes title from Layout to Devices
2) changes the column name from Layout to Property
3) updates the description of description and expected value column

### CODE REVIEW

**Review by RudraPratik30 — CHANGES_REQUESTED** [review]
Hey @SaurabhGurde, thanks for contributing!
As per the issue you were supposed to make changes in two files (LTS and Next Version) but I can see you have made changes in only one file, can you please replicate your changes in the Next Version as well, in a single PR?

Also you are required to sign the CLA before we can accept your contribution, thanks!

**Comment by SaurabhGurde** [comment]
@RudraPratik30 there was a bit confusion from my side. I have pushed a new commit updating the ToolJet/docs/docs/widgets/image.md file please check.

**Comment by RudraPratik30** [comment]
Hey @SaurabhGurde thanks for making the changes, will review it soon. Till that time can you please sign our [Contributor License Agreement (CLA)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11138). Without CLA we might not be able to accept your changes.

**Comment by SaurabhGurde** [comment]
@RudraPratik30 Signed CLA. Done!

**Review by RudraPratik30 — APPROVED** [review]
Hey @SaurabhGurde, thanks for contributing!
The changes look good to me and forwarding it to the team for final review, thanks again!

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Review by adishM98 — APPROVED** [review]

**Pull request merged**
