### PR TITLE
#3309: Fixed misaligned text issue

### LINKED ISSUE #3309: Misaligned text in events section
### Version Information
All

### Environment
All

### What is the expected behaviour?
Text: Query doesn't have any event handlers should be aligned

### What is the current behaviour?
Text: Query doesn't have any event handlers is mis-aligned

### How to reproduce the issue?

1. Check SS

### Screenshots or Screencast
image

### PR DESCRIPTION
**Pull request by shubham199711**
Fixed the text alignment issue on New query > advance > (No events added case)

Text: This query doesn't have any event handlers

fixes #3309

### CODE REVIEW

**Comment by stepinfwd** [comment]
Hi @shubham199711  the event cards style have changed due to the updated code , please make sure that changes are  in sync with the earlier UI.
Screenshot 2022-06-30 at 11 49 39 AM
Screenshot 2022-06-29 at 12 26 56 PM

**Comment by withshubh** [comment]
Hey @shubham199711 👋 
Any update on this?

**Comment by withshubh** [comment]
Hey @shubham199711 👋 
Are you still working on it?

**Comment by withshubh** [comment]
@shubham199711 Please give an update else we will have to close the PR and unassign the issue.

**Comment by withshubh** [comment]
Closing this PR as there was no update for more than 45 days.

**Pull request closed without merging**
