### PR TITLE
update Roadmap url

### LINKED ISSUE #7280: [docs]: Update the Roadmap hyperlink
### Summary

In [ToolJet Docs](https://docs.tooljet.com/docs/), the Roadmap section in the left sidebar is hyperlinked with an outdated URL; it needs an update to the new URL: https://github.com/tooljet/tooljet/milestones

image

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/

### Steps to reproduce the issue

1. Open https://docs.tooljet.com/docs/
2. Scroll to the bottom of the left sidebar
3. Notice the section "Roadmap."

### Additional Information

_No response_

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by StrixV54**
Fixes #7280
updated URL as mentioned in above issue.

### CODE REVIEW

**Review by tejakummarikuntla — CHANGES_REQUESTED** [review]
@StrixV54, can you update this change in all the other versions of the docs?
https://github.com/ToolJet/ToolJet/tree/develop/docs/versioned_docs

**Comment by StrixV54** [comment]
Sure

**Comment by StrixV54** [comment]
Hi @tejakummarikuntla - I have updated this, you can check now.

**Comment by StrixV54** [comment]
@tejakummarikuntla Hi, can you check this please.

**Review by tejakummarikuntla — APPROVED** [review]

**Pull request merged**
