### PR TITLE
[Bugfix] Syntax Errors in Query Transformation  and adds them to the Debugger

### LINKED ISSUE #3734: Syntax Errors in Transformation component, fires the toast without valid error message
### What is the expected behaviour?
Errors should be handled and added to the Debugger. Also should fire a toast with a valid error message.

### What is the current behaviour?
If any syntax or reference errors are evaluated from query transformations, an empty toast is fired(No error message) and Leftsidebar Inspector(JSON Tree component) tries to render an undefined component which crashes the component

### How to reproduce the issue?

1. Add a new query, for e.g., rest API with valid URL
2. Toggle the transformation on
3. voluntarily introduce a  JS Syntax error
4. Save and Run the query

### Screenshots or Screencast

https://user-images.githubusercontent.com/67645175/182676360-2cf690ac-a843-48dd-8a0c-2a1a19e9d456.mov

### PR DESCRIPTION
**Pull request by arpitnath**
Resolves #3734

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2nvu3dp Errors from Transformation components breaks the Inspector](https://app.clickup.com/t/2nvu3dp)

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Case

Test Case | Steps | Result
-- | -- | --
Should be able to have syntax errors in transformation component, firest a valid error toast message & valid debugger message. | Create an application. | Application gets created.
  | Add a rest api query with transformation toggled on. | Rest api query is added.
  | Add syntax error query in transformation. | Query is entered.
  | Click on Save & run. | Syntax toast is fired & debugger shows syntax error.


</body>
</html>

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Review by sherfin94 — CHANGES_REQUESTED** [review]
The error toast shows up in viewer mode. Please check.

**Comment by arpitnath** [comment]
> The error toast shows up in viewer mode. Please check.

Ref: fixed here - https://github.com/ToolJet/ToolJet/pull/3768

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
