### PR TITLE
fix(UI): Group Delete DarkMode

### PR DESCRIPTION
**Pull request by Sanjayrk0206**

### CODE REVIEW

**Comment by Sanjayrk0206** [comment]
fixed: #4380

**Comment by withshubh** [comment]
Hey @Sanjayrk0206 

Thanks for your interest in contributing to ToolJet.

Unfortunately, we have to close this PR because issue #4380 is assigned to someone else.

Please follow the contributing guidelines before creating an issue or the PR.

**Comment by Sanjayrk0206** [comment]
Hey @withshubh,

Can you assign this later? if it is not closed by the currently assigned person.

**Comment by withshubh** [comment]
Sure!

> Hey @withshubh,
> 
> Can you assign this later? if it is not closed by the currently assigned person.

**Pull request closed without merging**
