### PR TITLE
Detach modal button height property from modal height

### LINKED ISSUE #6306: Detach height of button box from height of modal widget
### Is your proposal related to a problem?
Button box wrapper which opens modal height is linked to modal height 

### Describe the solution you'd like
Add a separate height property for modal 
By default height of button box wrapper should be just more than the height of the button

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by stepinfwd**
close #6306

### CODE REVIEW

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@stepinfwd Existing modals are getting affected. Can you check for the backward compatibility?

**Comment by stepinfwd** [comment]
> @stepinfwd Seems like `%` is not supported. Can you check for the possibilities?

we can use other relative units like em , vw etc

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@stepinfwd Even with the latest change, it is affecting the existing modal height. I would suggest to keep the existing `height` property and can create a property with diff key like `modalHeight`. So, if the height value is available in the existing widget, we can use the height and display accordingly. If it is not available, then we can use the new logic and display with `modalHeight`

**Review by kavinvenkatachalam — DISMISSED** [review]

**Comment by withshubh** [comment]
docs here: https://github.com/ToolJet/ToolJet/pull/6566

**Pull request merged**
