### PR TITLE
[v2-beta/Bugfix]: Form Widget Bugs

### LINKED ISSUE #4993: [Bug]: Form Widget Child Data Not Exposed Properly
### Version Information

`v2-beta`

### Environment

`v2-beta`

### What is the expected behaviour?

The child widgets data of the Form component needs to be exposed properly. The data should not be cleared until all the event handler executions are completed

### What is the current behaviour?

`Filepicker` and `Multiselect` values are not exposed when we dropped into the Form widget. Form widget data got cleared before executing the events in the event handler

### How to reproduce the issue?

1. Drop the `Form` widget
2. Drop `MultiSelect` and `FilePicker` into the form widget
3. Open the `Inspector` and the data under Form doesn't contain any value of `Filepicker` and `Multiselect`
4. Create a `RunJS` query to get the data of the form like `return components.form1.data` with `Request Confirmation` toggled on.
5. Attach the created RunJS query to the `OnSubmit` of the form event
6. Submit the form and when look into the `runjs1` value in the Inspector, the correct value is not exposed

### Screenshots or Screencast

**Filled the form with the values -**

image

**Got a default value in runjs -**

image

### Any possible solutions?

In the Form component we're looking for a `value` key to expose the data. Few widgets might not have a value key and it is exposed with a different key name. We can make it dynamic and expose in a way how `ListView` is done. To provide the right data to the event handlers, we can make use of `Promise chain` and run the `resetForm` after completing all the events

### Can you identify the location in the driver source code where the problem exists?

`frontend/src/Editor/Components/Form.jsx`

### If the bug is confirmed, would you be willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by kavinvenkatachalam**
Resolves #4993

- [x] Not able to use data from form, for the query with confirmation box
- [x] The File Picker on the form is not visible in the inspector
- [x] Form widget not exposing values for widgets with multiple 
- [x] Submit Form CSA

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-3338yaz Not able to use data from form, for the query with confirmation box,](https://app.clickup.com/t/3338yaz)

**Comment by shubh22** [comment]
Task linked: [CU-3338acz Form submit should have CSA (Suggestion :) )](https://app.clickup.com/t/3338acz)

**Comment by shubh22** [comment]
Task linked: [CU-32xjbmc The filepicker on the form is not visible in the inspector.](https://app.clickup.com/t/32xjbmc)

**Comment by shubh22** [comment]
Task linked: [CU-32xjavg Form widget not exposing values for widgets with multiple values](https://app.clickup.com/t/32xjavg)

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
