### PR TITLE
added component specific action to Dropdown Widget

### LINKED ISSUE #3495: Add : Component specific action to Dropdown
Environment -
Development

Feature Request - Add component-specific action to dropdown widget

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #3495

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2hjk4w3 Component specific action -  Dropdown](https://app.clickup.com/t/2hjk4w3)

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @manishkushare , please make the following changes:

1. Change handle to `selectOption`
2. Change action name to 'Select option'
3. Fire the `onSelect` event on the `then` of the `setExposedVariable` you're invoking when the action is called
4. If the value is not a part of the set of available options, then the exposed value should be `undefined`

**Comment by manishkushare** [comment]
@sherfin94 , made the suggested changes, please take a look at it

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @manishkushare it does not work when I set the target option to `{{1}}`

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
