### PR TITLE
[Feature] Update Manage user Archive and Unarchive button style

### LINKED ISSUE #2792: Manage user Archive and Unarchive button style
### Is your proposal related to a problem?
Manage user page Archive and Unarchive button does not have a look and feel of a button
three dots are appearing on click and table structure in changing

https://www.loom.com/share/f8396f1ee742470bb0953222757218f1

### Describe the solution you'd like
Add look and feel of a button to Archive and Unarchive, add loading  icon on API call

Screenshot 2022-04-12 at 9 57 55 AM

### If the feature is approved, would you be willing to submit a PR?
No

### PR DESCRIPTION
**Pull request by eyuelberga**
Resolves #2792

### CODE REVIEW

**Comment by gsmithun4** [comment]
Deployed
https://tj-pr.herokuapp.com/

**Comment by gsmithun4** [comment]
Shall we add `min-width: 100px` style to button, so that all button width remains same

Screenshot 2022-05-20 at 10 20 46 AM

**Comment by gsmithun4** [comment]
shall we reduce the top and bottom padding to `30px`? the button looks big now

**Review by gsmithun4 — CHANGES_REQUESTED** [review]
Style changes

**Comment by eyuelberga** [comment]
I added `btn-sm` class to the button and also set inline-style for min-width
tooljet_screenshot

**Review by gsmithun4 — APPROVED** [review]
LGTM

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Case

Test Case | Steps | Result
-- | -- | --
Should be able to view Archive button. | Create an application. | Application gets created.
  | Hover over my workspaces. | The options get displayed
  | Click on manage users. | Manage users page is opened.
  | Click on invite users. | Invite user page is displayed.
  | Enter first & last name & email address. | First & last name & email address is entered.
  | Click on create user. | User is created & list of all users is displayed.
  | Observe. | The archive button is visible with red color.
Should be able to view Unarchive button. | Create an application. | Application gets created.
  | Hover over my workspaces. | The options get displayed
  | Click on manage users. | Manage users page is opened.
  | Click on invite users. | Invite user page is displayed.
  | Enter first & last name & email address. | First & last name & email address is entered.
  | Click on create user. | User is created & list of all users is displayed.
  | Click on archive button. | The unarchive button with green color is visible.


</body>
</html>

**Pull request merged**
