### PR TITLE
fix(editor): avoid empty slug in share URL

### LINKED ISSUE #1288: Empty slug in share application URL
### Environment

ToolJet Cloud
### What is the expected behaviour?

Slug id should not be empty
### What is the current behaviour?

Slug id can be empty
### How to reproduce the issue?

1. Open share modal in editor
2. Add spaces in slug id
3. Copy the URL 

### Screenshots or Screencast

Empty Slug Id

### Any possible solutions?
Prevent spaces to be considered as valid

### If the bug is confirmed, would you be willing to submit a PR?
yes

### PR DESCRIPTION
**Pull request by jyash97**
Closes #1288

### CODE REVIEW

**Comment by jyash97** [comment]
@Navaneeth-pk  Facing issues with heroku deploy. Maybe screen recording will help: 
Empty slug url

**Comment by Navaneeth-pk** [comment]
If the slug is empty, the field should be shown empty but when the user click on the copy icon, we will copy the URL that includes the id of the application?
@jyash97

**Comment by jyash97** [comment]
Hey @Navaneeth-pk  👋

Yes in case of empty slug (entered by user) , on copying the url will contain application id, else it just goes to `/application`

**Comment by Navaneeth-pk** [comment]
closing as this change is not required now.

**Pull request closed without merging**
