### PR TITLE
Added automation for datasource connection.

### PR DESCRIPTION
**Pull request by emidhun**
Fixes: #5090 
  - Redis
  - MongoDB
  - Firestore
  - Bigquery

### CODE REVIEW

**Comment by emidhun** [comment]
Screenshot 2022-12-29 at 10 42 26 AM
@Navaneeth-pk Please have a look into this.

**Comment by shubh22** [comment]
Task linked: [CU-2x6f09w Add cypress test for google doc integration [WIP -  On hold till table widget spec completion]](https://app.clickup.com/t/2x6f09w)

**Review by sherfin94 — DISMISSED** [review]

**Comment by sherfin94** [comment]
@emidhun , please look into the conflicts.

**Comment by emidhun** [comment]
@sherfin94 Resolved conflicts,
Could you please check once?

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
