### PR TITLE
docs: added Env dropdown section in the TopBar doc

### PR DESCRIPTION
**Pull request by Abhinav-CHD**
[Fixed ](docs: added Env dropdown section in the TopBar doc #8455

### CODE REVIEW

**Review by karan-rathod-316 — CHANGES_REQUESTED** [review]
Hi @Abhinav-CHD, 

You are currently replacing the old images with new ones. This will add the new images in all the older versions as well. Can you suffix the images with v2 and also leave older images so that the older versions are not affected?

For e.g. the new image of `profile.png` can be named `profile-v2.png`. And then, refer the ones with v2 in the docs for the latest version.

**Comment by Abhinav-CHD** [comment]
@karan-rathod-316, sure I will add v2 to new images and leave previous unmodified.

**Comment by Abhinav-CHD** [comment]
Hi @karan-rathod-316, any update on this?

**Comment by 2001asjad** [comment]
Hi @Abhinav-CHD , let me confirm with the team and get back to you.

**Comment by karan-rathod-316** [comment]
> Hi @karan-rathod-316, any update on this?

Hi @Abhinav-CHD, this will be reviewed by EOD today.

**Comment by karan-rathod-316** [comment]
@Abhinav-CHD This is merged with #9334. Your commit is visible on that branch. Please check:-).

**Pull request closed without merging**
