### PR TITLE
[docs]: changes made in Cloud Firestore data source reference

### LINKED ISSUE #7599: [docs]: changes required in Cloud Firestore data source reference
### Summary

There are a few changes required in the [Cloud Firestore](https://docs.tooljet.com/docs/data-sources/firestore) reference doc:
- Add a desctription above `Connection`
```
ToolJet can connect to Cloud Firestore databases to read and write data.
```
- Update the description of the `Connection` to
```
ToolJet connects to your Cloud Firestore using JSON key of your GCP service account. Get your service account key as JSON from GCP console. For generating a new key, check out [Firestore's official documentation](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#iam-service-account-keys-create-console).

Once you have the key, open it in a text editor and copy the contents. Paste the contents in the **Private key** field of the Firestore data source modal.

Click on **Test connection** button to verify if the key is valid. Click on **Save** button to save the data source.
```

Make the above changes in the following:

1. `docs/docs`
2. `docs/versioned_docs/version-2.19.0`
3. `docs/versioned_docs/version-2.18.0`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/firestore

### Steps to reproduce the issue

_No response_

### Additional Information

_No response_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by shelar1423**
Issue  
fix #7599

**- There are a few changes made in the [Cloud Firestore](https://docs.tooljet.com/docs/data-sources/firestore) reference doc:**

- Added  a desctription above Connection:

`ToolJet can connect to Cloud Firestore databases to read and write data.`

- Updated  the description of the Connection to:

```
ToolJet connects to your Cloud Firestore using JSON key of your GCP service account. Get your service account key as JSON from GCP console. For generating a new key, check out [Firestore's official documentation](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#iam-service-account-keys-create-console).

Once you have the key, open it in a text editor and copy the contents. Paste the contents in the **Private key** field of the Firestore data source modal.

Click on **Test connection** button to verify if the key is valid. Click on **Save** button to save the data source.
```

- Made  the above changes in the following:

`
docs/docs`
`docs/versioned_docs/version-2.19.0
`
`docs/versioned_docs/version-2.18.0`

### CODE REVIEW

**Review by withshubh — APPROVED** [review]
LGTM 🚀

**Comment by shelar1423** [comment]
@withshubh  so will this be mreging today or how is it gonna be ?

**Comment by shelar1423** [comment]
@withshubh what does this workflow approval required mean ?im new to this .

**Comment by shelar1423** [comment]
@withshubh @tejakummarikuntla when will this be mreged?

**Pull request merged**
