### PR TITLE
refactor/Issue:#7522-Description -Update

### PR DESCRIPTION
**Pull request by ghOst-vedant**
[refactor]:Updated-Descriptions(tooltips) for calendar, iframe, code editor and tabs components 

issue #7522

<table class="demo">
	<tbody>
	<tr>
		<td>Screenshot 2023-09-29 at 3 38 13 PM</td>
		<td>Screenshot 2023-09-29 at 3 38 22 PM</td>
	</tr>
	<tr>
		<td>Screenshot 2023-09-29 at 3 38 44 PM</td>
		<td>Screenshot 2023-09-29 at 3 38 30 PM</td>
	</tr>
	</tbody>
</table>

### CODE REVIEW

**Comment by ghOst-vedant** [comment]
@karan-rathod-316

**Comment by ghOst-vedant** [comment]
@akshaysasidrn hello sir can u please review.

**Comment by ghOst-vedant** [comment]
@tejakummarikuntla is there any issue

**Comment by ghOst-vedant** [comment]
@adishM98 is anything wrong ??

**Review by tejakummarikuntla — APPROVED** [review]

**Pull request merged**
