### PR TITLE
Corrected spellings in heroku deployment guide

### PR DESCRIPTION
**Pull request by Blazing-Mike**

### CODE REVIEW

**Comment by arpitnath** [comment]
Hi @Blazing-Mike, thanks for contributing to ToolJet! Is there any issue related to this?

cc: @withshubh

**Comment by Blazing-Mike** [comment]
@arpitnath there is no issues related to this. Thanks.

**Comment by arpitnath** [comment]
@Blazing-Mike Can you please create one and mention the issue in the Pull request?

**Comment by Blazing-Mike** [comment]
@arpitnath can confirm if this is correct.

**Review by withshubh — APPROVED** [review]

**Pull request merged**
