### PR TITLE
Place text 'unsaved changes' instead of loader for whole saving process in editor. 

### LINKED ISSUE #3658: Place text 'unsaved changes' instead of loader for whole saving process in editor.
### Is your proposal related to a problem?
Currently we have loader for whole saving process.

### Describe the solution you'd like
Place text 'unsaved changes' instead of loader for whole saving process

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #3658

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2me3cxh Place text 'unsaved changes' instead of loader for whole saving process in editor.](https://app.clickup.com/t/2me3cxh)

**Comment by kavinvenkatachalam** [comment]
As discussed, hide the loader and change the text to `Saving...` while saving the changes

**Comment by gondar00** [comment]
Also, need to set `versionSaving` to false in catch block [here](https://github.com/ToolJet/ToolJet/blob/ef63057e0a2807e0731165200e899e1decc57b81/frontend/src/Editor/Editor.jsx#L1073)

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Pull request merged**
