### PR TITLE
[localization] Created the it file translation

### PR DESCRIPTION
**Pull request by TheZal**
Added the language to the `language.json` file and translated the global strings.
This solves issue #4257

### CODE REVIEW

**Comment by withshubh** [comment]
> @withshubh is this ok?

Thanks for creating the PR. Will review it soon.

**Review by withshubh — APPROVED** [review]

**Comment by Navaneeth-pk** [comment]
@TheZal please resolve merge conflicts.

**Comment by TheZal** [comment]
@Navaneeth-pk done! :)

**Comment by withshubh** [comment]
Hey @TheZal 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
