### PR TITLE
Input enter onsubmit

### PR DESCRIPTION
**Pull request by developer-honoru**
https://user-images.githubusercontent.com/33475816/183082217-9e2d8fce-412f-4dfd-868f-f14f78ce4f9f.mp4

### CODE REVIEW

**Comment by developer-honoru** [comment]
#3754

**Comment by sherfin94** [comment]
Hey @developer-honoru , could you change the event name from onSubmit to onEnterPressed?

**Comment by developer-honoru** [comment]
물론이죠 @sherfin94

**Comment by developer-honoru** [comment]
image
@sherfin94 I just changed the name, but I get an error. Do you have any guesses?

**Comment by developer-honoru** [comment]
image

**Comment by developer-honoru** [comment]
image
@sherfin94 I just changed the name, but I get an error. Do you have any guesses?

**Pull request closed without merging**
