### PR TITLE
Add default value for text widget

### PR DESCRIPTION
**Pull request by nik132-eng**
image

### CODE REVIEW

**Comment by nik132-eng** [comment]
Is this correct sir?

**Comment by nik132-eng** [comment]
@arpitnath can you please check out this PR?

**Comment by nik132-eng** [comment]
done sir

**Comment by arpitnath** [comment]
@nik132-eng please could you share a screen recording?

p.s. don't call me sir 🙏🏻 🥶

**Comment by nik132-eng** [comment]
image

I don't know how to deploy this project. I build websites and only use Js there. I am a noob for opensource and just want to give it a try and learn from this. Some contributors and many YouTubers say that a good first issue is easy to solve so that's why I gave it a try. I literally don't know how to operate this project sorry from my site. 

if I talked much sorry for that.

**Comment by nik132-eng** [comment]
image

**Comment by arpitnath** [comment]
https://user-images.githubusercontent.com/67645175/138270327-8e0f091d-a08e-424b-919c-ac76283109c9.mov

You have changed the Property Label Name

**Comment by nik132-eng** [comment]
if all things are perfect so can you please merge this PR into the repo? @arpitnath

**Pull request merged**
