### PR TITLE
Added validation for input fields on manage SSO page

### LINKED ISSUE #3320: Add validation for input fields on manage SSO page
### What is the expected behaviour?

1. The input fields on the manage SSO pages are required.
2. The success toast in the general settings page should be  `updated SSO configurations`

### What is the current behaviour?

1. The input fields on the manage SSO pages are not required.
3. The success toast in the general setting is `updated sso configurations`

### How to reproduce the issue?

1.
4.
5.

### Screenshots or Screencast
[Video](https://www.loom.com/share/76bfb64abcf44d6383e22529bbab1c64)

### Any possible solutions?

1. Add mandatory markings.
2. Update toast message.

### PR DESCRIPTION
**Pull request by vedant-z**
Fixes #3320

### CODE REVIEW

**Comment by vedant-z** [comment]
@ajith-k-v Please review the changes

**Comment by gsmithun4** [comment]
@vedant-z Please rebase, that will fix the lint issues

**Comment by vedant-z** [comment]
Hello @gsmithun4 sir!

If you could elaborate a little on how and what to rebase it would be of great help.

**Comment by gsmithun4** [comment]
> Hello @gsmithun4 sir!
> 
> Sorry this might be a very basic thing but I have never ran into such issue.
> 
> If you could elaborate a little on how and what to rebase it would be of great help.

Please merge this PR https://github.com/vedant-z/ToolJet/pull/1
It will add all the latest changes to your branch

**Comment by vedant-z** [comment]
Hello @gsmithun4 sir!

I have merged the PR.

**Comment by vedant-z** [comment]
Sorry sir for the inconvenience.

I think as I made the changes and created a PR for issue #3320 from GitHub Web interface it caused some issues.

**Comment by vedant-z** [comment]
Thanks for your HELP 🙌

**Comment by vedant-z** [comment]
@gsmithun4 

Sir, are there anymore changes left to complete this issue ?

**Comment by gsmithun4** [comment]
> @gsmithun4
> 
> Sir, are there anymore changes left to complete this issue ?

The lint issue persist, checking

**Comment by gsmithun4** [comment]
https://github.com/ToolJet/ToolJet/runs/7066438773?check_suite_focus=true
can you please fix the lint issue?

**Comment by vedant-z** [comment]
Sure Sir !!

I will try my best.

**Comment by withshubh** [comment]
Hey @vedant-z 👋 
Just following up - were you able to fix this? You can ask questions on our [Slack Community](https://tooljet.slack.com/join/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg#/shared-invite/email) if you have any doubts.

**Comment by vedant-z** [comment]
@vedant-z Hii!

Actually I am busy with my end semister exams, so I couldn't work on this currently.

But I think by --->
Disabling the prettier extension 
And setting Default format to false 

The issue will be solved.

**Comment by withshubh** [comment]
Hey @vedant-z 👋 
Would you be able to continue working on this PR?

**Comment by vedant-z** [comment]
@withshubh Yes I will resume working on this in 4-5 days..

My exams are ending so...

**Comment by vedant-z** [comment]
@withshubh 
I tried to fix the LINT issue but I am unable to do so.

If someone else wants to work on this you may unassign me with this issue.

**Comment by vedant-z** [comment]
@arpitnath Thanks Sir for fixing the Lint issue 🎊

**Comment by shivangT** [comment]
Hey @vedant-z 

Any updates on the following?

**Comment by vedant-z** [comment]
Hey @shivangT 

I think this issue has been solved.

Previously this was kept on hold because of failure of LINT test.

As of now all tests have passed after changes done by @arpitnath 

So I think this should be merged.

**Comment by shivangT** [comment]
Sure, thanks for the update.
We’ll get the review done and close it.

**Comment by vedant-z** [comment]
@shivangT Hi sir 

If this issue is solved on ToolJet's side then can you please try to merge this between 1-31 st October, as I am participating in Hacktoberfest this year 😊

**Comment by withshubh** [comment]
> @shivangT Hi sir
> 
> If this issue is solved on ToolJet's side then can you please try to merge this between 1-31 st October with hacktoberfest-accepted label, as I am participating in Hacktoberfest this year 😊

Hey @vedant-z 
I'm sorry but this won't be fair. I request you pick another issue and contribute. We will accept that under Hacktoberfest's contribution.

**Pull request closed without merging**
