### PR TITLE
perf: update resolve references fn call with use memo

### PR DESCRIPTION
**Pull request by gondar00**
fixes: #3982

### CODE REVIEW

**Review by kavinvenkatachalam — DISMISSED** [review]
LGTM

**Comment by kavinvenkatachalam** [comment]
@sherfin94 Can you please check this PR?

**Comment by sherfin94** [comment]
@gondar00 @kavinvenkatachalam General question, I'm worried that the elements inside the dependency arrays of the useMemo calls might have deep nested components, potentially making widgets not respond to those changes. What do you feel?

**Review by sherfin94 — COMMENTED** [review]
@gondar00 @kavinvenkatachalam General question, I'm worried that the elements inside the dependency arrays of the useMemo calls might have deep nested components, potentially making widgets not respond to those changes. What do you feel?

**Comment by gondar00** [comment]
It looks like react `useMemo` does a deep comparison check with the previous object on every render and thus prevents widgets not respond to those changes

**Comment by kavinvenkatachalam** [comment]
@sherfin94 Can you check this whenever you're available?

**Comment by gondar00** [comment]
@sherfin94 can you please have a look at this PR ?

**Review by kavinvenkatachalam — COMMENTED** [review]
I checked with the large app which was resolving the properties around `4800` times and now it got reduced to around `900`

**Review by kavinvenkatachalam — DISMISSED** [review]

**Comment by sherfin94** [comment]
Sorry @kavinvenkatachalam and @gondar00 , I kind of missed this, let me revert back to @shubh22 and see if we can get this merged into v1.31

**Comment by sherfin94** [comment]
Guys, we are moving this to v2-beta, I will merge it as soon as we merge `develop` to `v2-beta`

**Pull request closed without merging**
