### PR TITLE
Docs/google cloud run broken image fix

### LINKED ISSUE #6316: [docs version 2.4]: fix broken image in deployment doc for google cloud run
### Summary

- Go to the Setup -> Google Cloud Run doc: https://docs.tooljet.com/docs/2.4.0/setup/google-cloud-run
- On the step 4, you'll find the broken image

Solution:
- Go to the `docs/versioned_docs/version-2.4.0/setup/google-cloud-run.md`
- On line number 50 change the image name to `port-and-capacity-postgrest.png`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/2.4.0/setup/google-cloud-run

### Steps to reproduce the issue

_No response_

### Additional Information

_No response_

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by Abjcodes**
Fixes #6316

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @Abjcodes - The issue was not assigned to you. Please follow the contributing guidelines before making a pull request, not following might lead to closing the pull request.

**Review by withshubh — CHANGES_REQUESTED** [review]
Please remove all the unnecessary changes in the PR. Please keep only the change that fixes the broken image.

**Review by withshubh — CHANGES_REQUESTED** [review]
Hey @Abjcodes - Please read the issue description (mentioned in the PR description) properly. 
The fix is needed on the versioned_docs/version-2.4.
The fix that you added is on the base directory(docs/docs) which is not required. Please revert all the changes and make the correct changes.

**Comment by tejakummarikuntla** [comment]
Hey @Abjcodes, could you please share the progress with the requested changes? Feel free to let us know if you're looking for any help. Thank you.

**Pull request closed without merging**
