### PR TITLE
fix #10612 

### LINKED ISSUE #10612: Spacing Inside The Search Bar
### Expected Behavior

There should be some space between the search icon and the placeholder text to improve visual clarity.

### Current Behavior

The search icon and placeholder text appear stacked with minimal space between them, leading to a cluttered appearance.

### Steps to Reproduce

1. Create an account.
2. Navigate to /my-workspace/data-sources.
3. Observe the search bar for data sources.

### Screenshots

image  
image

### Possible Solution

Consider adding margin or padding to the icon to create space between the icon and the placeholder text.

### Code Location

The issue is likely within the associated CSS files.

### Willing to Submit a PR?

Yes, I am willing to submit a pull request to fix this issue.

### PR DESCRIPTION
**Pull request by Mudit-Jxin7**
Screenshot

image

### CODE REVIEW

**Review by monyishh — COMMENTED** [review]
I think it is good to go as it solved the problem.

**Comment by PriteshKiri** [comment]
Hey @monyishh,

Are you still working on the issue?

**Comment by PriteshKiri** [comment]
Closing the PR due to lack of progress

**Comment by PriteshKiri** [comment]
Closing this issue due to lack of progres

**Pull request closed without merging**
