### PR TITLE
Feature: port multi select to react select lib

### LINKED ISSUE #2550: Improvement: Change multi-select to react-select
### Is your proposal related to a problem?

Port multi-select to react select component
- Also this widget should contain an optional option for selecting/unselecting all options

### Describe the solution you'd like

Replace current select lib with react-select 

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Resolves #2550

### CODE REVIEW

**Review by Moode09 — DISMISSED** [review]

**Comment by sherfin94** [comment]
The exposed variable `values` presently is an array of objects, whereas it used to be an array of values of the selected options. Please change it back to that, for backward compatibility

image

**Comment by sherfin94** [comment]
The close button width seems to be a bit out of bounds
image

**Comment by sherfin94** [comment]
Please make the height of the selected options smaller and fixed, so that even if there are many selected options, it can be properly fit (given that the developer has given enough height for the multiselect).

That is, it should be able to look like this, if there are many selected options:
image

**Comment by sherfin94** [comment]
Would it be possible to not include `All` as a selection on the multiselect when it is selected and only show it on the options? To deselect all, we already have the `X` button on the right side.

image

**Review by sherfin94 — CHANGES_REQUESTED** [review]
I've mentioned some changes on the comments.

**Review by Moode09 — APPROVED** [review]

**Comment by stepinfwd** [comment]
updated changes @sherfin94

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
