### PR TITLE
The position of icon to expand the code editor in new window is  fixed

### LINKED ISSUE #6542: [UI]: The position of icon to expand the code editor in new window is not fixed
### What is the expected behaviour?
The icon position should be fixed, so that if there is large amount of data and user scrolls down in the code editor grid, the icon should always be visible

### What is the current behaviour?
The icon only appears at the top right side, and on scroll it is not accessible.
Also the window close icon takes some time to load.

### How to reproduce the issue?

1. Drag any component like table or chart
2. Enter some data in code editor and try to scroll down
3. Verify if the icon to open/expand  the code editor is visible or not

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/e973c07d-e327-411a-9fe8-d5e1e5ffe8f3

### PR DESCRIPTION
**Pull request by ShahriyaSiddique**
[UI]: The position of icon to expand the code editor in new window is not fixed #6542

### CODE REVIEW

**Comment by withshubh** [comment]
Please comment on the issue so that I assign that to you.

**Comment by johnsoncherian** [comment]
Hi @ShahriyaSiddique thanks for the contribution. The fix is working as expected for the code hinter inputs inside widget inspector. However its breaking the behaviour of the same in other parts. (Refer below video)
Suggestion: Use position absolute and top css properties on popup icon and position relative to its parent to align it fixed at the top.

https://github.com/ToolJet/ToolJet/assets/57667706/0fb5d4eb-f8ff-4c1a-afe6-85ab29d3c1d5

**Review by johnsoncherian — CHANGES_REQUESTED** [review]
This change is breaking the behaviour of icon button in other parts of the app. Refer comment: https://github.com/ToolJet/ToolJet/pull/6676#issuecomment-1591082020

**Comment by withshubh** [comment]
Hey @ShahriyaSiddique - Please update the PR with the suggested changes.

**Comment by ShahriyaSiddique** [comment]
> Hi @ShahriyaSiddique thanks for the contribution. The fix is working as expected for the code hinter inputs inside widget inspector. However its breaking the behaviour of the same in other parts. (Refer below video) Suggestion: Use position absolute and top css properties on popup icon and position relative to its parent to align it fixed at the top.
> 
>  Screen.Recording.2023-06-14.at.5.42.11.PM.mov

I have tried your mentioned way. But it's not working. Do you have any other guidelines?

**Comment by johnsoncherian** [comment]
> Hey @ShahriyaSiddique - Please update the PR with the suggested changes.

Add below classes and styles to PopupIcon component

```
const PopupIcon = ({ callback, icon, tip, transformation = false }) => {
  const size = transformation ? 20 : 12;

  return (
    <div className="d-flex justify-content-end w-100 position-absolute" style={{ top: 0 }}>
      <OverlayTrigger
```

and then add class `position-relative` to divs in line 305 and 222.
Requesting you to test this changes as well once. Thanks.

**Comment by ShahriyaSiddique** [comment]
> > Hey @ShahriyaSiddique - Please update the PR with the suggested changes.
> 
> Hi @ShahriyaSiddique sure. Please try below given changes and test once. You may have to make some minor additional changes but should work.
> 
> Add below classes and styles to PopupIcon component
> 
> ```
> const PopupIcon = ({ callback, icon, tip, transformation = false }) => {
>   const size = transformation ? 20 : 12;
> 
>   return (
>     <div className="d-flex justify-content-end w-100 position-absolute" style={{ top: 0 }}>
>       <OverlayTrigger
> ```
> 
> and then add class `position-relative` to divs in line 305 and 222.

Updated the PR. Please review the changes.

**Review by johnsoncherian — APPROVED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]

**Pull request merged**
