### PR TITLE
fix: Marketplace scrollbar issue on /integrations route

### LINKED ISSUE #6818: Marketplace: display scrollbar only if the items exceed on the page
#### Current Behavior:
The Installed & Marketplace page in ToolJet displays a scrollbar at all times, even when there are no items present on the page.

#### Steps to Reproduce:

1. Set up ToolJet locally.
2. Enable the Marketplace feature following the instructions provided in the ToolJet documentation (https://docs.tooljet.com/docs/contributing-guide/marketplace/marketplace-setup).
3. Navigate to the Marketplace section.
4. Observe that a scrollbar is present on the page, regardless of the number of items displayed.

#### Expected Solution:
To resolve this issue, the scrollbar should only appear when the number of items on the page exceeds the available space. When there are no items or when the items fit within the page, the scrollbar should not be displayed, providing a more visually streamlined and intuitive user interface.
### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/25361949/9c8561f9-b341-4a2d-be90-b71d44796697

### PR DESCRIPTION
**Pull request by ShyanRoyChoudhury**
This PR solves the scrollbar issue on /integrations route. Now when the items exceed the page only then the scroll is activated.  Thus, providing a more visually streamlined and intuitive user interface.

fixes #6818

### CODE REVIEW

**Comment by akshaysasidrn** [comment]
@ShyanRoyChoudhury can we solve the issue without adding custom CSS?
You should be able to leverage bootstrap classes to achieve the same.

**Comment by ShyanRoyChoudhury** [comment]
Sure. Let me take a look. @akshaysasidrn

**Comment by PriteshKiri** [comment]
Hey @ShyanRoyChoudhury, any updates of the PR?

**Comment by ShyanRoyChoudhury** [comment]
My apologies for the delay. Will update the PR soon @PriteshKiri

**Comment by priteshTJ** [comment]
Hey @ShyanRoyChoudhury, any updates on the PR? Please let me know if you are facing any issue.

**Comment by PriteshKiri** [comment]
@ShyanRoyChoudhury can you please brief us more about the issue? so that @akshaysasidrn can help.

**Comment by akshaysasidrn** [comment]
Closing this in favour of [PR](https://github.com/ToolJet/ToolJet/pull/10163).
Thank you for your attempt.

**Pull request closed without merging**
