### PR TITLE
[feature] Added maximum canvas height property

### LINKED ISSUE #2907: Add maximum canvas height option
### Is your proposal related to a problem?

Currently, there is no option to limit canvas height. now canvas has fixed max-height

### Describe the solution you'd like

Add a property in the global settings popup 

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Resolves #2907
[heroku](https://canvas-height.herokuapp.com/)

### CODE REVIEW

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Cases

Test Case | Steps | Result
-- | -- | --
Canvas height can be entered as 2400 as the highest. | Create an application. | Application gets created.
  | Click on the settings. | The height of the canvas is set to 2400.
  | Try change it to more than 2400. | It does not go beyond 2400.


</body>
</html>

**Comment by gondar00** [comment]
image
@shah21 can we add a info icon beside the text max height of canvas and on hover of info icon it says max height is 2400px?

**Comment by shah21** [comment]
> image
> 
> @shah21 can we add a info icon beside the text max height of canvas and on hover of info icon it says max height is 2400px?

Sure

**Review by sherfin94 — APPROVED** [review]

**Comment by sherfin94** [comment]
@gondar00 Merging this PR since @shah21 is making the enhancement you suggested a community issue.

**Pull request merged**
