### PR TITLE
Fixed query database operation typo

### PR DESCRIPTION
**Pull request by mazkaaa**
Fix typo in the operation for Notion data source https://github.com/ToolJet/ToolJet/issues/2975

### CODE REVIEW

**Review by arpitnath — CHANGES_REQUESTED** [review]
@mazkaaa Please revert the changes done in the `package-lock.json` files

**Comment by mazkaaa** [comment]
> @mazkaaa Please revert the changes done in the `package-lock.json` files

Hi, I have no idea how to revert to the latest commit before mine properly, so I reverting using the manual way. https://github.com/ToolJet/ToolJet/pull/3041/commits/1ea07311d00501f5583e5ab8bef9e51240e93764

**Comment by Navaneeth-pk** [comment]
@mazkaaa  please remove the unwanted changes in this PR, there are more than 10k lines of changes.

**Comment by mazkaaa** [comment]
> @mazkaaa please remove the unwanted changes in this PR, there are more than 10k lines of changes.

It’s s removed now.

**Review by arpitnath — APPROVED** [review]

**Pull request merged**
