### PR TITLE
Added info popovers for maintenance mode and maximum canvas height features

### LINKED ISSUE #3009: Add info icons for maintenance mode, max height of canvas features
### Is your proposal related to a problem?

167352317-61e36208-5fa7-40d8-8b6c-798ac7f23ccb

Screenshot 2022-05-09 at 2 26 30 PM

Currently, maintenance mode & canvas height features don't have an info icon to describe the feature

### Describe the solution you'd like

Add an info icon beside the texts and show a short description of the particular option. 
like, 
for **maximum canvas height** "max height is 2400px"

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?
No

### PR DESCRIPTION
**Pull request by shah21**
Resolves #3009

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2hr9qy6 Add info popovers for maintenance mode and maximum canvas height features](https://app.clickup.com/t/2hr9qy6)

**Comment by shubh22** [comment]
Task linked: [CU-2hr9qc7 Add info popovers for maintenance mode and maximum canvas height features](https://app.clickup.com/t/2hr9qc7)

**Comment by sherfin94** [comment]
@shah21 Putting on hold in sync with click up.

**Comment by sherfin94** [comment]
Closing as there is no activity for a long time.

**Pull request closed without merging**
