### PR TITLE
Copy button added for links in manage sso / general settings

### LINKED ISSUE #3415: Copy option for URL's in manage sso / general settings
### Is your proposal related to a problem?
Currently no option to copy url's with single click.

### Describe the solution you'd like
Add a button to copy the links.

### If the feature is approved, would you be willing to submit a PR?
YES.

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #3415

### CODE REVIEW

**Comment by gsmithun4** [comment]
@stepinfwd Shall we show a `Login URL/ Redirect URL copied` message

**Comment by stepinfwd** [comment]
updated with changes @gsmithun4

**Comment by gsmithun4** [comment]
@stepinfwd please fix the dark theme style
Screenshot 2022-07-09 at 1 24 36 AM

**Comment by stepinfwd** [comment]
fixed dark mode issues @gsmithun4

**Review by gsmithun4 — APPROVED** [review]
LGTM

**Pull request merged**
