### PR TITLE
Updated the Twitter Logo to New Logo ( X )

### LINKED ISSUE #7907: Update the Twitter Logo to New Logo ( X ).
Update the Twitter Logo to the latest Logo ( X )

### Describe the solution you'd like

As we know Twitter's name and Logo have been changed. So I would like to change the Logo to X on the docs page of Tooljet. 

image

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by niranjan-kurhade**
In this PR, I updated the Twitter logo to its latest one. This PR fixes #7907 

**Screenshots**

image

image

### CODE REVIEW

**Comment by niranjan-kurhade** [comment]
Hey @withshubh, I didn't know that signing commits was a compulsory thing. In the review, I came to know about it. So what should I do now? 

Also Please review the PR!

**Comment by tejakummarikuntla** [comment]
Hey @niranjan-kurhade, while @withshubh reviews the PR, could you please sign the CLA?

**Comment by niranjan-kurhade** [comment]
> Hey @niranjan-kurhade, while @withshubh reviews the PR, could you please sign the CLA?

Hey @tejakummarikuntla, Sorry but can you please quickly guide me with signing the CLA?
I was thinking of making a new PR as I didn't sign it, Any other faster way of doing that? How should I do it?

**Comment by niranjan-kurhade** [comment]
> Hey @niranjan-kurhade, while @withshubh reviews the PR, could you please sign the CLA?

Hey @tejakummarikuntla, I have signed the CLA. 
Also @withshubh, Please review and merge if everything is proper.

**Comment by niranjan-kurhade** [comment]
> Hey @niranjan-kurhade, while @withshubh reviews the PR, could you please sign the CLA?

Hey @tejakummarikuntla, I have signed the CLA.
Also @withshubh, Please review and merge if everything is proper.

**Comment by niranjan-kurhade** [comment]
> > Hey @niranjan-kurhade, while @withshubh reviews the PR, could you please sign the CLA?
> 
> Hey @tejakummarikuntla, I have signed the CLA.

Hey @withshubh @arpitnath @adishM98 @johnsoncherian @kavinvenkatachalam Can you review and merge this PR.

**Comment by niranjan-kurhade** [comment]
> > Hey @niranjan-kurhade, while @withshubh reviews the PR, could you please sign the CLA?
> 
> Hey @tejakummarikuntla, I have signed the CLA.

Hey @withshubh @arpitnath @adishM98 @johnsoncherian @kavinvenkatachalam Can you review and merge this PR.

**Review by withshubh — APPROVED** [review]

**Pull request merged**
