### PR TITLE
Add border color property to number input widget

### PR DESCRIPTION
**Pull request by Srisuma13**
fixes https://github.com/ToolJet/ToolJet/issues/4166

### CODE REVIEW

**Comment by Srisuma13** [comment]
@arpitnath Could you please review this PR? Also, do I need to deploy the demo as well for this?

**Comment by arpitnath** [comment]
@Srisuma13 Thanks for contributing to ToolJet 🚀
We shall review your PR soon, till then you can check out issues with [hactoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) tags.

**Review by arpitnath — CHANGES_REQUESTED** [review]
Please can you add a default value for in the widget definitions in the **widgetConfig.js**?

**Review by arpitnath — APPROVED** [review]

**Comment by arpitnath** [comment]
@Srisuma13 LGTM! Can you please resolve the conflicts?

**Comment by Srisuma13** [comment]
> @Srisuma13 LGTM! Can you please resolve the conflicts?

done @arpitnath

**Review by arpitnath — APPROVED** [review]

**Comment by kavinvenkatachalam** [comment]
@Srisuma13 Can you please resolve the conflicts?

**Comment by Srisuma13** [comment]
> @Srisuma13 Can you please resolve the conflicts?

done @kavinvenkatachalam @arpitnath

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @Srisuma13 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
