### PR TITLE
Add missing sourceOptions to Snowflake to fix the warehouse/database/schema/role when connecting

### PR DESCRIPTION
**Pull request by joshuataylor**
Snowflake is missing various sourceOptions, which means that role is passing in as public, so the role defined in the UI isn't working. Also added the other missing sourceOptions.

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
You might need to commit the package lockfile too if package.json is being modified. @joshuataylor

**Comment by joshuataylor** [comment]
I have reverted the change for the version bump.

**Comment by Navaneeth-pk** [comment]
Thanks @joshuataylor !

@akshaysasidrn can you please review the PR?

**Review by akshaysasidrn — APPROVED** [review]

**Comment by Navaneeth-pk** [comment]
@joshuataylor can you please resolve the lint errors so that we can merge this PR?

**Comment by akshaysasidrn** [comment]
@joshuataylor could you please fix the lint error?

**Comment by akshaysasidrn** [comment]
Merging this. Will fix lint separately. Thank you for your contribution.

**Pull request merged**
