### PR TITLE
Template: Created digital marketing campaign manager

### PR DESCRIPTION
**Pull request by Ranit-Bandyopadhyay**
Added template for digital marketing campaign manager

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
@Ranit-Bandyopadhyay  can you please update the title of PR so that the purpose of PR is clear?

**Comment by Ranit-Bandyopadhyay** [comment]
This tool empowers users to build and append UTM tags (Urchin Tracking Module) to URLs. These tags act like short codes added to URLs, enabling to track the source and campaign details of your website traffic. They offer valuable insights for website owners and marketers.
Features
UTM tag builder
UTM tag viewer with ToolJet DB

**Comment by karan-rathod-316** [comment]
Hi @Ranit-Bandyopadhyay,  `Update definition.json` makes it very confusing to understand the purpose of this PR. Please update it.

**Comment by karan-rathod-316** [comment]
Fixes #9203

**Comment by karan-rathod-316** [comment]
Hi @Ranit-Bandyopadhyay, thank you for your contribution. This is under review.

**Review by abhinabaadhikari — APPROVED** [review]

**Pull request merged**
