### PR TITLE
[HF23-docs] Fixes/Updated DOCS on requirenment

### LINKED ISSUE #7540: [docs]: changes required in Airtable data source reference
#### There are a few changes required in the [Airtable data source](https://docs.tooljet.com/docs/data-sources/airtable) reference doc:
1. Replace the following text in description `Airtable API key is required to create an Airtable data source on ToolJet. You can generate API key by visiting [Airtable account page](https://airtable.com/account). ` with the text below:
	  ```
	Airtable Personal Access Token is required to connect to the Airtable data source on ToolJet. You can generate the PAT by visiting [Developer Hub from your Airtable profile](https://support.airtable.com/docs/creating-and-using-api-keys-and-access-tokens#understanding-personal-access-token-basic-actions)
  	```
2. Rename the heading `Supported Queries` to `Supported Operations`
3. Remove the `TIP: This guide assumes that you have already gone through Adding a data source tutorial.`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/data-sources/airtable

### Steps to reproduce the issue

_No response_

### Additional Information

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by omkarvilasmote**
PR :-
updating the old Docs to new on requirenment

fixes #7540

### CODE REVIEW

**Review by withshubh — CHANGES_REQUESTED** [review]
Could you please make the same changes in the `versioned_docs` `version-2.18.0` & `2.19.0`

**Comment by omkarvilasmote** [comment]
@withshubh yes i can change it

**Comment by omkarvilasmote** [comment]
@withshubh I don't understand what it means in version 2.18.0 & 2.19.0

**Comment by withshubh** [comment]
Please make the suggested changes

**Comment by omkarvilasmote** [comment]
wait i am pushig the pull new with a version changes

**Comment by omkarvilasmote** [comment]
or anything more changes?

**Pull request closed without merging**
