### PR TITLE
Small fixes for Server-side filter button (#4571)

### LINKED ISSUE #4571: Hide `server side filter` option in table when `Show filter button` is disabled
### Is your proposal related to a problem?

1. Currently option for `Server side filter` is shown even when the `Show filter button` is disabled.
2. `Server side filter` option is placed at the bottom of the list, rather it should be right below the `Show filter button

### Describe the solution you'd like

1. If the `Show filter button` button is disabled, don't show the option for the `server side filter`. 
2. `Server-side filter` should be moved to just below the `Show Filter Button` button 

Note: Solve both these issues in a single PR.

### Steps to reproduce the issue
- On the app builder, drag the table widget and check the option

Screenshot 2022-10-23 at 6 36 21 PM

### PR DESCRIPTION
**Pull request by daniloff200**
fixes #4571

### CODE REVIEW

**Comment by gsmithun4** [comment]
deployed https://tj-4580.herokuapp.com/

**Review by arpitnath — APPROVED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Review by sherfin94 — APPROVED** [review]

**Review by sherfin94 — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @daniloff200 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Comment by daniloff200** [comment]
hi, @withshubh !
Thanks a lot for the link, I've submitted it! 💯

**Pull request merged**
