### PR TITLE
rename Workspace Environment Variables to Workspace Variables

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
closes https://github.com/ToolJet/ToolJet/issues/4289

cc @withshubh

### CODE REVIEW

**Review by withshubh — DISMISSED** [review]

**Comment by MrKrishnaAgarwal** [comment]
@withshubh Please review now, I have followed everything :)

**Review by withshubh — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
Can you merge it @Navaneeth-pk or @withshubh?

**Comment by MrKrishnaAgarwal** [comment]
Thank you @Navaneeth-pk 🙏🏻

**Comment by MrKrishnaAgarwal** [comment]
> Hey @MrKrishnaAgarwal Thanks for contributing to ToolJet. 🙌 Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

Thankyou @withshubh, I have filled the form.
Will I get any further updates on tracking or will I directly receive them at my doorstep?

**Comment by withshubh** [comment]
> > Hey @MrKrishnaAgarwal Thanks for contributing to ToolJet. 🙌 Please submit the form to claim your Hacktoberfest swag: [airtable.com/shr1qR6xhqsWO7LD7](https://airtable.com/shr1qR6xhqsWO7LD7)
> 
> Thankyou @withshubh, I have filled the form. Will I get any further updates on tracking or will I directly receive them at my doorstep?

We'll share more updates over the email once we start shipping swags.

**Comment by MrKrishnaAgarwal** [comment]
> > > Hey @MrKrishnaAgarwal Thanks for contributing to ToolJet. 🙌 Please submit the form to claim your Hacktoberfest swag: [airtable.com/shr1qR6xhqsWO7LD7](https://airtable.com/shr1qR6xhqsWO7LD7)
> > 
> > Thankyou @withshubh, I have filled the form. Will I get any further updates on tracking or will I directly receive them at my doorstep?
> 
> We'll share more updates over the email once we start shipping swags.

Okay, Thankyou!

**Pull request merged**
