### PR TITLE
Added border color option to Password Input widget

### PR DESCRIPTION
**Pull request by akarsh-jain-790**
Fixes: #4168

https://user-images.githubusercontent.com/72064462/197329575-3925080a-4a2b-430b-8142-02e6f6c588ed.mp4

### CODE REVIEW

**Comment by gsmithun4** [comment]
deployed https://tj-4558.herokuapp.com/

**Comment by gsmithun4** [comment]
@akarsh-jain-790 please fix the lint errors

**Comment by akarsh-jain-790** [comment]
> @akarsh-jain-790 please fix the lint errors

@gsmithun4 Done

**Review by arpitnath — DISMISSED** [review]

**Comment by arpitnath** [comment]
@akarsh-jain-790 Please fix the merge conflicts.

**Comment by akarsh-jain-790** [comment]
> @akarsh-jain-790 Please fix the merge conflicts.

@arpitnath Done

**Comment by arpitnath** [comment]
@akarsh-jain-790 can you fix the conflicts please 😅

**Review by kavinvenkatachalam — DISMISSED** [review]
LGTM

**Comment by akarsh-jain-790** [comment]
> @akarsh-jain-790 can you fix the conflicts please 😅

@arpitnath Done

**Review by kavinvenkatachalam — DISMISSED** [review]
LGTM

**Comment by Nandinisaha13** [comment]
Hey @akarsh-jain-790 I tried it on my windows for dark mode, the border color is hardly visible. Screenshot is attached.
password_bordercolor

**Comment by akarsh-jain-790** [comment]
> `181bdc8`

@Nandinisaha13 I have updated the PR, your can re-review

**Review by kavinvenkatachalam — APPROVED** [review]

**Pull request merged**
