### PR TITLE
Update theme.scss

### PR DESCRIPTION
**Pull request by atharvnaik1**
1. Implemented changes in theme.scss an respective files  for select month, year background in dark mode  , day is already correct.
2. Implemented changes in theme.scss and respective files input.react-datepicker-time__input background color from white to dark mode.
3. Updated the time popper for dark theme.
4.npm run build before start .

### CODE REVIEW

**Comment by johnsoncherian** [comment]
Hi @atharvnaik1 , Thanks for the contribution. Can you sync ur branch with latest develop and check this again. Looks like the style changes are not reflecting on the popup
image

**Comment by karan-rathod-316** [comment]
Hi @atharvnaik1, any updates on the suggested changes :-)?

**Comment by PriteshKiri** [comment]
Hey @atharvnaik1 ,

Did you get a chance to look at the suggested changes?

**Comment by PriteshKiri** [comment]
Closing this because of lack of progress.

**Pull request closed without merging**
