### PR TITLE
cursor pointer added fixes #6121

### LINKED ISSUE #6121: Change cursor to poiner on hover of toggle in Share dialogue box
Hovering the cursor over the toggle of Share dialogue box shows the `default` cursor.

image

Change the default cursor to the `pointer` on hovering over the toggle.

### PR DESCRIPTION
**Pull request by nazrul7711**
Fixes #6121

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @nazrul7711 - Could you please link to the issue the PR fixes?

**Comment by nazrul7711** [comment]
yes I have added fixes #6474 comment in the description

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
Hey @nazrul7711 - Thanks for the PR. 

It's not recommended to change the `tabler.scss` file directly. Because when we update the latest version of tabler SCSS and the changed might get replaced. So, please revert the changes from `tabler.scss` and do the changes in `theme.scss`. Attaching the screenshot how it can be done. Please let me know if you have any questions

image

**Comment by nazrul7711** [comment]
hey @kavinvenkatachalam i have made the changes

**Review by kavinvenkatachalam — APPROVED** [review]

**Pull request merged**
