### PR TITLE
[Feature]: CodeHinter preview for listItem, cellValue

### LINKED ISSUE #3372: [Feature]: CodeHinter Preview for listItem, cellValue
### Is your proposal related to a problem?

While working with the `List View` and `Table` widgets, the preview for the `listItem` and `cellValue` are not shown.

### Describe the solution you'd like

Preview can be shown with custom resolvables

### Describe alternatives you've considered

No

### If the feature is approved, would you be willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by kavinvenkatachalam**
Resolves #3372

### CODE REVIEW

**Review by sherfin94 — CHANGES_REQUESTED** [review]
When I merged with the latest develop and tested this, it seems to be affecting the functionality of List View when put inside another List View. I'll post the screen recording on the corresponding clickup issue as the video is a bit too big.

**Comment by kavinvenkatachalam** [comment]
> When I merged with the latest develop and tested this, it seems to be affecting the functionality of List View when put inside another List View. I'll post the screen recording on the corresponding clickup issue as the video is a bit too big.

@sherfin94 Fixed the issue for nested `Listview`

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @kavinvenkatachalam , the list view is not working on viewer mode.

**Comment by kavinvenkatachalam** [comment]
> Hey @kavinvenkatachalam , the list view is not working on viewer mode. (Actually no widgets are appearing on viewer mode)

My bad! The issue is fixed. Added a check for the `viewer` mode

**Review by sherfin94 — DISMISSED** [review]

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Everything works!, please resolve conflicts and we can merge.

**Pull request merged**
