### PR TITLE
fix: Update logic for queries filter

### PR DESCRIPTION
**Pull request by TheLearneer**
Basically added a temporary state with filtered queries so that original list of queries is kept as it is..

fixes: #3306

### CODE REVIEW

**Comment by TheLearneer** [comment]
Hi @arpitnath @withshubh 

I didn't realize the `create-review-app` label added to the PR.
Even after seeing it, I didn't realize it was asking me for review app??

However, I have deployed the local branch from which I am raising this PR i.e. `TheLearneer:fix-3306......` and it is available at <https://tooljet-tl.herokuapp.com/>

You can login with default email/password and check the code changes in action.

**NOTE:** Typing `boy` would make the test easier.

**Comment by withshubh** [comment]
Hey @TheLearneer 👋 

> Even after seeing it, I didn't realize it was asking me for review app??

It wasn't asking you, adding this label creates a deployment of this PR.

> I have deployed the local branch from which I am raising this PR i.e. TheLearneer:fix-3306...... and it is available at [tooljet-tl.herokuapp.com](https://tooljet-tl.herokuapp.com/)

I checked the fix on your deployment and it works fine.

Someone from the team will review the code soon! Thanks for contributing 🙌

**Comment by TheLearneer** [comment]
Ahh @withshubh I got a little confused with the label then.

Also regarding the pull request, it is indeed working fine, but seems like there has been some changes on the develop branch causing conflict in my PR.
I might need to look into it again.

**Review by gondar00 — APPROVED** [review]

**Comment by gondar00** [comment]
@TheLearneer please fix the merge conflict

**Comment by withshubh** [comment]
@TheLearneer Friendly bump - please fix the conflict

**Comment by TheLearneer** [comment]
Sorry for the delay, I got caught up on my job, so couldn't look up on this PR earlier.
I have fixed the merge conflict, please do let me know if there is any further issues 🙇

**Review by gondar00 — APPROVED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]

**Pull request merged**
