### PR TITLE
[ bug fixed ] : File is saved as csv while type is selected as text on event handler

### LINKED ISSUE #3692: File is saved as csv while type is selected as text on event handler
### Environment
ToolJet cloud

### What is the expected behaviour?
The file should be downloaded in text/doc format.

### What is the current behaviour?
The file is being downloaded as csv.

### How to reproduce the issue?

1. Drag & drop a button.
2. Add an event handler with action type as generate a file.
3. Select type as text and enter the data and name of file.
4. Click on the file.
5. The file uses csv as an extension to be saved.

### Screenshots or Screencast
https://drive.google.com/file/d/1Vpf1v96hUrCUqEHQ7xLczsCOJVz-W7pa/view?usp=sharing

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #3692

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2wfg2r9 generate file in text](https://app.clickup.com/t/2wfg2r9)

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare I tried changing the type from `Text` to `csv` and clicked the button. I don't see the file downloading. Can you check it out?

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by ritvikmathur1999** [comment]
Assign this issue to me, I'll resolve it.

**Comment by withshubh** [comment]
> Assign this issue to me, I'll resolve it.

Hey @ritvikmathur1999 👋 

Thanks for your interest in contributing to ToolJet. 

This PR is already approved, you can pick other open issues that are not assigned to anyone.

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by kavinvenkatachalam** [comment]
@manishkushare Can you fix the lint errors?

**Pull request merged**
