### PR TITLE
Fix: #8423 Link pricing page with badges

### PR DESCRIPTION
**Pull request by ayushjha119**
Link The pricing page with badges and also remove the unnecessary space  and linting issue due to my VS code

### CODE REVIEW

**Comment by ayushjha119** [comment]
@withshubh @karan-rathod-316  please check the latest commit , i think this will fix the issue

**Comment by ayushjha119** [comment]
@karan-rathod-316 can you check this??

**Review by karan-rathod-316 — APPROVED** [review]
LGTM

**Comment by karan-rathod-316** [comment]
Fixes #8423

**Pull request merged**
