### PR TITLE
Improvement: Filepicker - handle xlsx parsing

### LINKED ISSUE #3652: Filepicker improvement : handle parsing  Microsoft Excel (.xlsx) file
### Is your proposal related to a problem?
At the moment, we don't have support to parse .xls or .xlsx file

### Describe the solution you'd like
Add support to parse .xlsx file

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #3652

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2kbkz4g Handle .xls file parsing. (the auto-detect should take care)](https://app.clickup.com/t/2kbkz4g)

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Case

Test Cases | Steps | Result
-- | -- | --
Should be able to handle xls parsing. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed.
  | Update the file type as "application/vnd.ms-excel" | The file picker should accept xls file only.
  | Click on filepicker. | Browse opens up.
  | Select xls file & click open. | xls file is opened.
  | Open inspector. | Inspector is opened.
  | Click on component & then file picker & parsed data. | Parsed data is displayed correctly.


</body>
</html>

**Review by arpitnath — CHANGES_REQUESTED** [review]
We should have the option to select `Microsoft Excel` as a file type along with **CSV and auto detect**
cc: @sherfin94 
Screenshot 2022-07-28 at 1 46 41 PM

**Comment by shubh22** [comment]
Task linked: [CU-2mtjqzz Filepicker: [improvement]](https://app.clickup.com/t/2mtjqzz)

**Comment by sherfin94** [comment]
Hey @manishkushare , I have fixed the package lock issue, could you check if the feature is still working?

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Please change the format of `parsedData` as discussed.

**Comment by manishkushare** [comment]
@sherfin94 , updated the PR with requested changes. I don't have access to resolve the merge conflicts.

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @arpitnath , functionality of this PR works, however, there seems to be many package.json and package-lock.json changes that are unnecessary, could you take over this PR and make sure that only those package changes related to the new xlsx package are involved?


https://user-images.githubusercontent.com/20333972/186126521-0c31468e-8080-4956-a84a-56d366cd6817.mov

cc: @shubh22

**Comment by arpitnath** [comment]
Refer: #3842

**Comment by shubh22** [comment]
Task linked: [CU-2k0aqfh File Picker Updates: Improvements and Bugfixes](https://app.clickup.com/t/2k0aqfh)

**Pull request closed without merging**
