### PR TITLE
refactor: remove @babel/plugin-proposal-class-properties

### PR DESCRIPTION
**Pull request by erfan93na**
fixes: #3939

### CODE REVIEW

**Comment by gondar00** [comment]
Hey @erfan93na, could you remove it from `frontend/babel.config.js` under plugins key and also commit the package-lock.json please? 

note: npm version needs to be `7.20.0`

```js
npm i -g npm@7.20.0
```

**Comment by erfan93na** [comment]
Hey @gondar00,

I did the following:

1. Removed class properties plugin from babel.config.js
2. Had to update "@babel/preset-env" to "^7.18.10", (Webpack had a syntax error before I did so)
3. Ran `npm i` on frontend and server directories, also ran `npm build` on plugins, so their `package-lock.json` are updated.

Currently webpack compiles successfully after `npm start` on frontend.

**Comment by gondar00** [comment]
@erfan93na some issue with your latest commit the cla license is showing pending can you once please check?

**Comment by erfan93na** [comment]
> 

Unfortunately I made the 2nd commit with another git name and email (incorrect too), 
Currently I am not able to sign CLA for that commit
Should I create another branch, cherry-pick the useful commits and create a new pull request?

**Comment by gondar00** [comment]
Yep you can create a new branch and cherry pick the commit @erfan93na

**Comment by gondar00** [comment]
Closed as resolved in #3959

**Pull request closed without merging**
