### PR TITLE
fix: 4966 edit comments

### PR DESCRIPTION
**Pull request by mikebarr24**
#4966 
This is my first larger PR. Always happy to take feedback as I'm sure this PR will need it 😀.

### CODE REVIEW

**Comment by gondar00** [comment]
Hey @mikebarr24, the fix for this issue is basically in [this](https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/_ui/Mentions/index.js#L9) file, if we change the useEffect to 

```
  React.useEffect(() => {
    setMentionsInputValue(value);
  }, [value]);
```

We are able to see the comment inside the input, we don't have to make any other changes except the on in `Mentions` component

**Comment by mikebarr24** [comment]
@gondar00 Happy to make that update. However, I've copied in some direction I got from the Slack group. 

> Shubhendra
>   [5 days ago]
> Hey 
> [@Michael Barr](https://tooljet.slack.com/team/U0419594BNG)
>  - Thanks for sharing this.
> I checked it and yes its working but it is not clear.
> Ideally user should be able to edit the comment directly once edit option is clicked,
> rather than going to the main comment input box and then enter the new comment that will replace the old comment.

I think I have understood this to mean edit the comment directly. 

Shall I update to your solution?

**Comment by gondar00** [comment]
Oh, Sorry about that 🙇🏻 

Yes, please can you update the solution I have proposed

**Comment by mikebarr24** [comment]
> 
😂 No problem. I enjoyed exploring this anyway. I learnt a lot! 
Hope this is OK.

**Comment by gondar00** [comment]
Thank you @mikebarr24 I'm glad you enjoyed exploring Tooljet. Please feel free to pick any [open](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs) community issues that you find interesting, Thank you for your contribution 🏅

**Review by gondar00 — APPROVED** [review]

**Pull request merged**
