### PR TITLE
adds `On change` event in color picker component

### LINKED ISSUE #4174: Add On change event in Color Picker Component
### Is your proposal related to a problem?

Currently, there are no event handlers for the Color Picker component. We should have an event `on change` whenever the value in the component is changed.

### Describe the solution you'd like

The Color Picker configuration pane should have an "Events" section, just like other components.

Refer to this PR: https://github.com/ToolJet/ToolJet/pull/4058

### PR DESCRIPTION
**Pull request by appledora**
* Issue - #4174 
* Why - Currently, there are no event handlers for the Color Picker component. We should have an event on change whenever the value in the component is changed.
* Changes - Following the guidelines from #4058 , updated the `frontend/src/Editor/WidgetManager/widgetConfig.js` and `frontend/src/Editor/Components/ColorPicker.jsx` files. 

Happy to improve upon feedbacks :smiley_cat: 

fixes #4174

### CODE REVIEW

**Comment by appledora** [comment]
@withshubh @arpitnath  would appreciate your feedbacks here!

**Comment by appledora** [comment]
@arpitnath @withshubh any updates on this?

**Comment by withshubh** [comment]
> @arpitnath @withshubh any updates on this?

Hey @appledora 👋 
Thanks for creating the PR.
We will review the PR as soon as possible. :D

**Review by arpitnath — COMMENTED** [review]
This is firing the `onChange` event three times, whenever a new color is picked.
Ideally, the event should be fired only once when a new color is picked or when the color is changed/updated.

**Review by arpitnath — CHANGES_REQUESTED** [review]
My suggestion will be, we should consider firing the `onChange` event whenever the state variable **color** is changed/updated.

**Review by appledora — COMMENTED** [review]
Reviewed change requests

**Review by arpitnath — DISMISSED** [review]
https://user-images.githubusercontent.com/67645175/197884824-cd209ef1-a256-4c81-9d28-70eda2f2de63.mov

If the event is attached to the widget, on page load the event is triggered.

**Comment by arpitnath** [comment]
@appledora Also, can we fire the event as a side effect on the component's state getting an update rather than repeatedly calling the same **fireEvent** function?

**Review by kavinvenkatachalam — APPROVED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@manishkushare Can you take a pull from the latest develop?

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @appledora   
Thanks for contributing to ToolJet. :raised_hands: 
While this PR is under review, you can submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Comment by Nandinisaha13** [comment]
Hey @appledora I can see while I change the default color form the properties then also the event gets fired. This should not be happening. attaching the screencast for the same.

**Comment by appledora** [comment]
Hi, @Nandinisaha13 yes, I have also observed this. However,  thanks for pointing out. I will get back to working on it by next week, hopefully :D

**Review by kavinvenkatachalam — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @appledora - Please submit the form before the end of this week to claim your Hacktoberfest swag: [airtable.com/shr1qR6xhqsWO7LD7](https://airtable.com/shr1qR6xhqsWO7LD7)

**Comment by appledora** [comment]
@withshubh apologies for the delay, fall semester got my whole schedule messed up :'( Completed the form!

**Comment by withshubh** [comment]
> @withshubh apologies for the delay, fall semester got my whole schedule messed up :'( Completed the form!

No worries, thanks for submitting it.

**Pull request merged**
