### PR TITLE
Feature :: table component specific action 

### PR DESCRIPTION
**Pull request by stepinfwd**
- [x]  selectRowByIndex
    - [x]  selectRowByKeyAndValue

    part of #3601

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2k0aq4y Feature :: table component specific action - selectRow](https://app.clickup.com/t/2k0aq4y)

**Comment by shubh22** [comment]
Task linked: [CU-2juetrv Component Specific actions : Table](https://app.clickup.com/t/2juetrv)

**Comment by sherfin94** [comment]
Temporarily pausing as there seems to be several issues that need to be tackled for Table.

**Comment by sherfin94** [comment]
Closing as Table will be refactored soon.

**Pull request closed without merging**
