### PR TITLE
Issue # 6404

### PR DESCRIPTION
**Pull request by thefloofe22**
Fixed the documentation bug, as noted in the issues description for issue # 6404

### CODE REVIEW

**Comment by tejakummarikuntla** [comment]
Fixes #6404 

@thefloofe22 , could you please sign the CLA to progress the PR?

**Comment by thefloofe22** [comment]
I signed the CLA, but I am a bit confused. It says my status is still "not signed yet". Does someone have to approve it?

**Comment by thefloofe22** [comment]
Signed the CLA

**Review by withshubh — APPROVED** [review]

**Comment by withshubh** [comment]
After careful consideration, we have reached a decision to consolidate all the issues that necessitate changes in each version into a single merged issue. This resolution has been implemented with the aim of minimizing the inconvenience associated with creating separate issues or pull requests for identical bugs, as an affect this issues needs to be closed.

We appreciate everyone's efforts in identifying these issues and submitting them for consideration. We hope you understand and are sorry for the inconvenience caused, would encourage you to explore other `good first issues` and `up for grabs`.

**Pull request closed without merging**
