### PR TITLE
Added Json description feature

### LINKED ISSUE #1731: Generate Chart from json description
### Is your proposal related to a problem?

Currently, we can't generate a chart from the JSON description.
### Describe the solution you'd like

Add a field for generating charts from JSON data
### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by shah21**
Resolves #1731

### CODE REVIEW

**Comment by sherfin94** [comment]
@shah21 Plotly provides this online editor for visualising several of its example jsons: http://plotly-json-editor.getforge.io/

One such example being: https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/11.json

Simple example jsons provided in the plotly website are working, but these kind of advanced jsons are not working. Can you figure out what's going?

**Comment by sherfin94** [comment]
Also, presently the data field and json field are shown regardless of whether the user is plotting from data or json, could you make it so, that the data and chart type fields are displayed only if the toggled is turned off(default), and json field is displayed only if the toggle is turned on?

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Posted my change requests as comment ☝🏼

**Comment by shah21** [comment]
> @shah21 Plotly provides this online editor for visualising several of its example jsons: http://plotly-json-editor.getforge.io/
> 
> One such example being: https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/11.json
> 
> Simple example jsons provided in the plotly website are working, but these kind of advanced jsons are not working. Can you figure out what's going?

`https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/11.json`

the JSON object that got from the above ⬆️  URL is working perfectly in my local project. So what actually is the problem, can you elaborate? 

Screenshot 2022-01-06 at 4 58 32 PM

**Comment by sherfin94** [comment]
> > @shah21 Plotly provides this online editor for visualising several of its example jsons: http://plotly-json-editor.getforge.io/
> > One such example being: https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/11.json
> > Simple example jsons provided in the plotly website are working, but these kind of advanced jsons are not working. Can you figure out what's going?
> 
> `https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/11.json`
> 
> the JSON object that got from the above ⬆️ URL is working perfectly in my local project. So what actually is the problem, can you elaborate?
> 
> Screenshot 2022-01-06 at 4 58 32 PM

Check this one: 
https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/2dhistogram_contour_subplots.json

Its not showing the exact countour graph that's being displayed on their online visualizer.

**Comment by sherfin94** [comment]
Few small changes on the inspector @shah21 , 

1. Change the title of the section to from `Plot from JSON` to `Plotly JSON chart schema`
2. Change the label of the field inside the section from `Plot from JSON` to `Use Plotly JSON schema`
3.  Put this section below the `title` section

**Comment by sherfin94** [comment]
@shah21 One last change, the 'marker color' field is unnecessarily shown even if plotly is selected. Could you hide that if plotly is selected?

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
