### PR TITLE
Refactor table component

### LINKED ISSUE #3932: [refactor]: Table widget
### What area of the codebase is to be refactored?

Table widget

### What are the potential advantages of this proposed refactoring?

Table codebase is very difficult to traverse, applying more refactoring will allow newer developers to make changes to it, and also will make it easier to implement automatic column configuration. This will also take us forward towards completely loading table from the new API for properties and styles.

### PR DESCRIPTION
**Pull request by sherfin94**
Resolves #3932

## Refactoring achieved:

* Introduced centralised store to manage data of the table using useReducer hook
* All properties and styles are now being loaded using a single function, in a separate file
* Minimised the usage of directly accessing component.definition to access properties and styles
* Minimised the usage of currentState, and instead kept data in the centralized data store
* Moved all column type definitions of the table to a separate file
* Moved Filter related code to a separate file
* Moved custom filter configuration for react table to a separate file
* Moved IndeterminateCheckbox used for bulk selection to a different file
* exposeToCodeHinter and variablesExposedForPreview are now available for every component to use

## Explanation for migration:

There is one migration included, the value of `columnSizes` property did not follow the format
of other properties (`{ value: ...}`), the migration changes it to that format, so that, we can
use the new api to load it, instead of directly accessing `component.definition.properties..`

### CODE REVIEW

**Comment by sherfin94** [comment]
Found one issue myself: Bulk update buttons are not being displayed.

**Comment by Nandinisaha13** [comment]
Not able to download the filtered result. 
[table_filter.webm](https://user-images.githubusercontent.com/41302917/188412080-b19b9f72-906a-4326-9463-edd404f9fa36.webm)

**Comment by sherfin94** [comment]
Compact and Spacious cell sizing doesn't work

**Comment by Nandinisaha13** [comment]
Can't download searched results.

**Comment by Nandinisaha13** [comment]
Undefined selected row & selected row ID.
[table_selectedrow.webm](https://user-images.githubusercontent.com/41302917/188566015-0ed2b311-6bf6-4cde-9bea-9721b60d11e2.webm)

**Comment by Nandinisaha13** [comment]
Instead of crashing the widget, the debugger should throw an error.
[table_wrong.webm](https://user-images.githubusercontent.com/41302917/188568394-381988f2-6e71-4f8f-a11b-79132f99d7af.webm)

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@sherfin94 Here are the few things I noticed which didn't work (some of them are in production as well)

1. Highlighting the selected row only works for the first selected row 
2. Border radius, visibility, disable not working
3. On the viewer mode, I tried adding the filter but was not able to scroll the select
4. On the UI when we drop the table and without resizing it, the filters select seem to be overlapping

**Comment by Nandinisaha13** [comment]
Multiple toast if table name is empty
[multipletoast_refactor.webm](https://user-images.githubusercontent.com/41302917/189909782-961bbb43-6f00-4c2e-944b-c8a94d6dcf6e.webm)

**Comment by Nandinisaha13** [comment]
Save changes or discard changes button doesn't appear even after the field is edited.
[Uploading Table_savechangesno.webm…]()

**Review by kavinvenkatachalam — DISMISSED** [review]
LGTM

**Pull request merged**
