### PR TITLE
[localization] Translate Profile Settings Page in Spanish #4186

### LINKED ISSUE #4186: [localization] Translate Profile Settings Page in Spanish
### Is your proposal related to a problem?

Add translations for the Profile Settings Page in Spanish

### Describe the solution you'd like

The strings need to be translated:

Screenshot 2022-09-30 at 3 41 54 PM

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

### PR DESCRIPTION
**Pull request by Ambareen09**
fixes #4186

### CODE REVIEW

**Comment by Ambareen09** [comment]
I have made a PR, kindly add a hacktoberfest-accepted label if this PR is acceptable.

**Comment by withshubh** [comment]
> I have made a PR, kindly add a hacktoberfest-accepted label if this PR is acceptable.

Sure! We will review the PR soon and will add the relevant tags.

**Comment by withshubh** [comment]
@Ambareen09 Please resolve the merge conflict.

**Comment by Ambareen09** [comment]
I resolved them and committed, Is it fine now?

**Review by withshubh — DISMISSED** [review]

**Comment by Navaneeth-pk** [comment]
@Ambareen09 please resolve the merge conflicts.

**Comment by Ambareen09** [comment]
@Navaneeth-pk Please look now, I have again resolved my conflicts.

**Comment by Navaneeth-pk** [comment]
@Ambareen09 I think conflicts were not resolved properly. Currently the PR doesn't have any changes.

**Review by withshubh — APPROVED** [review]

**Comment by withshubh** [comment]
LGTM
Thanks for your help @taicoding 🙌

**Comment by withshubh** [comment]
Hey @Ambareen09  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
