### PR TITLE
[docs]: Update data-sources guides - SMTP, Snowflake, Stripe

### PR DESCRIPTION
**Pull request by RudraPratik30**
Update the following docs in the data source library:
- SMTP
- Snowflake
- Stripe

### CODE REVIEW

**Review by karan-rathod-316 — COMMENTED** [review]
Please fix the below changes and confirm:

For Stripe, the table for queries is not accessible. Use some other formatting or fix the column widths. 

For the tip section in Snowflake, the content can be phrased better:
"Query results can be transformed using transformations. Read our [transformations](link) documentation to learn more."

**Comment by RudraPratik30** [comment]
Updated both the changes @karan-rathod-316

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Review by johnsoncherian — APPROVED** [review]

**Pull request merged**
