### PR TITLE
migrated webpack v4 to v5

### LINKED ISSUE #773: Upgrade webpack to v5 from v4
Current webpack version: `4.29.6`
Latest version: `5.53.0`

Migration guide: https://webpack.js.org/migrate/5/

Key improvements: 
https://webpack.js.org/blog/2020-10-10-webpack-5-release/
```
Improve build performance with Persistent Caching.
Improve Long Term Caching with better algorithms and defaults.
Improve bundle size with better Tree Shaking and Code Generation.
Improve compatibility with the web platform.
Clean up internal structures that were left in a weird state while implementing features in v4 without introducing any breaking changes.
Prepare for future features by introducing breaking changes now, allowing us to stay on v5 for as long as possible.
```

### PR DESCRIPTION
**Pull request by febinsathar**
migrated webpack v4 to v5

fixes #773

### CODE REVIEW

**Comment by gondar00** [comment]
@febinsathar You're on npm version 6, can you please upgrade your npm version by running `npm i -g npm` and do `npm i` again

**Comment by febinct** [comment]
updated

**Review by gondar00 — APPROVED** [review]
Later, will have to use https://webpack.js.org/guides/asset-modules/ as `file-loader` is getting depreciated, but that can be part of other PR

**Comment by arpitnath** [comment]
@febinsathar 
Thanks for contributing to ToolJet again. Would you mind filling up our Hacktoberfest form to confirm your swags? 
https://app.tooljet.io/applications/hacktoberfest-2021-form

**Pull request merged**
