### PR TITLE
[ Bug fixed ] : [ Table ] When column name is changes, particular column data becomes empty when downloaded

### LINKED ISSUE #5478: [ Bug ] : [ Table ] when column name is changed, particular column data appears empty upon downloading
### Version Information
v2.1.0

### Environment
Development

### What is the expected behaviour?
When we change the column name in the Table widget and download the table data, it should display the respective data.

### What is the current behaviour?
When we change the column name and try to download the table data, a column whose name was changed is not showing any data for that particular column, it simply displays an empty column.

### How to reproduce the issue?

1. Create a new application 
2. Drag a table widget from the right sidebar on the canvas.
3. A table with the default data will be appearing on the canvas
4. Click anywhere on the table widget or the label of the table widget on the canvas to open the widget inspector for the table at the right sidebar.
5. In the widget inspector, look for the columns sections in the properties tab. It will show 3 cards displaying the names of the columns in the table widget.
6. For our simplicity, let's focus on the `name` column, click on the name card, and it will open the pop-up window to the left of the card, which will show all the column details. In that, look for the column name field and change its value to `first_name` from `name`. If the column becomes, empty in the table widget itself, again look for the key field, and provide the appropriate value according to the data provided.
7. Now, in the table widget, look for the download option, available in the header of the table widget, click on it, and a pop-up window will appear to select the type in which we wish to download the data, select any, table data will start downloading.
8. Once, downloaded, open the file, and you can observe, the first_name column will be empty.
9. That's our task we n

### Screenshots or Screencast
[Tooljet - Dashboard - 6 February 2023 - Watch Video](https://www.loom.com/share/0497b0412d514028a56a5ba2caf34a03)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by manishkushare**
Resolves #5478

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-85zrm99vu [ Bug ] : [ Table ] when column name is changed, particular column data appears empty upon downloading](https://app.clickup.com/t/85zrm99vu)

**Review by sherfin94 — CHANGES_REQUESTED** [review]
@manishkushare , now the table doesn't seem to be able to generate CSV at all.

I am getting a blank CSV with headers when I generate from the following app
[tableissue-export-1675675828170.json.zip](https://github.com/ToolJet/ToolJet/files/10661614/tableissue-export-1675675828170.json.zip)

Please check

**Comment by manishkushare** [comment]
> @manishkushare , now the table doesn't seem to be able to generate CSV at all.
> 
> I am getting a blank CSV with headers when I generate from the following app [tableissue-export-1675675828170.json.zip](https://github.com/ToolJet/ToolJet/files/10661614/tableissue-export-1675675828170.json.zip)
> 
> Please check

@sherfin94 Made the changes to resolve the bug

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @manishkushare , looks like the original bug is now back. Please check

image

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
