### PR TITLE
Update date picker widget to use toggles for date and time selection properties

### LINKED ISSUE #3576: Add toggle button to enable widget properties
### What is the expected behaviour?

Add buttons for “Enable time selection” & “Enable date selection”, so that users can easily toggle true and false values.

### What is the current behaviour?

Toggle button missing in “Enable time selection” & “Enable date selection”  properties.

### How to reproduce the issue?

1. Go to this [link](https://app.tooljet.com/)
2. Now click on "create new application" 
3. Now drag and drop the date-picker widget from the widgets inventory
4. Inspect the widget and scroll down to its properties panel on the right
5. Now under sections “Enable time selection” & “Enable date selection” we have to add toggle buttons 

### Screenshots or Screencast

Screenshot 2022-07-11 at 4 12 57 PM

### Any possible solutions?

Refer to other widgets by inspecting them to learn about the UI.

### PR DESCRIPTION
**Pull request by Nathan-Bisson**
Closes #3576

### CODE REVIEW

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Review by arpitnath — APPROVED** [review]

**Comment by sherfin94** [comment]
Hey @Nathan-Bisson , the code works, however, we'll need to apply a migration along with your changes, so that, users who has programmatically configured the two properties for their existing date-pickers, will have their `Fx` buttons activated and their code displayed, instead of showing a toggle. This can be a bit tedious for you, so we'll assign an internal developer to write the migration and then merge it.

**Comment by shivangT** [comment]
Hello @sherfin94 
Please take a look into this& assign this to someone.
Thanks

**Comment by arpitnath** [comment]
Closing this PR, as the issue has been assigned to someone else.
cc: @shubh22

**Pull request closed without merging**
