### PR TITLE
[localization] Translate Component Manager in Spanish

### PR DESCRIPTION
**Pull request by LPRegen**
Spanish translations for `widgetManager` has been added.

This PR resolves [issue #4184](https://github.com/ToolJet/ToolJet/issues/4184)

### CODE REVIEW

**Review by Navaneeth-pk — DISMISSED** [review]

**Comment by Navaneeth-pk** [comment]
@LPRegen please resolve the merge conflicts.

**Comment by LPRegen** [comment]
> @LPRegen please resolve the merge conflicts.

It's done.

**Review by withshubh — APPROVED** [review]

**Comment by withshubh** [comment]
Hey @LPRegen  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Comment by LPRegen** [comment]
Hi @withshubh 
I completed the form and thanks for it!

**Pull request merged**
