### PR TITLE
[ Feature] :: Option to disable action buttons :: Table widget

### LINKED ISSUE #2987: script to disable Action-button in Table
### Is your proposal related to a problem?

There is no option for disabling the Action button in the table.

### Describe the solution you'd like

Add a Disable option for programmatically disabling the button.

### LINKED ISSUE #4340: Option to disable action buttons :: Table widget
### Is your proposal related to a problem?
Currently no option to disable action button in table.

### Describe the solution you'd like
Add an option to toggle enable/disable in table widget

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #4340 
closes #2987

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2w9z66j Option to disable action buttons :: Table widget](https://app.clickup.com/t/2w9z66j)

**Review by kavinvenkatachalam — DISMISSED** [review]
LGTM

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @stepinfwd, it looks like there has been a miscommunication of the feature spec.

What we needed was a disable button per action button, inside the popover for the action button, where we can also use `cellValue` , `rowData` etc.

Please hold this feature for now, and get the recomputed priorities from @shubh22

**Comment by stepinfwd** [comment]
Closing this one , opened here  https://github.com/ToolJet/ToolJet/pull/4528

**Pull request closed without merging**
