### PR TITLE
[HF23-AB] Update widgetConfig.js

### PR DESCRIPTION
**Pull request by Dv04**
Changed the file according to #7736

I have changed most of the occurrences to have sentence cases.

If you don't mind, I also put that in some places that may have not been covered by the issue. If those are to be reverted back, I will gladly do so.

### CODE REVIEW

**Review by tejakummarikuntla — CHANGES_REQUESTED** [review]
Hey @Dv04 , I'd request you to revisit the issue description #7736 and revert the changes that are not mentioned. Please keep the changes only that are asked in the issue description to progress it for reviews and merging.

Additionally, the changes are needed in two files. I was able to find only one file with the changes. Please take a look.

**Comment by Dv04** [comment]
Hey @tejakummarikuntla, As mentioned in the issue #7736, 

> Changes are only required in the widgetConfig.js file, locate the object which has the related component name in the name key, and make changes only in that particular object.

And that is why I had only changed one file. if you would direct me to the next one I will change it as well. 

And I will revert the extra changes sure. Sorry for misunderstanding that part.

**Comment by Dv04** [comment]
@tejakummarikuntla The change is done. Please have a look when available.

**Review by Dv04 — COMMENTED** [review]
Reopen

**Comment by Dv04** [comment]
Hey @tejakummarikuntla, sorry for closing the previous pull request, that was a hacksquad requirement. But I have done all and only the necessary changes in this https://github.com/ToolJet/ToolJet/pull/7944. Please have a look at it.

**Pull request closed without merging**
