### PR TITLE
[docs]: Fix Style table in PDF Component

### LINKED ISSUE #11703: [docs]: Update the Styles table in PDF Component
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/pdf#styles

- Update the columns of Style table to "Property", "Description" and "Configuration Options"
- Update the content as given in  - [Reference](https://docs.tooljet.com/docs/widgets/text-input/#additional-actions) (check the visibility row in Additional Actions table)

In current docs:

Screenshot 2024-12-24 at 12 47 28 PM

Reference doc:
Screenshot 2024-12-24 at 12 48 01 PM

The changes are to be implemented in three files -
Next - ToolJet/docs/docs/widgets/pdf.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/pdf.md
Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/pdf.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by Ayushraj1605**
### **What kind of change does this PR introduce?**  
Documentation Update  

---

### **Issue Number:**  
Fixes #11703

---

### **Did you add tests for your changes?**  
Not required.  

---

### **Snapshots/Videos:**  
None.  

---

### **If relevant, did you update the documentation?**  
Yes, updated the documentation as part of this PR.  

---

### **Summary**  
- Updated the columns of the style table in the PDF widget documentation to "Property," "Description," and "Configuration Options."  
- Revised the content based on the provided reference, particularly updating the visibility row in the Additional Actions table.  
- Changes implemented in the following files:  
  - `Next - ToolJet/docs/docs/widgets/pdf.md`  
  - `Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/pdf.md`  
  - `Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/pdf.md`  

---

### **Does this PR introduce a breaking change?**  
No  

---

### **Other information**  
None  

---

### **Have you read the [contribution code of conduct](https://github.com/ToolJet/ToolJet/blob/7d09abf5161e90583f5fba87f82a04ae50c8e3ac/CODE_OF_CONDUCT.md)?**  
Yes

### CODE REVIEW

**Review by RudraPratik30 — CHANGES_REQUESTED** [review]
Hey @Ayushraj1605, thanks for contributing!

As mentioned in the [issue](https://github.com/ToolJet/ToolJet/issues/11703), you also need to update the table content, please do the needful.

If you need any assistance, feel free to drop a message in the contributors' channel on our [Slack](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA).

Thanks again, and happy coding!

**Comment by RudraPratik30** [comment]
Hey @Ayushraj1605, any updates?

**Comment by Ayushraj1605** [comment]
hey @RudraPratik30  ya i will be creating a PR by today

**Comment by RudraPratik30** [comment]
Hey, thanks for the update!
You can push changes to this PR instead of creating a new one.

**Comment by Ayushraj1605** [comment]
hey @RudraPratik30  i have pushed the updates.

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Review by adishM98 — APPROVED** [review]

**Pull request merged**
