### PR TITLE
[docs]: Update Device Table in Table Component

### LINKED ISSUE #11717: [docs]:Update the Devices table for the Table Component
### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/widgets/table/table-properties/#devices

Please check the [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices) for the Device Table.
- Update the column name from "Options" to "Property"
- Update the content of the table as per the given [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices).

Table in current docs:
Screenshot 2024-12-27 at 12 16 13 PM

Table in reference:
image

The changes are to be implemented in three files -
Next - ToolJet/docs/docs/widgets/table/properties.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/table/properties.md
Version 3.0.0 (LTS) - ToolJet/docs/versioned_docs/version-3.0.0-LTS/widgets/table/properties.md

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

### PR DESCRIPTION
**Pull request by Anuj012004**
Description:
I've updated the Devices table documentation in three files:

docs/docs/widgets/table/properties.md
docs/versioned_docs/version-2.50.0-LTS/widgets/table/properties.md
docs/versioned_docs/version-3.0.0-LTS/widgets/table/properties.md

Changes made:

Updated column name from "Options" to "Property".
Ensured consistent table content across all specified files.
Maintained document formatting standards.

Fixes #11717

### CODE REVIEW

**Comment by Anuj012004** [comment]
@PriteshKiri  Could you please review this documentation update?

 Thank you!

**Review by RudraPratik30 — CHANGES_REQUESTED** [review]
Hey @Anuj012004, thanks for contributing to ToolJet!

Please make the following mentioned changes. 

If you need any assistance, feel free to drop a message in the contributors' channel on our [Slack](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA).

Thanks again, and happy coding!

**Comment by Anuj012004** [comment]
Hi @RudraPratik30 Could you please tell me do I need to change all three files?

**Comment by RudraPratik30** [comment]
Hey, Yes you need to update the changes in all the three files.

**Comment by Anuj012004** [comment]
Hi @RudraPratik30,

Updated changes:

Removed bold from device visibility options.
Made "fx" bold, removed backticks.

**Review by RudraPratik30 — APPROVED** [review]
Hey @Anuj012004, thanks for contributing to ToolJet!
The changes look good to me and forwarding it to the team for final review.
Your PR will be merged soon, thanks again!

**Review by karan-rathod-316 — APPROVED** [review]
Looks good to me.

**Pull request merged**
