### PR TITLE
Enhance GraphQL plugin to be able to send custom headers

### LINKED ISSUE #4768: Need the ability to reuse query results in source headers and/or send custom headers on graphQL queries
### Is your proposal related to a problem?

Yes, it's currently not possible to send customer headers to a graphQL source, based on data in the app. Which is critical if you are to use api's which are authenticated per user / something they entered, vs per app at the env. var level.

### Describe the solution you'd like

1. Ability to use app data in source headers (strong preference for this)
2. Ability to send custom headers in graphQL queries (this is a weak work around).

### Describe alternatives you've considered

(Write your answer here.)

### If the feature is approved, would you be willing to submit a PR?

Willing to review it, but not (at the moment) invest the time. Still evaluating solutions.

### PR DESCRIPTION
**Pull request by yuku**
Closes #4768 

* Allow using `react-component-headers` as a QueryEditor.
  Previously, `react-component-header` was only available as a SourceEditor. In this PR, it can now be used as a QueryEditor.
  In addition, if it is rendered as a QueryEditor, it internally uses the `<CodeHinter>` component so that users can use dynamic headers.
* Make the GraphQL plugin use the `react-component-headers` query.
* Tweak description of the manifest of GraphQL plugin.

## Quality Assurance
* Confirm GraphQL query editor has `headers` form

    https://user-images.githubusercontent.com/96157/210196434-03012d76-ff87-4562-ba83-dbafc7cb4265.mov

* The added unit test passes

### CODE REVIEW

**Comment by yuku** [comment]
@withshubh Could you review this PR? Thanks!

**Review by gondar00 — APPROVED** [review]
Looks good 🥇

**Comment by gondar00** [comment]
@yuku could you please fix the [lint](https://github.com/ToolJet/ToolJet/actions/runs/3890247413/jobs/6639202557) errors

**Comment by yuku** [comment]
@gondar00 Done!

**Review by gondar00 — APPROVED** [review]

**Review by gondar00 — APPROVED** [review]

**Pull request merged**
