### PR TITLE
Fixed version name sanitization on editing versions

### LINKED ISSUE #4486: User input isn't sanitized on server while editing server names. Sanitization is done only for create versions
### What is the expected behaviour?
User input should be sanitized while editing version names as it is done currently while creating versions

### What is the current behaviour?
Currently user input is not sanitized while editing version name

### How to reproduce the issue?

1. Edit any application
2. Go to versions dropdown & click on edit icon for editing the name
3. Now add any special character like '<' or '>' and save
4. The input is not sanitized on server & same value is returned from API on get call for versions

### Screenshots or Screencast
Version PUT API Payload
VersionPutPayload

Version GET API response
VersionGetResponse

### Any possible solutions?
Possible solution is to sanitize the user input on backend as it is done for create version scenario

### If the bug is confirmed, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by surajrane42**
Resolves #4486

### CODE REVIEW

**Comment by gsmithun4** [comment]
deployed https://tj-4570.herokuapp.com/

**Comment by gsmithun4** [comment]
@surajrane42 Please fix the lint errors and test cases

**Comment by surajrane42** [comment]
@gsmithun4 @arpitnath I have tried fixing the e2e tests. Can you please check now

**Comment by gsmithun4** [comment]
@surajrane42 Please rebase https://github.com/surajrane42/ToolJet/pull/1

**Comment by surajrane42** [comment]
@gsmithun4 Rebased the branch. Please check

**Comment by gsmithun4** [comment]
@surajrane42 There is a testcases failing, please fix

**Comment by surajrane42** [comment]
@gsmithun4 Sure I will have a look at it & fix it soon

**Comment by withshubh** [comment]
Hey @surajrane42   
Thanks for contributing to ToolJet. :raised_hands: 
While this PR is under review, you can submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Comment by withshubh** [comment]
Hey @surajrane42 - Please make the changes suggested by @gsmithun4 so that we can review and merge the PR.

**Review by gsmithun4 — APPROVED** [review]

**Pull request merged**
