### PR TITLE
Fix for broken pin icon of popovers in dark mode

### LINKED ISSUE #791: Pin icon on inspector and Error coming white in dark mode and is not readable.
Pin icon on 'Inspector' and 'Error' tabs coming white in dark mode and is not readable(As shown in SS below). Should be black.

Screenshot 2021-09-20 at 11 07 19 AM
Screenshot 2021-09-20 at 11 11 07 AM

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
Fixes #791 
Issue: 
Screenshot 2021-09-21 at 1 20 44 PM

In this update, if the pin is in inactive state it will show like,
Screenshot 2021-09-21 at 3 20 05 PM

If the pin button is in active state: 
Screenshot 2021-09-21 at 1 16 18 PM

### CODE REVIEW

**Comment by akhilgkrishnan** [comment]
@Navaneeth-pk please review

**Comment by Navaneeth-pk** [comment]
@akhilgkrishnan shouldn't the button also be dark like the other buttons?

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan shouldn't the button also be dark like the other buttons?

This happens if they are trying to click on the pin. 
Screenshot 2021-09-21 at 1 16 18 PM

**Comment by Navaneeth-pk** [comment]
@akhilgkrishnan the screenshot in the PR description is of the issue and not the fix?

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan the screenshot in the PR description is of the issue and not the fix?

It is the fix. previously it was like this
Screenshot 2021-09-21 at 1 20 44 PM

**Comment by Navaneeth-pk** [comment]
@akhilgkrishnan sorry was confused. 

image
Can you please check the buttons above? they are dark even before they are clicked/selected on dark mode. It should be the case for the `pin` button too, right?

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan sorry was confused.
> 
> image
> Can you please check the buttons above? they are dark even before they are clicked/selected on dark mode. It should be the case for the `pin` button too, right?

Sure. Between can you please check the show query button.

**Comment by Navaneeth-pk** [comment]
@akhilgkrishnan that also needs to be fixed but it is out of scope for this issue. Someone is fixing it along with a PR for fixing sidebar icons.

**Comment by akhilgkrishnan** [comment]
Thanks @Navaneeth-pk, I will update

**Pull request merged**
