### PR TITLE
multiselect labels fixed

### LINKED ISSUE #1096: Bugfix: fix Multiselect widget's values, display values and default value
Screenshot 2021-10-15 at 7 48 02 PM

### Current behaviour
app crashes when label values : `{{}}`

### Fix
[ ] option labels
[ ] option values
[ ] add default values

### PR DESCRIPTION
**Pull request by arpitnath**
Fixes #1096 

Loom : https://www.loom.com/share/308add618f84458bb05e571792b81eea

### CODE REVIEW

**Comment by arpitnath** [comment]
app: https://tooljetapp-pr.herokuapp.com/apps/71160e52-35ad-4009-a7ac-e95f6e4ea89a

**Comment by sherfin94** [comment]
@arpitnath Since we've made multiple changes in `properties` of this widget, we'll need a migration to backfill values for existing cloud and community users who have used multiselect in any of their apps.

**Comment by arpitnath** [comment]
app: https://tooljet-pr-app.herokuapp.com/apps/2d7ccad6-96a3-4576-9376-349eff1c9f4b

**Comment by sherfin94** [comment]
Looks like the app crashes if the default value is an array. Given that this is a multi-select, the default value should always be an array, don't you feel
multiselect-default-array

**Comment by arpitnath** [comment]
> Looks like the app crashes if the default value is an array. Given that this is a multi-select, the default value should always be an array, don't you feel multiselect-default-array

Yes, and I thought it will be good to fix it in a different PR

**Review by sherfin94 — DISMISSED** [review]

**Comment by sherfin94** [comment]
> > Looks like the app crashes if the default value is an array. Given that this is a multi-select, the default value should always be an array, don't you feel multiselect-default-array
> 
> Yes, and I thought it will be good to fix it in a different PR

This issue is only present in this PR. I tried in develop and there doesn't seem to be an issue.

**Comment by arpitnath** [comment]
https://user-images.githubusercontent.com/67645175/142957233-ac0fe52c-5cb2-45e4-a0ea-aa5b810df9ea.mov

**Comment by arpitnath** [comment]
updated app: https://tooljet-pr-app.herokuapp.com/

**Pull request closed without merging**
