### PR TITLE
feat: made obserable text for password

### PR DESCRIPTION
**Pull request by jaymehta002**
### Changes Made:

1. **Error Message Styling**:
   - Error messages indicating password requirements were styled differently based on their nature. The color red was used for error messages, while the color grey was used for non-error messages.

2. **Button Disable Condition**:
   - The condition for disabling the reset password button was updated to include checks for password requirements such as minimum length, presence of numbers, symbols, and uppercase letters.

### Description:

These changes improve the user experience by providing clearer visual feedback on password requirements and ensuring that the reset password button is disabled until all requirements are met.

### Code Changes
Created warning texts based on length, character inclusion, uppercase and numbers
```
<span style={{ color: this.checkPasswordLength(password) ? 'red' : 'grey' }}>
{this.checkPasswordLength(password) ? 'Password must be at least 5 characters' : ''}
</span>
<span style={{ color: this.checkPasswordSymbol(password) ? 'red' : 'grey' }}>
{this.checkPasswordSymbol(password) ? 'Password must contain a special character' : ''}
</span>
<span style={{ color: this.checkPasswordNumber(password) ? 'red' : 'grey' }}>
{this.checkPasswordNumber(password) ? 'Password must contain a number' : ''}
</span>
<span style={{ color: this.checkPasswordUpperCase(password) ? 'red' : 'grey' }}>
{this.checkPasswordUpperCase(password) ? 'Password must contain an uppercase letter' : ''}
</span> 
```
Added checks before proceeding with unchecked passwords
```
<ButtonSolid
disabled={
password?.length < 5 ||
this.checkPasswordNumber(password) ||
this.checkPasswordSymbol(password) ||
this.checkPasswordUpperCase(password) ||
password_confirmation?.length < 5 ||
isLoading ||
password.length !== password_confirmation.length
}
onClick={this.handleClick}
className="reset-password-btn"
data-cy="reset-password-button"
> ....
```

### CODE REVIEW

**Review by gsmithun4 — CHANGES_REQUESTED** [review]
This issue is for just changing a text 
`Password must be at least 5 characters` to 
`Password should be at least 5 characters`

**Comment by jaymehta002** [comment]
will create another repo with required changes

**Comment by PriteshKiri** [comment]
@jaymehta002 any updates on this?

**Comment by jaymehta002** [comment]
Created another PR #10060

**Comment by PriteshKiri** [comment]
Thanks for the update @jaymehta002

**Pull request closed without merging**
