### PR TITLE
Update widgetConfig.js

### PR DESCRIPTION
**Pull request by laurisseau**
Added backgroundColor: { value: '#fff00000' } in widgetConfig.js
Line: 1841

### CODE REVIEW

**Comment by donno2048** [comment]
Seems spammy (@Navaneeth-pk)

**Comment by Navaneeth-pk** [comment]
@laurisseau can you please mention the issue in PR description?

**Comment by laurisseau** [comment]
@Navaneeth-pk  how do i do that

**Comment by withshubh** [comment]
> @Navaneeth-pk how do i do that

Just click on the edit button on the top-right of the description and the add `fixes #issuenumber` or simply add the URL of the issue that this PR fixes.

Screenshot 2022-10-04 at 2 00 04 PM

**Comment by withshubh** [comment]
Hey @laurisseau 
Please share the link to the issue that is fixed by this PR?

**Pull request closed without merging**
