### PR TITLE
[Improvement] : Filepicker widget

### LINKED ISSUE #3020: Improvement to File Picker Widget
### Description

1. Clicking on the dropzone with the selected file(s) makes the list disappear
2. For A file which is greater than the max file size specified, an error message is displayed with the file size in bytes (which should be in MB or KB ideally)
3. If we select files more than the Max file count, the number of error toasts displayed is equal to the number of selected files.

### PR DESCRIPTION
**Pull request by manishkushare**
Resolve #3020

[x] Clicking on the dropzone with the selected file(s) makes the list disappear
[x] a file which is greater than the max file size specified, an error message is displayed with the file size in bytes (which should be in MB or KB ideally)
[x] fire fewer toasts for the same errors from different files

### CODE REVIEW

**Review by sherfin94 — CHANGES_REQUESTED** [review]
@manishkushare There are conflicts in this as I just merged your other filepicker changes. Please resolve the conflicts.

**Comment by sherfin94** [comment]
I set max size to `2000` bytes, selected a file and the message shown says max size is `77.91` kilobytes. This max size changes when I select a different file.

image

**Comment by sherfin94** [comment]
Clicking on the drop-zone still makes the list disappear, when we cancel the dialog box:


https://user-images.githubusercontent.com/20333972/169905090-aa26c836-f677-44ce-b018-8e038197d74c.mov


Since we're not showing the dropzone anyway when there are 1 or more files, lets not show it if the dialog is closed either?

**Comment by arpitnath** [comment]
> Clicking on the drop-zone still makes the list disappear, when we cancel the dialog box:
> 
>  Screen.Recording.2022-05-24.at.2.27.58.AM.mov 
> Since we're not showing the dropzone anyway when there are 1 or more files, lets not show it if the dialog is closed either?

resolved

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
