### PR TITLE
Show confirmation dialog when deleting a group

### LINKED ISSUE #1169: Ask for confirmation before deleting user groups
image

When the `delete` option is clicked, we need to show a confirmation dialog.

Example for the confirmation dialog: 
This dialog is shown when a user deletes an application.
image

### PR DESCRIPTION
**Pull request by trevorbayless**
Resolves #1169 

Heroku deploy: https://tooljet-pr.herokuapp.com

https://user-images.githubusercontent.com/3620552/138574903-8a2936b1-2812-4b94-8993-27fc80a1c4e4.mp4

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
Can you please fill our Hacktoberfest form? https://app.tooljet.io/applications/hacktoberfest-2021-form
@trevorbayless

**Comment by trevorbayless** [comment]
@Navaneeth-pk I filled it out a few weeks ago, and just received the automated confirmation email yesterday. Did you need me to fill it out again?

**Comment by Navaneeth-pk** [comment]
Sorry for the inconvenience, there was an issue with the form initially, some of the fields were not getting saved due to a misconfiguration. Will be great if you can fill the form once again.
@trevorbayless

**Comment by trevorbayless** [comment]
No problem at all! I just finished filling it out again. @Navaneeth-pk

**Pull request merged**
