### PR TITLE
Fixed failing manage SSO spec in multi workspace

### PR DESCRIPTION
**Pull request by alammoiz**
@emidhun 
Fixed https://github.com/ToolJet/ToolJet/issues/4391, please merge this https://github.com/ToolJet/ToolJet/pull/4509 PR b/c some fixed are depends on that

Screenshot 2022-10-29 at 1 15 57 AM

### CODE REVIEW

**Comment by ajith-k-v** [comment]
@alammoiz Please resolve the merge conflict

**Comment by alammoiz** [comment]
> @alammoiz Please resolve the merge conflict

resolved

**Comment by ajith-k-v** [comment]
@alammoiz  The spec is failing. Please take a look 
Screenshot 2022-10-31 at 6 25 10 PM

**Comment by alammoiz** [comment]
> @alammoiz The spec is failing. Please take a look Screenshot 2022-10-31 at 6 25 10 PM

Resolved

**Comment by alammoiz** [comment]
> > @alammoiz The spec is failing. Please take a look Screenshot 2022-10-31 at 6 25 10 PM
> 
> Resolved, @ajith-k-v

**Review by ajith-k-v — APPROVED** [review]
@alammoiz LGTM
Screenshot 2022-10-31 at 7 03 08 PM

**Comment by withshubh** [comment]
Hey @alammoiz  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
