### PR TITLE
Refactor/Issue-7521-Updated-Description

### PR DESCRIPTION
**Pull request by DarrenDsouza7273**
Updated The Description in the widgetConfig.js and en.json files
Issue #7521

### CODE REVIEW

**Comment by DarrenDsouza7273** [comment]
@karan-rathod-316

**Review by tejakummarikuntla — CHANGES_REQUESTED** [review]
Hey @DarrenDsouza7273 , I'd request you to go through the issue details and address the required changes in one more file: `en.json`

I was able to find the changes only in `widgetConfig.js`. Kindly make the changes in `en.json` as well.

**Comment by DarrenDsouza7273** [comment]
> Hey @DarrenDsouza7273 , I'd request you to go through the issue details and address the required changes in one more file: `en.json`
> 
> I was able to find the changes only in `widgetConfig.js`. Kindly make the changes in `en.json` as well.

ok ill do the changes

**Comment by DarrenDsouza7273** [comment]
@karan-rathod-316 @tejakummarikuntla Please verify now

**Comment by kavinvenkatachalam** [comment]
Hey @DarrenDsouza7273 ,


Thanks for the PR. Seems like the base branch is behind a few commits and it is showing unwanted file changes in your PR. Please update your develop with the latest changes or revert the unwanted changes.

image

image

**Comment by tejakummarikuntla** [comment]
Hey @DarrenDsouza7273, were you able to look into the comments? Could you let us know if you can take it up? Else, we might need to close the PR due to inactivity. Thank you!

**Comment by tejakummarikuntla** [comment]
Closing the PR due to contributor inactivity.

**Pull request closed without merging**
