### PR TITLE
fix: datepicker widget date and time selection in dark mode

### LINKED ISSUE #6271: [dark mode] fix color of time selection box in datepicker
### What is the current behaviour?
In dark mode, the color of the time selection box in datepicker should be dark.

### How to reproduce the issue?
1. Switch to dark mode
2. drag a datepicker
3. enable time selection from datepicker property
4. Check the color of the Time selection box

### Screenshots or Screencast
Screenshot 2023-05-05 at 6 00 14 PM

### PR DESCRIPTION
**Pull request by iSatVeerSingh**
### What is the current behaviour?
In dark mode, the color of the time selection box in the date picker should be dark.

Fixes #6271

### NOTE:- I couldn't find any solution to style time selector (Browser user agent time picker). Not even::-webkit pseudo-elements for this.

https://github.com/ToolJet/ToolJet/assets/85070570/fcfea688-40fe-4656-895c-e5f6a3a643fd

### CODE REVIEW

**Comment by iSatVeerSingh** [comment]
Please someone review this

**Review by stepinfwd — CHANGES_REQUESTED** [review]
input[type="time"]::-webkit-calendar-picker-indicator {
  filter: invert(1);
}

This snippet can be used to change the color of clock icon , try to club it with a classname in custominput or in datepicker component class

**Comment by stepinfwd** [comment]
> Please someone review this

Requested a small change rest of the things looks good

**Comment by tejakummarikuntla** [comment]
Hey @iSatVeerSingh, were you able to make progress with the requested changes?

**Comment by tejakummarikuntla** [comment]
Hey @iSatVeerSingh, were you able to make progress with the requested changes?

**Comment by iSatVeerSingh** [comment]
Sorry, I am not available.

**Pull request closed without merging**
