### PR TITLE
Template: Created placeholder image generator

### LINKED ISSUE #10888: Community template: Placeholder Image Generator
**Description:**
The Placeholder Image Generator template creates customizable placeholder images for web development, design, or content use, allowing users to specify size, colors, format, and custom text.

**Template feature list:**
Please check [here](https://docs.google.com/document/d/1zD0lfozBjuectZlApzq5s6y5RHZ3KW0CSHiuQKsYzYk/edit?usp=sharing)

**Template guidelines:**
Please check [here](https://docs.google.com/document/d/1lSXOpU4zXK8lsnF6Afbz1Qle_wW10ytLDV75II7K6yM/edit?usp=sharing)

**Template deadline:**
Upon assignment of a template development task, you must complete the development process within **7 working days** and submit the Pull Request (PR) for testing. If a delay is anticipated, promptly notify the ToolJet team via the [#contributors](https://tooljet.slack.com/archives/C05SSQF138F) Slack channel.
Failure to complete the development within **7 working days** or provide a response regarding any potential delays may result in the reassignment of the PR to other available community developers.

### PR DESCRIPTION
**Pull request by SanchitMahajan236**
Closes #10888
This pull request adds a placeholder image generator template to the project.

New feature addition:

Added a manifest and definition file that defines the placeholder image generator, including its name, description, widgets, sources, ID, and category.

https://github.com/user-attachments/assets/caf8377c-d22a-409a-bdcb-2c665f2132eb

@GrowwithNaveen @karan-rathod-316 @abhinabaadhikari 
Please review the PR.

### CODE REVIEW

**Comment by SanchitMahajan236** [comment]
Hi @GrowwithNaveen , the issue of the black screen is because of the color picker component of tooljet not working properly.
This explain the issue better. When I load the template, we get this screen :- 

Screenshot 2024-10-21 215158

This issue is due to the fact that the color picker component is not working properly with the default color I set in it. By default, the function of color picker is not giving any value you can see from the screenshot attached below.

Screenshot 2024-10-21 220015

As you can observe from the screenshot that the default value is #9b9b9b for the color but when I write the query to retrieve the color, it gives me the value #000000.

Can you please help me to mitigate this issue ?

**Comment by SanchitMahajan236** [comment]
@GrowwithNaveen please see the comment above and suggest a way to solve this issue

**Comment by GrowwithNaveen** [comment]
Hi @SanchitMahajan236, we tried to reproduce the issue, but it appears to be working fine. Could you try this workaround?
Run a JS query on page load to set the color picker values. 

Note: Ensure the default colors for the color pickers differ from those set by the JS query—adjusting the hex code's alpha value could also work.

**Comment by PriteshKiri** [comment]
Hey @SanchitMahajan236 

Any updates on this?

**Comment by PriteshKiri** [comment]
Closing the PR due to lack of progress

**Pull request closed without merging**
