### PR TITLE
Add scrollable for the user groups

### PR DESCRIPTION
**Pull request by SRIKARREDDY-dotorg**
**Summary of Changes:**

**1. Added Scrollable Mixin:**

- Created a reusable SCSS mixin named scrollable to standardize the styling of scrollable areas.
- The mixin sets the max-height, overflow-y, and custom scrollbar styles.
- Default height is set to 50vh, which can be customized through the $max-height parameter.

**2. Applied Mixin to Multiple Components:**

- **User Groups Component:** Updated to use the scrollable mixin, ensuring consistent scrolling behavior and styling for long lists of user groups.
- **Users Table Component:** Applied the mixin to the tbody of the users table, making it scrollable and visually consistent with other components.
- **Data Sources Component:** Incorporated the scrollable mixin to manage the scrolling of data source lists efficiently.

**Benefits:**

- **Consistency:** Provides a unified look and feel for scrollable areas across different components.
- **Usability:** Enhances user experience by ensuring scrollbars are styled consistently and functionally.
- **Reusability:** Simplifies maintenance and updates by using a single mixin for scrollable areas.

**Testing**
- Tested on my local machine 
[Screen Recording 2024-09-13 at 9.41.03 AM.zip](https://github.com/user-attachments/files/16988409/Screen.Recording.2024-09-13.at.9.41.03.AM.zip)

### CODE REVIEW

**Comment by rudeUltra** [comment]
Hey @SRIKARREDDY-dotorg great job using a reusable mixin but could you only add it to the user groups, other contributors have created PR's for the users and data sources page Thanks.

**Comment by rudeUltra** [comment]
@SRIKARREDDY-dotorg Yeah go ahead

**Comment by SRIKARREDDY-dotorg** [comment]
FYI, I had already signed Contributor License agreement.

**Comment by SRIKARREDDY-dotorg** [comment]
Can you please check the latest changes?

**Comment by SRIKARREDDY-dotorg** [comment]
Hi Any updates on the new changes?

**Comment by rudeUltra** [comment]
Hey @SRIKARREDDY-dotorg  sorry for the delay, could you try making the change by not changing tab-content CSS, it's used in a lot of places so it can break something, try adding a new CSS class for User group and use the mixin,
Thanks

**Comment by PriteshKiri** [comment]
Hey @SRIKARREDDY-dotorg,

Can you please update the PR with the changes mentioned by @rudeUltra ?

**Comment by SRIKARREDDY-dotorg** [comment]
ACK

**Comment by SRIKARREDDY-dotorg** [comment]
I have updated, let's close this. it's been there for a long time.

**Review by rudeUltra — APPROVED** [review]

**Comment by SRIKARREDDY-dotorg** [comment]
Merging is blocked by CLA, even after agreement. Could you please check or refresh the status?

**Comment by PriteshKiri** [comment]
@SRIKARREDDY-dotorg your PR has been approved. Will get merged soon.

**Pull request merged**
