### PR TITLE
changed Editing version -> App version in Editor.jsx

### LINKED ISSUE #893: Style changes for label displaying app version
### Is your proposal related to a problem?

Presently, app version is displayed this way:

image

### Describe the solution you'd like

Make it this way
image

### PR DESCRIPTION
**Pull request by Pockerman20**
fix #893

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
Thanks for contributing to ToolJet. Can you please fill up our Hacktoberfest form?https://app.tooljet.io/applications/hacktoberfest-2021-form
@Pockerman20

**Comment by Pockerman20** [comment]
Thanks for merging my PR.
The link provided by you is not responding.

Thanks

**Comment by Navaneeth-pk** [comment]
@Pockerman20 Are you accessing the form from a mobile device?

**Comment by Pockerman20** [comment]
Yes

**Comment by arpitnath** [comment]
@Pockerman20 
Thanks for contributing to ToolJet again. Would you mind filling up our Hacktoberfest form to confirm your swags? 
https://app.tooljet.io/applications/hacktoberfest-2021-form

**Pull request merged**
