### PR TITLE
styles: fixes in workspace dark mode

### LINKED ISSUE #4385: The workspace switching arrow appears only when hovered over in dark mode
### Is your proposal related to a problem?

The option to switch the workspace has an arrow that is not visible in the dark mode until the cursor hovers over the workspace name.

### Describe the solution you'd like

Make the cursor and workspace image visible in dark mode.

### Steps to reproduce the issue
- Toggle dark mode 
- Go to the dropdown on the navbar 
- Hover over the workspace name

Screenshot 2022-10-12 at 2 02 03 PM
Screenshot 2022-10-12 at 2 01 46 PM

### PR DESCRIPTION
**Pull request by KushalRaut**
Fixes #4385

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
@KushalRaut please add screenshots of the change so that it is easier to review.

**Comment by KushalRaut** [comment]
Here are some screenshots of the fix:
Without hover
image
With Hover
image

**Comment by gsmithun4** [comment]
deployed https://tj-4440.herokuapp.com/

**Review by gsmithun4 — CHANGES_REQUESTED** [review]
Hi @KushalRaut The light mode style is broken. Workspace avatar background should be darker
Screenshot 2022-10-24 at 11 49 15 PM

**Review by kavinvenkatachalam — APPROVED** [review]
LGTM

**Comment by withshubh** [comment]
Hey @KushalRaut   
Thanks for contributing to ToolJet. :raised_hands: 
While this PR is under review, you can submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

**Pull request merged**
