### PR TITLE
[cypress] Fix failing manage SSO spec in single workspace #4390

### PR DESCRIPTION
**Pull request by alammoiz**
Fixed https://github.com/ToolJet/ToolJet/issues/4390, added login-logo and removed extra dropdown

### CODE REVIEW

**Comment by alammoiz** [comment]
> Hi @alammoiz, I think the change you have made in commands.js may affect all the specs since we have to check the `Homepage logo` after each UI login. For me, the spec is still failing on disabling Google SSO. Please have a look into that.
> 
> Screenshot 2022-10-19 at 4 56 46 AM

Please check now @emidhun , I have added cy.wait(1000);

Screenshot 2022-10-19 at 5 44 47 PM

**Review by emidhun — CHANGES_REQUESTED** [review]
Hi @alammoiz,
I saw in the screenshot only one test case is passing and the rest three are failing.
Could you please have a look into that?
I think it is better to have the required changes only, Could you please disable your prettier before adding changes?

**Comment by alammoiz** [comment]
> Hi @alammoiz, I saw in the screenshot only one test case is passing and the rest three are failing. Could you please have a look into that? I think it is better to have the required changes only, Could you please disable your prettier before adding changes?

Hi @emidhun ,
Updated test case, it failed in 2 places didn't find a Google and GitHub Singin button on login. How can these button show on the login page? or May be it works fine on prod.

Screenshot 2022-10-20 at 4 37 23 PM

Screenshot 2022-10-20 at 4 38 00 PM

**Review by emidhun — CHANGES_REQUESTED** [review]
Hey @alammoiz 
Could you please revert the indentation changes and add the required changes only?

**Comment by alammoiz** [comment]
> Hey @alammoiz Could you please revert the indentation changes and add the required changes only?

sure

**Comment by alammoiz** [comment]
> Hey @alammoiz Could you please revert the indentation changes and add the required changes only?

You can check now

**Comment by ajith-k-v** [comment]
@alammoiz  The git SSO test is failing. Could you please have a look into that?

Screenshot 2022-10-29 at 8 33 16 AM

**Comment by alammoiz** [comment]
> @alammoiz The git SSO test is failing. Could you please have a look into that?
> 
> Screenshot 2022-10-29 at 8 33 16 AM

Actually it's git login button not appearing on login, that's why it's failing. I Didn't find a Google and GitHub Singin button on login. How can these button show on the login page?

**Comment by ajith-k-v** [comment]
@alammoiz  Please add this to your .env
`SSO_GOOGLE_OAUTH2_CLIENT_ID=
SSO_GIT_OAUTH2_CLIENT_ID=
SSO_GIT_OAUTH2_CLIENT_SECRET=`

**Comment by alammoiz** [comment]
> SSO_GOOGLE_OAUTH2_CLIENT_ID= SSO_GIT_OAUTH2_CLIENT_ID= SSO_GIT_OAUTH2_CLIENT_SECRET=

It's a config part. It works fine, I have done the indentation changes that @emidhun suggest. Please check it.

**Comment by ajith-k-v** [comment]
@alammoiz Still the spec is failing. Could you please change the `gitSignInText` in `/cypress-tests/cypress/constants/texts/manageSSO.js  `
Screenshot 2022-10-31 at 1 16 21 PM

**Comment by alammoiz** [comment]
> gitSignInText

Fixed, Nice check

**Review by ajith-k-v — APPROVED** [review]
LGTM
Screenshot 2022-10-31 at 1 36 35 PM

**Review by emidhun — APPROVED** [review]
LGTM

**Pull request merged**
