### PR TITLE
[Bug]: Query Manager Bugfixes

### PR DESCRIPTION
**Pull request by kavinvenkatachalam**
Fixes the following bugs -

- Throws errors when we focus the query name input and un focus it
- Draft query is not visible
- Update name on draft query
- Showing unsaved changes modal on `tooljetDB` without any changes
- While toggling off the raw JSON on body brings you back to header in REST API

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-85zrh0qpq Draft query is not added in Query Manager](https://app.clickup.com/t/85zrh0qpq)

**Comment by shubh22** [comment]
Task linked: [CU-85zrgxkzg Error toast message is being displayed while no change in query name takes place.](https://app.clickup.com/t/85zrgxkzg)

**Comment by shubh22** [comment]
Task linked: [CU-85zrgx1c8 Trying to save query names without changes](https://app.clickup.com/t/85zrgx1c8)

**Comment by shubh22** [comment]
Task linked: [CU-85zrh1hyq Unsaved changes modal popping up on tooljetDB without any changes](https://app.clickup.com/t/85zrh1hyq)

**Comment by shubh22** [comment]
Task linked: [CU-85zrh23p2 While toggling off the raw JSON on body brings you back to header in REST API](https://app.clickup.com/t/85zrh23p2)

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hi @kavinvenkatachalam ,

The `Discard changes when there are no actual changes` issue  on TooljetDB is still there.

Also, when I discard them, the newly selected query is showing blank.

Please check

https://user-images.githubusercontent.com/20333972/210217143-c8e5ce4c-7a6e-4714-9494-43faacc99f58.mov

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
