### PR TITLE
Update Inspector.jsx

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
Fix to the issue #7714 
i have rename the widget component  in the confirmation modal of deleting component

### CODE REVIEW

**Comment by HeetVekariya** [comment]
@bilalmirza74 If i am correct the contributing.md says "Add a comment on the issue and wait for the issue to be assigned before you start working on it. This helps to avoid multiple people working on similar issues.",
Does it mean i have to wait for the issue to be assigned or just submit the PR  ??

**Comment by HeetVekariya** [comment]
> > @bilalmirza74 If i am correct the contributing.md says "**Add a comment on the issue and wait for the issue to be assigned before you start working on it. This helps to avoid multiple people working on similar issues**.", Does it mean i have to wait for the issue to be assigned or just submit the PR ??
> 
> now can you see any conflict in PR's

I am complaining about the PR but the manners that is to followed

**Comment by HeetVekariya** [comment]
> > > > @bilalmirza74 If i am correct the contributing.md says "**Add a comment on the issue and wait for the issue to be assigned before you start working on it. This helps to avoid multiple people working on similar issues**.", Does it mean i have to wait for the issue to be assigned or just submit the PR ??
> > > 
> > > 
> > > now can you see any conflict in PR's
> > 
> > 
> > I am not complaining about the PR but the manners that is to followed
> 
> sorry bro my bad i just saw the PR changes

- No worries, but what further action you are going to take, will you accept this PR or not

**Comment by HeetVekariya** [comment]
> @HarshitVashisht11 Follow the rules to do PR "Add a comment on the issue and wait for the issue to be assigned before you start working on it. This helps to avoid multiple people working on similar issues."

No worries 👍 , just asking you, if you can assign issues can you please assign other issue to me.

**Comment by arpitnath** [comment]
Hello, @HarshitVashisht11! 😄
@bilalmirza74 is not authorized to assign you any issues. Issues will be assigned to you by a maintainer. It's important to have an issue assigned to you before you begin working on it and create a pull request (PR). Otherwise, can be considered as **invalid**`

**Comment by tejakummarikuntla** [comment]
Hello @HarshitVashisht11, please refrain from raising Pull Requests for issues that have not been assigned to you. Thank you.

**Pull request closed without merging**
