### PR TITLE
[docs]Fix typos and grammatical errors in adding-widget.md

### PR DESCRIPTION
**Pull request by kVarunkk**
This PR fixes typos and grammatical errors in [documentaion](https://github.com/ToolJet/ToolJet/blob/develop/docs/docs/tutorial/adding-widget.md)

### CODE REVIEW

**Review by withshubh — APPROVED** [review]

**Comment by kVarunkk** [comment]
Hi @Navaneeth-pk, just had one doubt, how will I be contacted regarding the swags if I'm eligible?
Thanks!

**Comment by withshubh** [comment]
Hey @kVarunkk 

Thank you for your contribution. Only the issues with Hacktoberfest label are eligible for the swags.

Also, Please make sure to follow the contributing guidelines before creating the PR.

**Comment by kVarunkk** [comment]
> Hey @kVarunkk
> 
> Thank you for your contribution. Only the issues with Hacktoberfest label are eligible for the swags.
> 
> Also, Please make sure to follow the contributing guidelines before creating the PR.

Hey @withshubh, as I read on the [blog](https://blog.tooljet.com/hacktoberfest-2022/) of ToolJet, we can participate also by contributing to the documentation. So if you could clear this, It would be great!
Thanks!

**Comment by Navaneeth-pk** [comment]
Only the issues that we create with the `hacktoberfest` label is eligible for Hacktoberfest. 
@kVarunkk

**Pull request merged**
