### PR TITLE
[Feature]: Run query while Creating/Saving 

### LINKED ISSUE #3130: [Feature]: Save & Run button in Query Manager
### Is your proposal related to a problem?

While creating/updating the query, the user needs to save the query and run the query. This involves two steps and it is not intuitive.

### Describe the solution you'd like

We can replace the `save` button with `save & run` which runs the query after saving it

### If the feature is approved, would you be willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by kavinvenkatachalam**
Resolves #3130

### CODE REVIEW

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Hey @kavinvenkatachalam , `Create and run` works correctly, but `Save and run` doesn't seem to run the query.

https://user-images.githubusercontent.com/20333972/170957549-498a717b-1b16-479c-a8cd-0d6063e1268c.mov

**Comment by kavinvenkatachalam** [comment]
> Hey @kavinvenkatachalam , `Create and run` works correctly, but `Save and run` doesn't seem to run the query.
> 
>  Screen.Recording.2022-05-30.at.2.32.54.PM.mov

I'll look into it

**Comment by kavinvenkatachalam** [comment]
@sherfin94 Query is running fine. There is some issue with the `Table.jsx` in updating the new value. From the below screenshot,`tableData` has the updated value. But due to memo and none of the dependencies got changed, the variable `data` holds the old value which is why the table is not updated. 

image

**Comment by sherfin94** [comment]
> @sherfin94 Query is running fine. There is some issue with the `Table.jsx` in updating the new value. From the below screenshot,`tableData` has the updated value. But due to memo and none of the dependencies got changed, the variable `data` holds the old value which is why the table is not updated.
> 
> image

@kavinvenkatachalam When we run query by clicking on the `play` button or by means of some `Run query` action, the `data` of the query becomes `[]` while it is loading, and then it becomes the new data. This makes it easy for components to reflect the value. When when we run query while saving/creating, this does not seem to happen. Can we reuse the same way in which query is run when we click on the play button, here?. We might just have to reuse the corresponding function.

**Comment by kavinvenkatachalam** [comment]
> > @sherfin94 Query is running fine. There is some issue with the `Table.jsx` in updating the new value. From the below screenshot,`tableData` has the updated value. But due to memo and none of the dependencies got changed, the variable `data` holds the old value which is why the table is not updated.
> > image
> 
> @kavinvenkatachalam When we run query by clicking on the `play` button or by means of some `Run query` action, the `data` of the query becomes `[]` while it is loading, and then it becomes the new data. This makes it easy for components to reflect the value. When we run query while saving/creating, this does not seem to happen. Can we reuse the same way in which query is run when we click on the play button, here?. We might just have to reuse the corresponding function.

Got it. I'll check and reuse that functionality

**Review by sherfin94 — CHANGES_REQUESTED** [review]
When I click on `Save and run` without making any changes to the query, it seems to keep loading forever:
image

**Review by sherfin94 — CHANGES_REQUESTED** [review]
The query `create and run` button seems to crash the app when clicked. (save and run is working)

https://user-images.githubusercontent.com/20333972/173767930-6ae9d34a-b477-4b13-bae9-2cd985b7bf07.mov

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
