### PR TITLE
Feature :: select widget property on click

### LINKED ISSUE #3620: Select and access properties of  a widget on clicking over its area
### Is your proposal related to a problem?
Currently widget properties can only be accessed by clicking on its label header.

### Describe the solution you'd like
Select and access properties of  a widget on clicking over its area.

### If the feature is approved, would you be willing to submit a PR?
Yes.

### LINKED ISSUE #3628: [ BUG ] :: Clicking on close should take to widget list in widget panel 🐛
### What is the expected behaviour?
Clicking on close should take to widget list in widget panel

### What is the current behaviour?
Clicking on close we go to a intermediate state saying "Please select a component to inspect"
### How to reproduce the issue?

1.Click on label of any widget 
2.Close properties

### Screenshots or Screencast

https://user-images.githubusercontent.com/31006028/179496000-73d859a5-363a-4d76-bc2c-c94abbef247b.mov

### If the bug is confirmed, would you be willing to submit a PR?
Yes.

### LINKED ISSUE #3637: [ Feature ] :: Automatically selecting  properties on dropping widget to canvas
### Is your proposal related to a problem?

We now have to manually select  properties after dropping widget to canvas

### Describe the solution you'd like

Automatically selecting  properties on dropping widget to canvas

### If the feature is approved, would you be willing to submit a PR?
Yes.

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #3620 
closes #3637
closes #3628

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2hy3p7w Select a widget on clicking over its area](https://app.clickup.com/t/2hy3p7w)

**Comment by shubh22** [comment]
Task linked: [CU-2k5z4tp Select and access properties of  a widget on clicking over its area](https://app.clickup.com/t/2k5z4tp)

**Review by kavinvenkatachalam — DISMISSED** [review]

**Review by sherfin94 — CHANGES_REQUESTED** [review]
Please look into: 

1. When widget is deleted, show the widget manager
2. Look into button group widget
3. Resolve conflicts

**Comment by kavinvenkatachalam** [comment]
@stepinfwd Select widget onClick is already available in the develop by PR #3665. You can revert the changes related to the select widget onClick.

cc: @sherfin94

**Comment by sherfin94** [comment]
Closing as feature has already been implemented.

**Pull request closed without merging**
