### PR TITLE
[ Feature ] :: Reorder Table columns using drag and drop

### LINKED ISSUE #4285: Option to drag and drop columns in Table widget
### Is your proposal related to a problem?
Changing columns order through widget itself would be helpful in speeding up development .

### Describe the solution you'd like
Add option to drag and drop columns in Table widget

### If the feature is approved, would you be willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #4285

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2w9tf57 Reorder Table columns using drag and drop](https://app.clickup.com/t/2w9tf57)

**Comment by shubh22** [comment]
Task linked: [CU-2vjy9qm Drag and Drop columns (like excel) - Table widget](https://app.clickup.com/t/2vjy9qm)

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@stepinfwd Two issues I noticed,

1. The table header's width increased much compared to the existing widget. Can you check that?
2. When I drag the column, the dragged column preview is not placed near the cursor. Attaching the GIF

Oct-10-2022 10-52-32

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@stepinfwd The height issue seems to be fixed. But preview while dragging still exists. I guess it differs from one column to another. For ex, if I reduce the size of the column and drag it, it is not working properly. Can you please check it?

Oct-10-2022 17-37-45

**Review by sherfin94 — DISMISSED** [review]

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
