### PR TITLE
fixed dark mode inconsistency in query formation dialog box

### PR DESCRIPTION
**Pull request by DSY4444**
closed https://github.com/ToolJet/ToolJet/issues/6942

If dark mode is on and we click on eye icon  and then try to submit query it shows diaglog box with options "Cancel" and "Yes", this dialog box was not carrying dark mode.
I just passed darkMode state to Confirm Component in Viewer.tsx.

### CODE REVIEW

**Comment by DSY4444** [comment]
also closed issue https://github.com/ToolJet/ToolJet/issues/6945
which is a typo one converted "Tooljet" to "ToolJet"  in Select DataSource

**Review by tejakummarikuntla — COMMENTED** [review]
Hey @DSY4444 , to progress this for review,
could you please revert the changes addressing other issue #6945? Kindly make sure this PR addresses the issue that is assigned to you #6942 ; thanks for your understanding.

**Comment by DSY4444** [comment]
> Hey @DSY4444 , to progress this for review, could you please revert the changes addressing other issue #6945? Kindly make sure this PR addresses the issue that is assigned to you #6942 ; thanks for your understanding.

**Comment by DSY4444** [comment]
Sure @tejakummarikuntla I will revert those changes and raise PR again. sorry for misunderstanding.

**Review by stepinfwd — APPROVED** [review]

**Review by kavinvenkatachalam — APPROVED** [review]

**Pull request merged**
