### PR TITLE
Added Confirm password field for profile- change password section

### LINKED ISSUE #3108: Confirm password field for profile- change password section
### Is your proposal related to a problem?
There is no confirm password field in user profile page 

### Describe the solution you'd like
Add confirm password field and verify the new password and confirm password are same

### If the feature is approved, would you be willing to submit a PR?
No

### PR DESCRIPTION
**Pull request by Syed-Ansar**
Added Confirm password field for profile - change password section 

fixes #3108 

Validated the input fields.

Screenshot 2022-06-22 at 2 46 18 PM

### CODE REVIEW

**Comment by Syed-Ansar** [comment]
> Hi @Syed-Ansar please fix the lint issues

Okay. I will and I found that it has one edge case. Should I add it ?

**Comment by Syed-Ansar** [comment]
> > Hi @Syed-Ansar please fix the lint issues
> 
> Okay. I will and I found that it has one edge case. Should I add it ?

Sir How do I fix lint issues. I don't know.

**Comment by Syed-Ansar** [comment]
> > > > Hi @Syed-Ansar please fix the lint issues
> > > 
> > > 
> > > Okay. I will and I found that it has one edge case. Should I add it ?
> > 
> > 
> > Sir How do I fix lint issues. I don't know.
> 
> https://github.com/ToolJet/ToolJet/runs/7005287888?check_suite_focus=true these are the lint errors, install ESLint extension in your vs code, it will show the lint errors

I have ESLint extension but I didn't see any errors. I may be wrong.

**Comment by Syed-Ansar** [comment]
> > > > > Hi @Syed-Ansar please fix the lint issues
> > > > 
> > > > 
> > > > Okay. I will and I found that it has one edge case. Should I add it ?
> > > 
> > > 
> > > Sir How do I fix lint issues. I don't know.
> > 
> > 
> > https://github.com/ToolJet/ToolJet/runs/7005287888?check_suite_focus=true these are the lint errors, install ESLint extension in your vs code, it will show the lint errors
> 
> I have ESLint extension but I didn't see any errors. I may be wrong.

I have created another pull request for the same issue with some validations please review #3365 . If it is correct then I will close this one.

**Comment by gsmithun4** [comment]
> > > > > > Hi @Syed-Ansar please fix the lint issues
> > > > > 
> > > > > 
> > > > > Okay. I will and I found that it has one edge case. Should I add it ?
> > > > 
> > > > 
> > > > Sir How do I fix lint issues. I don't know.
> > > 
> > > 
> > > https://github.com/ToolJet/ToolJet/runs/7005287888?check_suite_focus=true these are the lint errors, install ESLint extension in your vs code, it will show the lint errors
> > 
> > 
> > I have ESLint extension but I didn't see any errors. I may be wrong.
> 
> I have created another pull request for the same issue with some validations please review #3365 . If it is correct then I will close this one.



> > > > > > Hi @Syed-Ansar please fix the lint issues
> > > > > 
> > > > > 
> > > > > Okay. I will and I found that it has one edge case. Should I add it ?
> > > > 
> > > > 
> > > > Sir How do I fix lint issues. I don't know.
> > > 
> > > 
> > > https://github.com/ToolJet/ToolJet/runs/7005287888?check_suite_focus=true these are the lint errors, install ESLint extension in your vs code, it will show the lint errors
> > 
> > 
> > I have ESLint extension but I didn't see any errors. I may be wrong.
> 
> I have created another pull request for the same issue with some validations please review #3365 . If it is correct then I will close this one.

Yes, you can close this one

**Pull request closed without merging**
