### PR TITLE
Fixed ManageSSO left menu background color in Dark-theme.

### PR DESCRIPTION
**Pull request by Syed-Ansar**
Fixed issue #3396 

### Dark Theme

d

### Light Theme

l

### CODE REVIEW

**Comment by Syed-Ansar** [comment]
Hey @withshubh Can you review this PR for issue #3396

**Comment by gsmithun4** [comment]
Deployed 
https://tj-3399.herokuapp.com/

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Cases
Test Case | Steps | Result
-- | -- | --
Should be able to clearly view the details on manage sso in dark mode. | Click on dark theme icon. | The application gets in dark theme.
  | Hover over my workspace. | Options are displayed.
  | Click on Manage SSO. | The details are clearly visible.
  | Click on options like Google, GitHub, Password Login. | The details are clearly visible.


</body>
</html>

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test Case

Test Case | Steps | Result
-- | -- | --
Should be able to clearly view the details on manage sso in dark mode. | Click on dark theme icon. | The application gets in dark theme.
  | Hover over my workspace. | Options are displayed.
  | Click on Manage SSO. | The details are clearly visible.
  | Click on options like Google, GitHub, Password Login. | The details are clearly visible.


</body>
</html>

**Review by gsmithun4 — APPROVED** [review]
LGTM

**Pull request merged**
