### PR TITLE
Added check to see if workspace name exists, and blocks duplicates

### PR DESCRIPTION
**Pull request by Nathan-Bisson**
Fixes: #3028

### CODE REVIEW

**Comment by shubh22** [comment]
Task linked: [CU-2hy3p7w Select a widget on clicking over its area](https://app.clickup.com/t/2hy3p7w)

**Comment by gsmithun4** [comment]
> Task linked: [CU-2hy3p7w Select a widget on clicking over its area](https://app.clickup.com/t/2hy3p7w)

Attached wrong ticket

**Review by gsmithun4 — APPROVED** [review]
LGTM

**Comment by gsmithun4** [comment]
deployed https://tj-3618.herokuapp.com

**Comment by Nandinisaha13** [comment]
<html>
<body>
<google-sheets-html-origin>Test case

Test Case | Steps | Result
-- | -- | --
Should not be able to create a duplicate workspace. | Hover over workspace name. | Options are displayed.
  | Click on add workspace. | New pop up opens for workspace name.
  | Add previous workspace name & click enter. | Error toast as workspace already exists is displayed.


</body>
</html>

**Pull request merged**
