### PR TITLE
Bugfix :: wraping all text in statistics widget

### LINKED ISSUE #2089: Bugfix :: ui bugs in statistics widget
### What is the expected behaviour?
test to be wrapped for every value and label in widget
improvement : primary value can be made number only
dark theme border colour to be changed 

### What is the current behaviour?
Text is not wrapped , it overflows outside
Primary value  is string
Border colour in dark theme not as specified in design

### How to reproduce the issue?

1.Write long text inside statistics widget
2.Write string inside primary value
3.Observe border colour in dark theme

### Screenshots or Screencast
Screenshot 2022-02-01 at 11 31 39 AM

### PR DESCRIPTION
**Pull request by stepinfwd**
closes #2089

### CODE REVIEW

**Comment by Navaneeth-pk** [comment]
image
The primary value is being cut off.

**Comment by sherfin94** [comment]
The arrow icon which was properly positioned, does not look like its properly positioned anymore.

before: 
image

after: 
image

**Review by sherfin94 — CHANGES_REQUESTED** [review]
I've commented one issue, otherwise looks good 👍

**Comment by stepinfwd** [comment]
updated @sherfin94

**Review by sherfin94 — APPROVED** [review]

**Pull request merged**
