### PR TITLE
updating the INFO section

### PR DESCRIPTION
**Pull request by krimoelbahri**
I added a line to mention Updating "table1" with the name the user uses.

issue : https://github.com/ToolJet/ToolJet/issues/4987

### CODE REVIEW

**Comment by withshubh** [comment]
Hey @krimoelbahri - Thanks for creating the PR. Please link the issue in the PR description.

**Review by withshubh — CHANGES_REQUESTED** [review]
In every bullet point, there are 3 unnecessary spaces. Please keep it one else the docs will break.

**Comment by krimoelbahri** [comment]
hello @withshubh

**Comment by withshubh** [comment]
Please update in all the versions (v1 - v2.6) and also on the base directory `tooljet/docs/docs`
@krimoelbahri

**Review by withshubh — APPROVED** [review]

**Pull request merged**
