### PR TITLE
Feature/add toast close button

### PR DESCRIPTION
**Pull request by DonRomaniello**
Feedback implemented.

Added close button to all toasts, with dark mode as well.

### CODE REVIEW

**Review by kavinvenkatachalam — COMMENTED** [review]
Hey @DonRomaniello,

Changes are looking good! Could you please remove/discard the files from the PR which are not related to this PR? 

`plugins/package-lock.json`
`plugins/packages/woocommerce/lib/operations.json`

**Review by gsmithun4 — CHANGES_REQUESTED** [review]
`plugins/package-lock.json` please revert the changes

**Review by DonRomaniello — COMMENTED** [review]
Thank you for your patience. I hope this resolves the issues outlined.

**Review by kavinvenkatachalam — CHANGES_REQUESTED** [review]
@DonRomaniello Still I can see the changes related to `package-lock.json` and `plugins/packages/woocommerce/lib/operations.json` in the PR. Can you please revert the changes?

**Comment by withshubh** [comment]
Hey @DonRomaniello 👋 
Please make the changes requested above?

**Comment by withshubh** [comment]
Hey @DonRomaniello 👋 
I hope you're doing good. Do you want to continue working on this PR?

**Comment by kavinvenkatachalam** [comment]
Closing this and created a new PR #3821

**Pull request closed without merging**
