### PR TITLE
fix: Changed widget to component

### PR DESCRIPTION
**Pull request by HeetVekariya**
# Fixes issue:
- Issue: https://github.com/ToolJet/ToolJet/issues/7714
- Correction in inspector.jsx

<br> 

# Changes to be made:
- Change ```Widget``` to ```Component```

<br>

# Files changed:
- Inspector.jsx (frontend/src/Editor/Inspector/Inspector.jsx)

<br>

# Total changes: 1

### CODE REVIEW

**Review by Ckbhatia — COMMENTED** [review]
Looks all good!

**Comment by HeetVekariya** [comment]
@tejakummarikuntla WIll this PR be get merged ?

**Comment by HeetVekariya** [comment]
Is there any thing wrong with the PR, that is to be corrected ?

**Comment by HeetVekariya** [comment]
@tejakummarikuntla Is there anything left from my side for this PR ?

**Comment by HeetVekariya** [comment]
Thank you for merging the PR

**Pull request merged**
