### PR TITLE
Feature/tags widget

### PR DESCRIPTION
**Pull request by shah21**
Related to #1644

### CODE REVIEW

**Comment by sherfin94** [comment]
Lets make the tags have the same height as button component

image

**Comment by sherfin94** [comment]
If the grid of tags goes outside the height of the widget, then there should be horizontal scroll:

image

**Comment by sherfin94** [comment]
Lets have a little space between vertically stacked tags
image

**Comment by sherfin94** [comment]
Each tag should have separate text color also, just like tag color.

image

**Comment by sherfin94** [comment]
Finally, currently when a tag is created, it says tag1 tag2 etc, instead of that, lets have 4 tags that goes: 'success'(green), info (blue), warning (yellow) and danger(red)

**Review by sherfin94 — CHANGES_REQUESTED** [review]
I've added the required changes as comments..

**Comment by shah21** [comment]
> Finally, currently when a tag is created, it says tag1 tag2 etc, instead of that, lets have 4 tags that goes: 'success'(green), info (blue), warning (yellow) and danger(red)

You mean the default tags, right?

**Comment by sherfin94** [comment]
image

Hey @shah21 , some changes are required,

- The scrollbar is unnecessarily shown, check screenshot, show it only if necessary
- The bottom corners of the tags are rounded, whereas the top corders are sharp, like a rectangle: Make it so, that all corners are rounded
- The tags now expand as we increase the height of the widget, lets just have the tags take the same height that they come in https://preview.tabler.io/docs/badges.html
- The initial default colors that we apply when tags widget is created, lets select from the colors shown in the page: https://preview.tabler.io/docs/badges.html, with the same labels that you've already set.

**Review by sherfin94 — CHANGES_REQUESTED** [review]
@shah21 Two more items to go,

- Since we're accepting text color via data itself, the text color property on style section is not useful any more. Let's remove that.
- Specify in documentation that text color can also be set through data

**Review by sherfin94 — DISMISSED** [review]

**Comment by shah21** [comment]
> @shah21 Could you merge develop locally into this branch and push? There are are conflicts.

Okay,I will do that

**Review by Navaneeth-pk — APPROVED** [review]

**Pull request merged**
